### ISSUE TITLE
Implement "default" interface methods introduced in Java 8

### ISSUE THREAD

**Issue by mbenz89** [soot-oss/soot#1062]
Java 8 introduces _default_ methods for interfaces that contain a default implementation of an interface method. (https://docs.oracle.com/javase/tutorial/java/IandI/defaultmethods.html)

Soot does currently not handle this construct and has to be extended for it.

Related to #1054
Maybe related to #956

**Comment by mbenz89** [comment]
Solution: soot.SootMethodRefImpl#tryResolve(java.lang.StringBuffer) has to deal with interfaces as well.

**Comment by amishra123** [comment]
I would be interested to work on this.

**Comment by anddann** [comment]
@amishra123 Thanks!
We welcome your participation?
Do you want to do it alone or should we implement this feature together?

**Comment by mbenz89** [comment]
@amishra123 Great to hear! Let us know if you have questions.

**Comment by amishra123** [comment]
> @amishra123 Thanks!
> We welcome your participation?
> Do you want to do it alone or should we implement this feature together?

Either ways is fine with me. Let me come up with an implementation and I'll let you know if I need help. Thanks.

**Comment by anddann** [comment]
This is a duplicate of  issue #1054.
@amishra123 Did you make any progress or need support?

**Comment by mbenz89** [comment]
done with https://github.com/soot-oss/soot/pull/1221
