### ISSUE TITLE
Converting jimple to dex is very slow! Is there something wrong? How to speed up?

### ISSUE THREAD

**Issue by CbcWestwolf** [soot-oss/soot#1183]
For some reasons I need to use Soot to convert jimple to dex but I found the speed is very slow. For a test app with the size of 17.8 KB and less than 20 jimple files, Soot takes at least 6 mins to convert! Here is my command. Is there anything I can do to improve the converting speed? It seems that Soot takes much time on "Call Graph"?

> jdklib='/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/'
> jarlist=$(find $jdklib -name "*.jar"|xargs|sed "s/ /:/g")
> jdkjars=$jarlist
> soottrunk='~/Desktop/sootclasses-trunk.jar'
> java -jar $soottrunk soot.Main -w -v -allow-phantom-refs \\
-force-android-jar "/home/cbc/android-sdk/platforms/android-28/android.jar" \\
--src-prec J --cp $jdkjars':'$soottrunk -process-dir $1 --d $2 --java-version 1.8 --output-format dex

**Comment by MarcMil** [comment]
You should not need a call graph for writing out Dex files. Probably soot generates one because of the whole-program-mode (-w). What happens if you run soot without that mode?
