### ISSUE TITLE
After updating Soot from 3.3 to 4.2, "Exception in thread "main" java.lang.RuntimeException: None of the basic classes could be loaded! Check your Soot class path!"

### ISSUE THREAD

**Issue by CbcWestwolf** [soot-oss/soot#1379]
```java
public static void loadClasses(String classespath) {
        G.reset();

        // initialization for soot environment
        Options.v().set_allow_phantom_refs(true);
        Options.v().set_allow_phantom_elms(true);
        Options.v().set_ast_metrics(true);
        Options.v().set_whole_program(true);
        Options.v().set_prepend_classpath(true);
        Options.v().set_src_prec(Options.src_prec_class); // use class files for input
        Options.v().set_app(true);
        Options.v().set_verbose(true);

        // set goal dir for soot to load and analysis
        Options.v().set_soot_classpath(".:" + classespath + ":" + "rt.jar");
        Options.v().set_soot_modulepath(classespath);
        Options.v().set_process_dir(new ArrayList<String>(Collections.singletonList(classespath)));
        Scene.v().setSootClassPath(classespath);
        Scene.v().loadNecessaryClasses();
    }
```
I used the code above to load all the class files in the dir-path `classespath` because I want to modify some `Body`s of the methods. In Soot 3.3, the code works. But after I update Soot to 4.2, one exception happened: 
> Exception in thread "main" java.lang.RuntimeException: None of the basic classes could be loaded! Check your Soot class path!
	at soot.ModuleScene.loadBasicClasses(ModuleScene.java:505)
	at soot.ModuleScene.loadNecessaryClasses(ModuleScene.java:520)
	at Utils.loadClasses(Utils.java:108)
	at Test.main(Test.java:42)

How should I modify my code to load the classes? My desktop is Ubuntu 18.04 and the jdk version is 8.

Thanks!

**Comment by mbenz89** [comment]
It might be that using the 'set_module_path' option instructs soot to search the basic classes in Java modules instead of the rt jar which fails on your side due to having a jdk8. The solution would be to omit this option then. Can you second this @anddann?

**Comment by CbcWestwolf** [comment]
I get the same exception information whether omitting `set_module_path` or not. So are there any other possible solutions? 
Thanks!

**Comment by anddann** [comment]
yes @mbenz89 , we should throw an exception for such an invalid configuration

**Comment by CbcWestwolf** [comment]
My jdk's information is 
> openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~18.04-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)

The classes I am trying to analyze is also java se 8.
Thanks!

**Comment by anddann** [comment]
okay, what code are you invoking in at
Utils.loadClasses(Utils.java:108) and Test.main(Test.java:42)

**Comment by anddann** [comment]
Mhh, the configuration has some clashing arguments, what do you think @mbenz89 

```
        Options.v().set_app(true);
        Options.v().set_soot_classpath(".:" + classespath + ":" + "rt.jar");
        Options.v().set_soot_modulepath(classespath);
        Options.v().set_process_dir(new ArrayList<String>(Collections.singletonList(classespath)));
        Scene.v().setSootClassPath(classespath);
        Scene.v().loadNecessaryClasses();

```

should be sufficient to set

`        Options.v().set_soot_classpath(".:" + classespath + ":" + "rt.jar");
`

**Comment by CbcWestwolf** [comment]
The two top-level methods are below.
Test.main():
```
Utils.loadClasses("Test/list");
for (SootClass sootClass : Scene.v().getClasses()) {
    System.out.println(sootClass.getName());
}
```

Utils.loadClass() is shown in the issure. 
After I deleting the clashing arguments and set `set_soot_classpath` only, the code doesn't cause any exceptions but output nothing, which means that I still can't get `Body`s of the methods.

Thanks for your reply and solution!

**Comment by anddann** [comment]
Sry, my bad the call `Scene.v().loadNecessaryClasses();` is still necessary

**Comment by CbcWestwolf** [comment]
Now I can successfully load 3533 classes, but none of them are `ApplicationClass` and none of them from my dir `classpath`. And I notice that if I set the soot classpath an empty string `""` instead of `".:" + classespath + ":" + "rt.jar"`, I can still get 3533 classes printed.

Thanks!

**Comment by mbenz89** [comment]
In Soot, classpath specifies the classes that are used as so-called `LibraryClasses`, i.e. classes that are considered by the analysis if they are used in `ApplicationClasses` but are "directly" analyzed. 

`ApplicationClasses`, on the other side, are classes that you are targeting with your analysis. Classes put on the `process_dir` will be tagged as `ApplicationClasses`.

A common procedure is therefore to put the classes of an application that you aim to analyze on the process dir and some libraries (like the JDK) on the classpath, in case you want an analysis to follow down the callpath of such library classes. 

Thus, if you do not want to modify any jdk or library classes, you do not need to include the JDK into your classpath. This should make Soot much faster:

```
        Options.v().set_process_dir(new ArrayList<String>(Collections.singletonList(".")));
        // optional:  Options.v().set_soot_classpath("classespath + ":" + "rt.jar");
        Scene.v().loadNecessaryClasses();
```

Assuming that the classes you want to analyze are located in `.`.
Also, `rt.jar` needs to be located absolutely if it is not also located in your current working directory.

**Comment by CbcWestwolf** [comment]
Ok! I get it correctly at last! 
I should not forget this basic concept introduced in tutorials... 
Thanks for your kindness and patience again~
