### ISSUE TITLE
Missing CG edge for static field

### ISSUE THREAD

**Issue by rakshitkr** [soot-oss/soot#1383]
In the below code example, line A has a static field that gets initialized in `UserClass` by calling _func()_. The JVM implicitly calls the static initializer of `UserClass` and the initializer initialises `FIELD` by calling `func()`. So shouldn't there be a static edge from line A to `func()`?

### Sample code 1
```java
public class MainClass {
	public static void main(String[] args) {
		int field = UserClass.FIELD; // line A
	}
}
```

```java
public class UserClass {	
	public static final int FIELD = func();
	public static int func() {
		return 0;
	}	
}
```

### CG 1
```
Total Edges:5
<demo.UserClass: void <clinit>()> may call <demo.UserClass: void <clinit>()>
<demo.UserClass: void <clinit>()> may call <java.lang.Object: void <clinit>()>
<demo.UserClass: void <clinit>()> may call <demo.UserClass: int func()>
<demo.MainClass: void main(java.lang.String[])> may call <demo.UserClass: void <clinit>()>
\\ missing edge
<demo.MainClass: void main(java.lang.String[])> may call <java.lang.Object: void <clinit>()>
```

This is not the case when _func()_ is invoked directly in line A like below

### Sample code 2
```
...
int field = UserClass.func(); // line A
...
```

### CG 2
```
Total Edges:6
<demo.UserClass: void <clinit>()> may call <demo.UserClass: void <clinit>()>
<demo.UserClass: void <clinit>()> may call <java.lang.Object: void <clinit>()>
<demo.UserClass: void <clinit>()> may call <demo.UserClass: int func()>
<demo.MainClass: void main(java.lang.String[])> may call <demo.UserClass: void <clinit>()>
<demo.MainClass: void main(java.lang.String[])> may call <demo.UserClass: int func()>
<demo.MainClass: void main(java.lang.String[])> may call <java.lang.Object: void <clinit>()>
```

**Comment by linghuiluo** [comment]
@rakshitkr in CG1 I see the edge from UserClass.clinit to func, so what is missing? 
the path MainClass.main ->  UserClass.clinit -> func is there. Looks fine for me.

**Comment by rakshitkr** [comment]
Okay thanks. I was assuming there should be an edge from `MainClass` to `UserClass.func()` like in the latter case.

**Comment by mbenz89** [comment]
In the latter case, the method `UserClass.func()` is directly called in main, that's why there is an edge from `main` to the method. In the first example, however, the method is not directly called in main, but the static constructor of `UserClass` is implicitly called when the `FIELD` field of it is accessed since it is the first time the class `UserClass` is accessed. Initialization of that field is then done in the static constructor since it is responsible for initializing the class and its fields.
Therefore, MainClass.main -> UserClass.clinit -> func  is the correct call chain to `func`.

**Comment by rakshitkr** [comment]
The above code was a simplified version. Here is the actual code :

### Test code 1
```java
@Test
public void generateNewAES128GCMKeySet() throws GeneralSecurityException {
	KeyTemplate kt = AeadKeyTemplates.createAesGcmKeyTemplate(16); // static method call
	Assertions.hasEnsuredPredicate(kt);
}
```
For code 1, below are the list of reachable methods
```
<dummyClass: void main(java.lang.String[])>
<tests.pattern.DummyTest: void generateNewAES128GCMKeySet()>
<com.google.crypto.tink.aead.AeadKeyTemplates: void <clinit>()>
<test.assertions.Assertions: void hasEnsuredPredicate(java.lang.Object)>
<com.google.crypto.tink.aead.AeadKeyTemplates: com.google.crypto.tink.proto.KeyTemplate createAesGcmKeyTemplate(int)>
<java.lang.Object: void <clinit>()>
<java.lang.Object: void registerNatives()>
```
### Test code 2
```java
@Test
public void generateNewAES128GCMKeySet_static() throws GeneralSecurityException {
	KeyTemplate kt = AeadKeyTemplates.AES128_GCM; // static field
	Assertions.hasEnsuredPredicate(kt);
}
```
For code 2, below are the list of reachable methods
```
<dummyClass: void main(java.lang.String[])>
<tests.pattern.DummyTest: void generateNewAES128GCMKeySet_static()>
<com.google.crypto.tink.aead.AeadKeyTemplates: void <clinit>()>
<test.assertions.Assertions: void hasEnsuredPredicate(java.lang.Object)>
<java.lang.Object: void <clinit>()>
<java.lang.Object: void registerNatives()>
```

Though the field `AES128_GCM` gets initialised with the return value of `createAesGcmKeyTemplate` method by `AeadKeyTemplates` static constructor [code](https://github.com/google/tink/blob/7e6d51d3ac1bdb29944f2df2b8b5e5925bc36e65/java_src/src/main/java/com/google/crypto/tink/aead/AeadKeyTemplates.java#L64), there is no corresponding call chain i.e. `DummyTest.generateNewAES128GCMKeySet_static -> AeadKeyTemplates.clinit -> createAesGcmKeyTemplate`. Hence analysis fails to generated the necessary predicate since the method is unreachable.

**Comment by rakshitkr** [comment]
The sootMethod corresponding to `AeadKeyTemplates` initialiser doesn't have `activebody`. Therefore, how to reach `createAesGcmKeyTemplate` method in this case? I don't see the method `createAesGcmKeyTemplate` in the list of reachable methods returned by `Scene.v().getReachableMethods();`

**Comment by mbenz89** [comment]
It seems that `com.google.crypto.tink.aead.AeadKeyTemplates` is introduced by a third party google library.  Have you added this library to Soot's classpath so that it is able to properly resolve it? Otherwise, Soot cannot build bodies for the class which would eventually lead to missing edges in the CG for this class.

**Comment by rakshitkr** [comment]
Yes. I've added the corresponding library jar to soot's classpath. You can find its code below

```java
@Override
	protected String getSootClassPath() {
		String tinkJarPath = new File("src/test/resources/tink-1.2.0.jar").getAbsolutePath();
		return super.getSootClassPath() +File.pathSeparator +tinkJarPath;
	}
```
This method is used later to initialise soot entry point [here](https://github.com/CROSSINGTUD/SPDS/blob/479c5b12f5b1061ab95941ae6abd4217ff499734/testCore/src/main/java/test/core/selfrunning/AbstractTestingFramework.java#L108)

**Comment by mbenz89** [comment]
Looks good to me. Could you check if the `AeadKeyTemplates` is definitely contained in the jar.
Also, could you debug into soot `SootResolver.processResolveWorklist` when the class is resolved and see what happens?

**Comment by rakshitkr** [comment]
`AeadKeyTemplates` is present in the jar. It is even added to the `worklist` at `desiredlevel = 2`. But its corresponding sootclass is set as phantom [here](https://github.com/soot-oss/soot/blob/3e9684eeac5611c4baed73eefb1738383063db6c/src/main/java/soot/SootResolver.java#L163)

**Comment by mbenz89** [comment]
Thanks for investigating!

The question then is: "Why is `onlySignatures` set to true in https://github.com/soot-oss/soot/blob/3e9684eeac5611c4baed73eefb1738383063db6c/src/main/java/soot/SootResolver.java#L159"

That again might indicate that the class is excluded since it won't be marked as phantom the first time it is processed by the worklist algorithm. Could you have another quick look why `onlySignatures` is true??

**Comment by rakshitkr** [comment]
It is happening because the crysl rule classes are excluded from soot scene [here](https://github.com/CROSSINGTUD/CryptoAnalysis/blob/325da3a0b0d9ef723d590cd2ec0e4f7ab1397736/CryptoAnalysis/src/test/java/test/UsagePatternTestingFramework.java#L370)

**Comment by rakshitkr** [comment]
@mbenz89 Thanks for your support. I can now see the respective edge in the CG.

```
STATIC edge: $stack1 = staticinvoke <com.google.crypto.tink.aead.AeadKeyTemplates: com.google.crypto.tink.proto.KeyTemplate createAesGcmKeyTemplate(int)>(varReplacer7) in <com.google.crypto.tink.aead.AeadKeyTemplates: void <clinit>()> ==> <com.google.crypto.tink.aead.AeadKeyTemplates: com.google.crypto.tink.proto.KeyTemplate createAesGcmKeyTemplate(int)>
```
