### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by muthu30011997** [soot-oss/soot#1386]
Is there any way to run soot in multi threaded way ?

**Comment by muthu30011997** [comment]
I got https://mailman.cs.mcgill.ca/pipermail/soot-list/2016-November/008619.html link when am i searching for the solution

**Comment by mbenz89** [comment]
I think that describes it pretty well. Soot's class loading and writing is parallel. Anything between is not parallel if you do not implement it as such. I.e., you can definitely write some body- or scene-transformers in parallel but you cannot rely on the Soot api working in a parallel manner without employing custom synchronization.

**Comment by muthu30011997** [comment]
HI @mbenz89  , in my case , i have to call soot.Main.main(args) method from multi thread code . I got 

java.lang.RuntimeException: timer totalTimer has already been started!
at soot.Timer.start(Timer.java:94)
	at soot.Main.run(Main.java:234)
	at soot.Main.main(Main.java:141)

exception . How can i solve it ? 

Is there any way to call soot.Main.main(args) method in multi thread ?
