### ISSUE TITLE
Bump into ConcurrentModificationException when invoke retrieveActiveBody() during method list traverse

### ISSUE THREAD

**Issue by QRXqrx** [soot-oss/soot#1496]
Hey there,

I found that invoking SootMethod#retriveActiveBody when traversing method list getting using SootClass#getMethods() will accidentally lead to ConcurrentModificationException. I'm really puzzled about this because I have no idea the similarity between the failed method. If I skipped the failed method, the iteration will not stopped util meets another failed method. So I think these failed methods may have some common features. The code is like follows:

```
Options.v().set_allow_phantom_refs(true); // For process run.
// Set test classes as application class and set production classes as library classes.
Options.v().set_process_dir(Collections.singletonList(commons_io_test_class_dir_path));
String cp = commons_io_production_class_dir_path + File.pathSeparator + junitDep + File.pathSeparator + rtJarPath;
Options.v().set_soot_classpath(cp);

// Initialize
Scene.v().loadNecessaryClasses();
// Draw application (test) classes.
Chain<SootClass> appClasses = Scene.v().getApplicationClasses();
for (SootClass appClass : appClasses) {
    SootClass sootClass = Scene.v().loadClassAndSupport(className); // Load app class.
    List<SootMethod> sootMethods = sootClass.getMethods();
    for (SootMethod sootMethod : sootMethods) {
        // Some operations and contains invocation of retrieveMethodBody
        System.out.println(sootMethod.retrieveMethodBody());
    }
}
```

The exception stack is like:
```
java.util.ConcurrentModificationException
	at soot.util.HashChain$LinkIterator.hasNext(HashChain.java:569)
	at edu.learn.pa.soot.ExperimentOnSlice_commons_io.constructDotForTestClass(ExperimentOnSlice_commons_io.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
```

Please reply me at your convienience, thanks :-)

**Comment by patricklam** [comment]
Try using SootClass.methodIterator() instead.

**Comment by QRXqrx** [comment]
@patricklam Thank u for your replying. I tried your advice but it seems it doesn't work for me and I still got the same exception. In fact, I don't think this exception is realted to the iterator I use because this exception usually occurs when one try to modify a list while traversing it.

**Comment by patricklam** [comment]
Try copying the list of methods and seeing if you can iterate on that copy.
That really should work. I didn't think that retrieveActiveBody should
change the list of methods.

The stack trace is strange, it is calling the iterator probably on the list
of units in the body but from a unit test. Is this code in a test?

**Comment by QRXqrx** [comment]
@patricklam Yes, it is a test. I use to write junit test method to run some immature code snippet. Will this cause unintended problems?

**Comment by patricklam** [comment]
Beats me. I would also be conservative and put a G.v().reset() in front of
the test to make sure that it works, or maybe put it in a non test and see
if it still happens.

**Comment by QRXqrx** [comment]
@patricklam Oops, it still happens.. I wonder whether I did something wrong?😢 Or it is a bug? So weird.  

Code:
```
    public static void main(String[] args) {
         G.reset();
        Options.v().set_allow_phantom_refs(true); // For process run.
        // Set test classes as application class and set production classes as library classes.
        Options.v().set_process_dir(Collections.singletonList(commons_io_test_class_dir_path));
        String cp = commons_io_production_class_dir_path + File.pathSeparator + junitDep + File.pathSeparator + rtJarPath;
        Options.v().set_soot_classpath(cp);

        // Initialize
        Scene.v().loadNecessaryClasses();
        // Mention phantom classes.
        System.out.println(SEP);
        if(Scene.v().getPhantomClasses().isEmpty())
            System.out.println("Contain phantom classes.");
        else
            System.out.println("No phantom class.");
        System.out.println(SEP);
        // Draw application (test) classes.
        Chain<SootClass> appClasses = Scene.v().getApplicationClasses();
        for (SootClass appClass : appClasses) {
            String className = appClass.getName();
            System.out.println(SEP);
            System.out.println(className);
            System.out.println(SEP);
            SootClass sootClass = Scene.v().loadClassAndSupport(className); // Load app class.
            Iterator<SootMethod> methodIte = sootClass.methodIterator();
            while (methodIte.hasNext()) {
                SootMethod sootMethod = methodIte.next();

                System.out.println(sootMethod.retrieveActiveBody());
            }
        }
    }
```

Exception stack:
```
Exception in thread "main" java.util.ConcurrentModificationException
	at soot.util.HashChain$LinkIterator.hasNext(HashChain.java:569)
	at edu.learn.pa.soot.ExperimentOnCommonsIO.main(ExperimentOnCommonsIO.java:47)
```

**Comment by patricklam** [comment]
Oh. It's not the methods iterator that is giving you trouble, I bet, but
rather the classes iterator. (I don't know what line numbers you have). I'm
pretty sure that loadClassAndSupport from within the appClasses iteration
is giving you trouble. Load the classes and then iterate. You should only
be using appClass inside the loop, not a thing that you are asking
loadClassAndSupport for.

pat

**Comment by QRXqrx** [comment]
@patricklam You are right: The exception is surely thrown at the line of class iteration (`for (SootClass appClass : appClasses) {`). Do you mean that I should do get methods from `appClass` and call `retriveActiveBody` directly? If so, I'm afraid it doesn't work again. 😢 
```
public static void main(String[] args) {
         G.reset();
        Options.v().set_allow_phantom_refs(true); // For process run.
        // Set test classes as application class and set production classes as library classes.
        Options.v().set_process_dir(Collections.singletonList(commons_io_test_class_dir_path));
        String cp = commons_io_production_class_dir_path + File.pathSeparator + junitDep + File.pathSeparator + rtJarPath;
        Options.v().set_soot_classpath(cp);

        // Initialize
        Scene.v().loadNecessaryClasses();
        // Mention phantom classes.
        System.out.println(SEP);
        if(Scene.v().getPhantomClasses().isEmpty())
            System.out.println("Contain phantom classes.");
        else
            System.out.println("No phantom class.");
        System.out.println(SEP);
        // Draw application (test) classes.
        Chain<SootClass> appClasses = Scene.v().getApplicationClasses();
        for (SootClass appClass : appClasses) {
            String className = appClass.getName();
            System.out.println(SEP);
            System.out.println(className);
            System.out.println(SEP);
            Iterator<SootMethod> methodIte = appClass.methodIterator();
            while (methodIte.hasNext()) {
                SootMethod sootMethod = methodIte.next();
                System.out.println(sootMethod.retrieveActiveBody());
            }
        }
    }
```

Exception stack:
```
Exception in thread "main" java.util.ConcurrentModificationException
	at soot.util.HashChain$LinkIterator.hasNext(HashChain.java:569)
	at edu.learn.pa.soot.ExperimentOnCommonsIO.main(ExperimentOnCommonsIO.java:47)
```

**Comment by patricklam** [comment]
Which line is line 47?

**Comment by QRXqrx** [comment]
This line:
![image](https://user-images.githubusercontent.com/49576982/99745276-4b717880-2b14-11eb-9856-2303b141d224.png)

**Comment by patricklam** [comment]
Set a breakpoint in HashChain.add and one inside your for loop, disable the
HashChain breakpoint, run, enable the breakpoint, and see what the call
stack is.

**Comment by QRXqrx** [comment]
@patricklam I will try that, thank u for your advice 👍

**Comment by QRXqrx** [comment]
Well, I have debugged for a while, and it guess this is the bug caused by **the usage of lambda expression within application class**. To illustrate that I make the following three screen shot:
 
![image](https://user-images.githubusercontent.com/49576982/99752550-8200c080-2b1f-11eb-8b94-3b97e967ef15.png)
In the first picture, the size of `appClasses` is 250.

![image](https://user-images.githubusercontent.com/49576982/99752855-2256e500-2b20-11eb-8c8a-a4ec71215da0.png)

In the second picture, after processing `org.apache.commons.io.ByteOrderParserTest#testThrowsException`, the size of `appClasses` change to **251**

![image](https://user-images.githubusercontent.com/49576982/99752988-58946480-2b20-11eb-869a-05d037d683c9.png)
At this point, the processed is `org.apache.commons.io.ByteOrderParserTest#lambda$testThrowsException$0` which I think is correspond to the following test method:
```
    @Test
    public void testThrowsException() {
        assertThrows(IllegalArgumentException.class, () -> parseByteOrder("some value"));
    }
```

I checked similar test methods I recorded yesterday and found usage of lambda expressions, too. It seems Soot need to add an anonymous class as application class when a lambda expression occurs. How to avoid that? I wish Soot able to analyze test method like that properly.

**Comment by patricklam** [comment]
The short-term solution is to use a snapshotIterator on appClasses. The
long-term solution is to pre-generate the application classes that get
generated when there are lambda expressions. I would need to learn how that
all happens to implement that, but it would be great if someone could do it.

pat

**Comment by patricklam** [comment]
(You would miss the lambda class. You could do another iteration to catch
classes that you missed.)

**Comment by QRXqrx** [comment]
It seems that the anonymous class used by lambda expression won't construct .class file through compiling (using javac). You could follow the following steps to reproduce the exception:

1. Make directory at current workplace and named it "lambda", i.e. `./lambda`.
2. Create a java file `TestLambda.java` under `./lambda` . Copy the following code into it and compile.
```
import java.util.ArrayList;
import java.util.List;
import java.util.function.Supplier;

public class TestLambda {

    public static void main(String[] args) {
        List<Integer> numList = getNumList(10, () -> 1);
        System.out.println(numList);
    }

    public static List<Integer> getNumList(int len, Supplier<Integer> supplier) {
        ArrayList<Integer> numList = new ArrayList<>();

        for(int i = 0 ; i < len ; i++) {
            numList.add(supplier.get());
        }
        return numList;
    }

}
```
3. Use the following code to reproduce this exception:
```
package edu.learn.pa.soot;

import soot.Scene;
import soot.SootClass;
import soot.SootMethod;
import soot.options.Options;
import soot.util.Chain;

import java.util.Collections;
import java.util.List;

public class AnalyzeLambda {

    public static void main(String[] args) {
        String appDir = "./lambda";
        // Configure Soot Main.
        Options.v().set_process_dir(Collections.singletonList(appDir));

        // Initial.
        Scene.v().loadNecessaryClasses();
        Chain<SootClass> appClasses = Scene.v().getApplicationClasses();
        for (SootClass appClass : appClasses) {
            List<SootMethod> sootMethods = appClass.getMethods();
            for (SootMethod sootMethod : sootMethods) {
                String fullName = String.format("%s#%s", appClass.getName(), sootMethod.getName());
                System.out.println(fullName);
                sootMethod.retrieveActiveBody();
            }
        }
    }

}

```

If it is as expected, then you could receive following exception stack. BTW, I'm using jdk8. The version of soot is 4.2.1.
```
Exception in thread "main" java.util.ConcurrentModificationException
	at soot.util.HashChain$LinkIterator.hasNext(HashChain.java:569)
	at edu.learn.pa.soot.AnalyzeLambda.main(AnalyzeLambda.java:29)
```

**Comment by patricklam** [comment]
Thanks. That looks helpful as a bug report. Perhaps it is best to file as a
separate bug and close this one for easy understanding.

**Comment by QRXqrx** [comment]
OK
