### ISSUE TITLE
Invoke SootMethod#retrieveActiveBody for a method contains the usage of lambda expressions while traversing application classes will cause ConcurrentModificationException.

### ISSUE THREAD

**Issue by QRXqrx** [soot-oss/soot#1497]
Hi there,
This is a issue follows #1496 . I wonder whether this is a bug. Or is there any solution to this? 

You could follow the following steps to reproduce this exception:

1. Make directory at current workplace and named it "lambda", i.e. `./lambda`.
2. Create a java file `TestLambda.java` under `./lambda` . Copy the following code into it and compile.
```
import java.util.ArrayList;
import java.util.List;
import java.util.function.Supplier;

public class TestLambda {

    public static void main(String[] args) {
        List<Integer> numList = getNumList(10, () -> 1);
        System.out.println(numList);
    }

    public static List<Integer> getNumList(int len, Supplier<Integer> supplier) {
        ArrayList<Integer> numList = new ArrayList<>();

        for(int i = 0 ; i < len ; i++) {
            numList.add(supplier.get());
        }
        return numList;
    }

}
```
3. Use the following code to reproduce this exception:
```
import soot.Scene;
import soot.SootClass;
import soot.SootMethod;
import soot.options.Options;
import soot.util.Chain;

import java.util.Collections;
import java.util.List;

public class AnalyzeLambda {

    public static void main(String[] args) {
        String appDir = "./lambda";
        // Configure Soot Main.
        Options.v().set_process_dir(Collections.singletonList(appDir));

        // Initial.
        Scene.v().loadNecessaryClasses();
        Chain<SootClass> appClasses = Scene.v().getApplicationClasses();
        for (SootClass appClass : appClasses) {
            List<SootMethod> sootMethods = appClass.getMethods();
            for (SootMethod sootMethod : sootMethods) {
                String fullName = String.format("%s#%s", appClass.getName(), sootMethod.getName());
                System.out.println(fullName);
                sootMethod.retrieveActiveBody();
            }
        }
    }

}

```

If it is as expected, then you could receive following exception stack. BTW, I'm using jdk8. The version of soot is 4.2.1.
```
Exception in thread "main" java.util.ConcurrentModificationException
	at soot.util.HashChain$LinkIterator.hasNext(HashChain.java:569)
	at edu.learn.pa.soot.AnalyzeLambda.main(AnalyzeLambda.java:29)
```

**Comment by MarcMil** [comment]
retrieveActiveBody can cause new classes to be discovered. You can use a snapshotIterator instead to prevent the CME. However, you will not see the new classes. You could use a set of already discovered classes and iterate over this loop multiple times until you reach a fixed-point of classes.

**Comment by QRXqrx** [comment]
That does make sense. I solved my problem by collectingall methods I want to process first and avoiding invoking `retrieveActiveBody` during the iteration of `SootClass`es. It looks like the side-effect, which construts new classes, caused by `retrieveActiveBody` does have its rationales and is not a bug. I will close this issue then, thank u! :-)
