### ISSUE TITLE
is there any example to modify Jimple method body?

### ISSUE THREAD

**Issue by Marvinmw** [soot-oss/soot#1500]
Hi, I want to modify the method body, list of units. For example, I want to remove one unit or change the operator. Is there any tutorial about it?

**Comment by linghuiluo** [comment]
Check the Wiki

**Comment by Marvinmw** [comment]
> Check the Wiki

Thanks for your response. But I cannot find any guideline that I want. Creating a method body or instrumenting is not what I want. Could you kindly give me some tips?
