### ISSUE TITLE
Ambiguous method name xxx in class xx

### ISSUE THREAD

**Issue by RichardHoOoOo** [soot-oss/soot#1552]
Suppose I have a class A and a class B that extends A. Class B has a method `foo` that overrides Class A's `foo`.
```
class A {
    public A foo() {return null;}
}

class B extends A {
    public B foo() {return null;}
}
```

When I use the following code to get class B's `foo`,  an exception is thrown saying `soot.AmbiguousMethodException: Ambiguous method name foo in class B`
```
SootClass B = Scene.v().loadClassAndSupport("B");
SootMethod fooB = B.getMethodByNameUnsafe("foo");
``` 

When I print all the methods in B, the output is
```
<B: void <init>()>
<B: B foo()>
<B: A foo()>
```

Since B's `foo` overrides A's `foo`, why there are two `foo`s in B that causes the ambiguous exception?

**Comment by MarcMil** [comment]
I'd guess this is related to https://github.com/soot-oss/soot/issues/1553
The java compiler probably generates a method to access that other foo of the super class, and thus, there are two methods with the same name. Personally, I'd refrain to use getMethodByNameUnsafe if possible for reasons like this. Besides, overloading methods is very common and would lead to a failure as well. I'd reference methods by their subsignature.
