### ISSUE TITLE
A bug in EntryPoints:Iterable<SootMethod> clinitsOf(SootClass cl).

### ISSUE THREAD

**Issue by DongjieHe** [soot-oss/soot#1602]
Consider a case where the input class cl does not have the "clinit" method but its superclass has the "clinit" method. Then the correct output should give me the <clinit> in its superclass. However, the current implementation just returns an empty collection (line 189).

**Comment by linghuiluo** [comment]
Are you analyzing java bytecode or dex file?
If it is the later case, it can be that some optimization was already done during the build of the APK.
A small example to reproduce this would be helpful.

**Comment by DongjieHe** [comment]
Hi Linghui,
I am analyzing Java bytecode.
The attached file gives a small example that contains a total of 4 classes.
A1, A, and IA have the following relation:
**A1 extends A implements IA**
The main() method in Main presents a use case. 
When analyzing this example code, we invoke EntryPoints::clinitOf(A1) and expect it to return two clinits, i.e., "<soot.A: void clinit()>" and "<soot.IA: void clinit()>".
But the current implementation will give us an empty result due to its line 189. 

I hope I explain this issue clearly.

[Clinit-src.zip](https://github.com/soot-oss/soot/files/6438847/Clinit-src.zip)

**Comment by linghuiluo** [comment]
thanks, I will take a look into this.

**Comment by DongjieHe** [comment]
@linghuiluo Hi Linghui, suppose you are correct, and I need to get all static constructors that can be called by A1, if I should call EntryPoints::clinitOf on A1 and all its superclasses, then EntryPoints::clinitOf(SootClass cl) could be simplified by just returning the static constructor of cl.

**Comment by linghuiluo** [comment]
@DongjieHe Returning the static constructor of cl is not equal to what it is now. This method doesn't do as the Javadoc says. You are right, it affects also the call graph. I made a pull request https://github.com/soot-oss/soot/pull/1610
Can you also review it and leave a comment?
