### ISSUE TITLE
Support analysis single dex file or ClassDef in Dexlib2 please.

### ISSUE THREAD

**Issue by FlyingYu-Z** [soot-oss/soot#1607]
I want to parse an dex file for analysis,but it only has the usage of cmd.
and I want parse an ClassDef (in dexlib2) for analysis,how to do it ?

**Comment by MarcMil** [comment]
What is it you are trying to achieve?
"it only has the usage of cmd" What does this mean? Can you only run soot on the command line for whatever reason?
dexlib2 is part of smali, so if you do not want to use Soot at all, you should ask the smali team.
Or do you want to use soot for a specific class in an APK or dex file only?

**Comment by FlyingYu-Z** [comment]
> What is it you are trying to achieve?
> "it only has the usage of cmd" What does this mean? Can you only run soot on the command line for whatever reason?
> dexlib2 is part of smali, so if you do not want to use Soot at all, you should ask the smali team.
> Or do you want to use soot for a specific class in an APK or dex file only?

yes,I want use soot for a specific class,because i use dexlib2 usually.
i hope soot can be used for a ClassDef(dexlib2 class).

**Comment by MarcMil** [comment]
Take a look at https://github.com/soot-oss/soot/blob/develop/src/main/java/soot/dexpler/DexClassLoader.java#L71
However, it might be necessary to patch soot in a number of ways to support what you want, since this a very rare use case.
It'd be probably easier to read in the whole dex or apk file (if you don't have any, you could write it using dexlib2) and exclude everything using the exclude option and include only the class you want. Be sure to set "allow phantom refs" to true, since certainly there will be dangling references to other classes. That way, soot handles the reading in part.

For your reference in the soot code: the code in the package soot.dexpler is used to read dex files using dexlib into soot, soot.toDex is used to write dex files using dexlib.

**Comment by FlyingYu-Z** [comment]
Thanks! But it's hard to make a SootClass.
I think you can do following api like Dexlib2:

Dexlib2:

DexBackedDexFile dexFile= DexBackedDexFile.fromInputStream(Opcodes.getDefault(),new BufferedInputStream(new FileInputStream("test/classes.dex")));
List<ClassDef> classDefList= Lists.newArrayList(dexFile.getClasses());

do it for Soot：

SootDexFile dexFile=SootDexFile .fromInputStream(Opcodes.getDefault(),new BufferedInputStream(new FileInputStream("test/classes.dex")));
List<SootClass> classList=dexFile.getClasses();

do more on Java api rather than cmd usage,please 🙏

**Comment by MarcMil** [comment]
Soot is not just about APKs and Android, but also Java classes, source code, etc. You can read in a dex file, just use it the way soot is intended to be used as of right now, e.g.
```
		Options.v().set_allow_phantom_refs(true);
		Options.v().set_src_prec(Options.src_prec_apk);
		Options.v().set_process_dir(Arrays.asList(
				"/home/marc/app-debug.apk"));
		Options.v().set_force_android_jar("/home/marc/Android/Sdk/platforms/android-27/android.jar");
		Options.v().set_process_multiple_dex(true);
		Scene.v().loadNecessaryClasses(); //read in

//get specific class:
		SootClass c = Scene.v().getSootClass("foo.bar.MainActivity");
//or get all application classes:
		Chain<SootClass> allClasses = Scene.v().getApplicationClasses();

//do something... 
		PackManager.v().writeOutput(); //in case you want to write out the apk/dex file again
```
Change the /home/marc/app-debug.apk path to match the dex file on disk. Note that for soot you need to download and install the Android SDK and supply the path to the android.jar file and change


For a complete code sample, you could use e.g.
https://github.com/noidsirius/SootTutorial/blob/master/src/main/java/dev/navids/soottutorial/android/AndroidClassInjector.java
https://github.com/noidsirius/SootTutorial/

Change the apkPath variable to the dex file path.

**Comment by FlyingYu-Z** [comment]
ok,thank you very much
