### ISSUE TITLE
the URL does not work

### ISSUE THREAD

**Issue by khanjani-b** [soot-oss/soot#1611]
2. Step by Step Instructions for Integrating Soot with Eclipse: To Integrate Soot with eclipse follow the simple steps given below,

Within Eclipse Select:

Step1: Select, Help -> Software Updates (install new software) -> Find and Install

Step2: Select, Search for new features to install -> Next -> New Remote Site

Step3: Give the update site a name and use the below site link for the URL:
http://www.sable.mcgill.ca/soot/eclipse/updates/
and please do not forget the trailing slash.

Step4: Select: OK -> Finish

**in Step3 given URL does not work**

**Comment by linghuiluo** [comment]
i dont think the eclipse plugin still works. It hasn't been maintained for a while.

**Comment by khanjani-b** [comment]
thank you
