### ISSUE TITLE
What is the difference between IdentityStmt and AssignStmt?

### ISSUE THREAD

**Issue by 0range228** [soot-oss/soot#1672]
What is the difference between IdentityStmt and AssignStmt?

**Comment by StevenArzt** [comment]
An ``IdentityStmt`` assigns special values, such as a parameter, the ``this`` local, or the exception that was caught, to a local. All "normal" assignments, e.g., from one local to another or from a constant to a local, are modeled using the ``AssignStmt``.

**Comment by 0range228** [comment]
Thanks a lot ^_^
