### ISSUE TITLE
What are the meanings of these Stmt & Exprs?

### ISSUE THREAD

**Issue by 0range228** [soot-oss/soot#1679]
Hi,there!

I recently combed through the documentation, but I still can not find these Stmt & Exprs' meaning.

Please tell me these meanings .

**JEnterMonitorStmt
JExitMonitorStmt
JReturnStmt
JRetStmt
PlaceholderStmt
JLengthExpr
JNegExpr**

**Comment by patricklam** [comment]
see
https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-6.html#jvms-6.5.dneg

On Thu, Jun 24, 2021 at 1:00 PM 0range228 ***@***.***> wrote:

> *JEnterMonitorStmt*
>
>
> * JExitMonitorStmt*
>

synchronized() gets translated to the entermonitor/exitmonitor

> * JReturnStmt*
>
method return

>
> * JRetStmt*
>
not used, represents JSR statements


>
> * PlaceholderStmt*
>

I don't think it's used.


>
> * JLengthExpr*
>
x.length where x is an array


> * JNegExpr*
>
>
> Negate an integer variable.

**Comment by 0range228** [comment]
Thanks a lot , dude. ^_^
