### ISSUE TITLE
Some problems about flowThrough()

### ISSUE THREAD

**Issue by 0range228** [soot-oss/soot#1682]
Hi,there!
I have recently been implementing my own pointer analysis framework, Maybe I found a bug in soot.
Here's a simple example of my experiments with the to-be-analyzed method:
```java
public static void main(String[] args) {
        A a = new A();
        A b = new A();
        A c = new A();
        a=b;
        c=a;
        c.i = 6;
}
```
jimple file is:
```java
args := @parameter0: java.lang.String[]
$stack4 = new demo.A
specialinvoke $stack4.<demo.A: void <init>()>()
a = $stack4
$stack5 = new demo.A
specialinvoke $stack5.<demo.A: void <init>()>()
b = $stack5
$stack6 = new demo.A
specialinvoke $stack6.<demo.A: void <init>()>()
c = $stack6
a = b
c = a
c.<demo.A: int i> = 6
return
```
That's quite simple, right?
So I have now written a PTAanalysis that inherits the ForwardFlowAnalysis<>, and I have rewritten flowThrough() to iterate over each unit and determine their stmt type, e.g. InvokeStmt or something else, etc.
But I found that instead of executing the rewritten flowThrough() method each time, It executed super.flowThrough().

So I did the debugging:
```java
private boolean flowThrough(FlowAnalysis.Entry<N, A> d) {
        if (d.inFlow == d.outFlow) {
            assert !d.isRealStronglyConnected || d.in.length == 1;

            return true;
        } else if (d.isRealStronglyConnected) {
            A out = this.newInitialFlow();
            this.flowThrough(d.inFlow, d.data, out);
            if (out.equals(d.outFlow)) {
                return false;
            } else {
                this.copy(out, d.outFlow);
                return true;
            }
        } else {
            this.flowThrough(d.inFlow, d.data, d.outFlow);
            return true;
        }
    }
```
I went above to find that each time d is my jimple stmt and it's inFlow and outFlow are NULL ???
So it won't go into my own rewritten flowThrough() method?
I don't know what's going on, but if anyone knows why, please let me know immediately.
Thanks in advance.

**Comment by patricklam** [comment]
I'm a bit confused by why you show code from the private boolean
flowThrough() implementation. Is your flowThrough overriding protected
abstract void flowThrough(A in, N d, A out);?

**Comment by 0range228** [comment]
Yeah, I kill my bug which is associated with my own FlowSet. Thanks a lot.
