### ISSUE TITLE
How to convert single jimple file to class using Soot API?

### ISSUE THREAD

**Issue by CbcWestwolf** [soot-oss/soot#1690]
I'm trying to manipulate bytecode by creating jimple file and convert it to class bytecode using Soot API, as what I do like convert class to jimple. I create a directory named `jimple`, which has a structure like this: 
```text
jimple
└── Mutant3
    └── void main(java.lang.String[])
        └── Mutant3.main.jimple
```
In `Mutant3.main.jimple`, the `main` method look like this:
```text
    public static void main(java.lang.String[])
    {
        java.lang.String[] r0;
        java.lang.String $r2;

        r0 := @parameter0;

        $r2 = new java.lang.String;

        specialinvoke $r2.<java.lang.String: void init()>();

        entermonitor $r2;

        exitmonitor $r2;

        return;
    }
```
It is pretty easy and I'll do some modification after all.
Here is the java code `Jimple2Class` which is used to convert jimple. 
```java
import soot.*;
import soot.options.Options;
import soot.util.PhaseDumper;
import java.util.*;

public class Jimple2Class {
    public static void main(String[] args) {
        String path = "<path-to-jimple-directory>";

        G.reset();
        Options.v().set_allow_phantom_refs(true);
        Options.v().set_allow_phantom_elms(true);
        Options.v().set_ast_metrics(true);
        Options.v().set_whole_program(true);
        Options.v().set_prepend_classpath(true);
        Options.v().set_src_prec(Options.src_prec_jimple);
        Options.v().set_output_format(Options.output_format_class);
        Options.v().set_verbose(true);
        Options.v().set_process_dir(Collections.singletonList(path));

        Options.v().set_java_version(Options.java_version_8);

        Scene.v().loadNecessaryClasses();

        for (SootClass sootClass : Scene.v().getApplicationClasses()) {
            for (SootMethod sootMethod : sootClass.getMethods()) {
                System.out.println(sootMethod.getName());
            }
        }

        PackManager.v().writeOutput();
    }
}
```

The code is so similar to the code for converting class to jimple, which only differs on `set_src_prec` and `set_output_format`. However, after executing the `main` method, nothing is produced in `sootOutput` directory, and the loop for print method name in application classes print nothing.

So what's wrong with my way? Is it convenient to using Soot to convert jimple to class?

Thanks!

**Comment by linghuiluo** [comment]
why don't try instrumentation directly? I am not sure how well the Jimple front end is maintained. 
Here is a tutorial https://github.com/soot-oss/soot/wiki/Instrumenting-Android-Apps-with-Soot

**Comment by CbcWestwolf** [comment]
> why don't try instrumentation directly? I am not sure how well the Jimple front end is maintained.
> Here is a tutorial https://github.com/soot-oss/soot/wiki/Instrumenting-Android-Apps-with-Soot

Is it a better way to use other Soot IR front end like Baf? The reason I write Jimple is to create demo quickly with small code snippets. For this purpose, writing Jimple or even bytecode is the most convenient way.

Of course, it is a solution to insert `JimpleStmt` to `unitChain` in `JimpleBody` of an empty method.

**Comment by MarcMil** [comment]
The directory structure looks strange to me. AFAIK this should be a simple directory containing files with the format ```packagename.classname.jimple```, e.g. ```com.test.Main.jimple```.

**Comment by CbcWestwolf** [comment]
> The directory structure looks strange to me. AFAIK this should be a simple directory containing files with the format `packagename.classname.jimple`, e.g. `com.test.Main.jimple`. The methods are declared within the jimple file.
> 
> Why is "void main(java.lang.String[])" a directory or did I get something wrong?

Oh, it's a mistake to use such a strange name. Now soot could recognize the directory and output something. But I still could not get what I want because of the exception:
> Exception in thread "main" java.lang.RuntimeException: Error: Failed when lexing class Mutant3.
	at soot.JimpleClassSource.resolve(JimpleClassSource.java:109)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:253)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:221)
	at soot.SootResolver.bringToSignatures(SootResolver.java:292)
	at soot.SootResolver.bringToBodies(SootResolver.java:332)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:171)
	at soot.SootResolver.resolveClass(SootResolver.java:141)
	at soot.Scene.loadClass(Scene.java:1069)
	at soot.Scene.loadClassAndSupport(Scene.java:1054)
	at soot.Scene.loadNecessaryClasses(Scene.java:1861)
	at script.Jimple2Class.main(Jimple2Class.java:30)
Caused by: soot.jimple.parser.lexer.LexerException: [7,15] Unknown token: @parameter0;
	at soot.jimple.parser.lexer.Lexer.getToken(Lexer.java:1184)
	at soot.jimple.parser.lexer.Lexer.peek(Lexer.java:36)
	at soot.jimple.parser.parser.Parser.parse(Parser.java:120)
	at soot.jimple.parser.JimpleAST.<init>(JimpleAST.java:60)
	at soot.JimpleClassSource.resolve(JimpleClassSource.java:63)
	... 10 more

It seems that the usage of `@parameter0` is wrong. Can you help me?

**Comment by MarcMil** [comment]
Yes, your 
```
r0 := @parameter0
```
is missing a type.
It's supposed to be
```
r0 := @parameter0: java.lang.String[];
```
Also, your init call is probably supposed to look like this.
```
        specialinvoke $r2.<java.lang.String: void <init>()>();
```
Note the <init>, which indicates a constructor call.
Instead of writing Jimple files from scratch, it might be easier to create them based on existing java class files and modify them afterwards accordingly.

**Comment by CbcWestwolf** [comment]
> Yes, your
> 
> ```
> r0 := @parameter0
> ```
> 
> is missing a type.
> It's supposed to be
> 
> ```
> r0 := @parameter0: java.lang.String[];
> ```
> 
> Also, your init call is probably supposed to look like this.
> 
> ```
>         specialinvoke $r2.<java.lang.String: void <init>()>();
> ```
> 
> Note the `<init>`, which indicates a constructor call.
> Instead of writing Jimple files from scratch, it might be easier to create them based on existing java class files and modify them afterwards accordingly.

OK. Since I still get an empty method body after correcting the errors of parameter and invocation, I decide to modify existing Java class files.
Thanks for your answer!
