### ISSUE TITLE
Question About Including Every Possible Method to the Callgraph

### ISSUE THREAD

**Issue by aralyekta** [soot-oss/soot#1701]
Hi, I have been working with soot to extract inter-procedural CFGs from projects. To do that, I need the callgraph of the whole project but I ran into an issue while doing that and wanted to ask about it.
I realized that soot's CallGraph only includes the method invocations that are reachable from the source methods. It does not include the methods that are unreachable from the source methods. But I need these methods in my callgraph as well. How can I do that?
One possible solution I thought of was to create a Java code which explicitly invokes every possible method of the project in a main function, thus includes these methods in the callgraph. I tested this and it worked for a small code example, but it is really hard to explicitly call each method of the project in a Java code (for some projects, there are approximately 1000 methods in total).
Is there any way that I can include all of the methods (even unreachable ones) and their invocation relationships to soot's callGraph?
Thanks.

**Comment by piskachev** [comment]
You can tell Soot what are the entry points for the call graph. 
https://github.com/soot-oss/soot/wiki/Using-Soot-with-custom-entry-points

To get all the methods, just use the Scene to iterate over all classes and get all methods in a list and set them as entry points.

**Comment by aralyekta** [comment]
That helped, thanks.

**Comment by aralyekta** [comment]
I tried it out. It helped for setting some methods as entry points but for some other methods, even though I added them as entry points, soot's callgraph did not consider them as source methods.  In the below code, **main**, **<init>** and **bar** methods are considered as source methods but **math** and **foo** methods are not considered as source methods. What could be the reason? If you need, I can also show my soot code.

`public class CallGraphs
{

	// This is a comment outside the func
	public static void main(String[] args) 
{


		/*
		*
		*
		*/
		//

		//
		int x = 20;
		int y = 10;
		int z = 5;
		
		if (x < 5)
		{
			// If
			y -= 29;
		}
		else if (x == 10)
		{
			// Else if
			math(x,y);
			z *= 2;
		}
		else
		{
			// Else
			math(x,y);
			//z *= 2;
		}
		int a = 1234;
	}

	public static void math(int x, int y) {
		int sum = x+y;
		int mul = x*y;
		int sub = x-y;
		//foo(sum);
		int test = x*x;
	}

	public static int foo(int x) {
		//System.out.println("Asd");
		if (x < 5) {
			//bar();
			return 2;
		}
		else {
			return 3;
		}
		//bar();
	}

	public static void bar() {
		System.out.println("Bar");
		//foo(2);
	}`

**Comment by piskachev** [comment]
What is the method `checkPackageName` doing?

**Comment by aralyekta** [comment]
It is just a method to check whether the target method belongs to my project of interest. Here is its definition:
`	
public static boolean checkPackageName(SootMethod mtd, String packageName)

	{
		try
		{
			SootClass cls = getClassOf(mtd);
			int packageNameLength = packageName.length();
			return cls.toString().length() >= packageNameLength && cls.toString().substring(0, packageNameLength).equals(packageName);
		}
		catch (Exception e)
		{
			return false;
		}	
	}`

**Comment by piskachev** [comment]
Did you try to run without that call? `if (checkPackageName(methods.get(a), packageName))`
If that does not work, I would debug to see what it is in the Scene and whether the methods `math` and `foo` are there and added to the list of entry points. Other than that the code you process the entry points look good to me.

**Comment by aralyekta** [comment]
I have an another question. I need to get the initial callgraph to store the initial source methods, and after doing that set some entry points and get the new callgraph. Is this possible? If it is, how can I do that?

**Comment by piskachev** [comment]
Yes, that should be possible. You can run as usual, get the initial call graph, process it to get the entry points and store them as you need. Then, you can call again the API `setEntryPoints` and call the CallGraph() constructor second time. Each call to the constructor will create new call graph object with the current state of the Scene.

**Comment by harshita19244** [comment]
@aralyekta if possible could you share your callgraph implementation. I am new to soot and I started working with callgraphs however I keep running into errors.

**Comment by XiaoQB** [comment]
> @aralyekta if possible could you share your callgraph implementation. I am new to soot and I started working with callgraphs however I keep running into errors.

me too, could u send me your callgraph implementation. Thank you very much! @aralyekta
