### ISSUE TITLE
An elegant approach to get enclosing body or enclosing method of soot.Unit

### ISSUE THREAD

**Issue by canliture** [soot-oss/soot#1711]
**Is your feature request related to a problem? Please describe.**
Request A Feature about an elegant approach to **get enclosing body or enclosing method** of **soot.Unit**

The feature is so helpful to locate a statement and its enclosing context/environment, especially for someone to do research on defect/vulnerability/bug location using Soot or FlowDroid.

**Describe the solution you'd like**
add one interface method named *getEnclosingBody* or *getEnclosingMethod* to the interface class **soot.Unit**

**Describe alternatives you've considered**
Now, I want to get a **Stmt**'s enclosing body or method, I have to pre-do something like this:

```java
Map<Unit, SootMethod> stmt2Enclosing = new HashMap<>();
for (SootClass cls : Scene.v().getClasses()) {
    for (SootMethod mtd : cls.getMethods()) {
        if (mtd.hasActiveBody()) {
            for (Unit unit : mtd.retrieveActiveBody().getUnits()) {
                stmt2Enclosing.put(unit, mtd);
            }
        }
    }
}
```
The code above pre-caches the index for the map pair **<Unit -> its enclosing Method>**.
But I don't think it's a good idea to do that. The most user-friendly way is just directly calling **soot.Unit.getEnclosingMethod()** to get Unit's enclosing method or body.

Maybe we can set Unit's enclosing Method/Body when we construct it.

**Additional context**
However, if I myself add a method to the interface soot.Unit, all the non-abstract class must implements the method, it's not a small work.

**Comment by StevenArzt** [comment]
Have you tried ``JimpleBasedInterproceduralCFG.getBodyOf()``? The resulting ``Body`` has a method ``getMethod`` to retrieve the ``SootMethod``.

**Comment by canliture** [comment]
Oh, oh, Thanks!
