### ISSUE TITLE
javax.servlet.http.* is not founded

### ISSUE THREAD

**Issue by HJX-zhanS** [soot-oss/soot#1719]
Hello,
I need to analysis a Java project. When I was analyzing a Java code that `import javax.servlet.http.*`, Soot reported an error `javax.servlet.http.* not founded`. How should I solve this problem?

Thanks!

**Comment by HJX-zhanS** [comment]
> Hello,
> I need to analysis a Java project. When I was analyzing a Java code that `import javax.servlet.http.*`, Soot reported an error `javax.servlet.http.* not founded`. How should I solve this problem?
> 
> Thanks!

**Comment by HJX-zhanS** [comment]
> Hello,
> I need to analysis a Java project. When I was analyzing a Java code that `import javax.servlet.http.*`, Soot reported an error `javax.servlet.http.* is not founded`. How should I solve this problem?
> 
> Thanks!

**Comment by canliture** [comment]
Maybe some dependencies (like servlet-api.jar ... files) should be added to soot_class_path.
`Options.v().set_soot_classpath('path/to/jar')`

**Comment by patricklam** [comment]
There is also the "add directory of jars" option that I added a few months
ago which may help.

**Comment by canliture** [comment]
Yeah, right here #1646

**Comment by HJX-zhanS** [comment]
> Maybe some dependencies (like servlet-api.jar ... files) should be added to soot_class_path.
> `Options.v().set_soot_classpath('path/to/jar')`
> 
> Or if you analysis `.java` Java source code file, soot will not so well support to parse Java source code.

**Comment by HJX-zhanS** [comment]
Thanks for your help! I chose to analysis the `.class` file, and then the problem was solved.
