### ISSUE TITLE
soot.toolkits.graph.HashMutableEdgeLabelledDirectedGraph cannot be cast to soot.toolkits.graph.pdg.HashMutablePDG

### ISSUE THREAD

**Issue by HJX-zhanS** [soot-oss/soot#1723]
Hello, guys
When I used this code to generate a Program Dependence Graph(PDG), I got a problem `soot.toolkits.graph.HashMutableEdgeLabelledDirectedGraph cannot be cast to soot.toolkits.graph.pdg.HashMutablePDG`
```
for (SootClass sc : Scene.v().getApplicationClasses()) {
            for (SootMethod sm : sc.getMethods()) {
                HashMutablePDG pdg=null;
                try {
                    UnitGraph cfg=new CompleteUnitGraph(sm.getActiveBody());
                    pdg=new HashMutablePDG(cfg);
                }
                catch (Exception e){
                    System.out.println(e);
                    continue;
                }
            }
}
```
I find the problem at line 479 of `HashMutablePDG.class`

Can you help me?
Thanks

**Comment by HJX-zhanS** [comment]
I think the problem is caused by the fact that `this.clone` is of type `HashMutableEdgeLabelledDirectedGraph` and the code forces the child class `HashMutablePDG` to be converted to the parent class `HashMutableEdgeLabelledDirectedGraph`

**Comment by Kritip123** [comment]
### @HJX-zhanS 

I am interested to solve this issue and also work on soot. Are there any slack or discord channels, so that I can discuss it with the members?

**Comment by HJX-zhanS** [comment]
> ### @HJX-zhanS
> I am interested to solve this issue and also work on soot. Are there any slack or discord channels, so that I can discuss it with the members?

Well, we can use github' s issues to discuss this.

**Comment by canliture** [comment]
> I think the problem is caused by the fact that `this.clone` is of type `HashMutableEdgeLabelledDirectedGraph` and the code forces the child class `HashMutablePDG` to be converted to the parent class `HashMutableEdgeLabelledDirectedGraph`.
> 

Yeah, I have reproduced the crashing problem; I think this is just a bug in Soot.

**Comment by Kritip123** [comment]
> > ### @HJX-zhanS
> > I am interested to solve this issue and also work on soot. Are there any slack or discord channels, so that I can discuss it with the members?
> 
> Well, we can use github' s issues to discuss this.

Yeah sure. Let me have a look at any good first issue to begin with then.
