### ISSUE TITLE
Regarding the purpose of `split_new` in TypeResolver.java

### ISSUE THREAD

**Issue by flankerhqd** [soot-oss/soot#1760]
When looking into the issue https://github.com/secure-software-engineering/FlowDroid/issues/332, it seems the root cause is the `split_new` function of `TypeResolver`, which introduces new locals for the following code:

```java
public void onResume() {
    super.onResume();

    try {
        URL url = new URL(this.mUrl);
        String host = url.getHost();
        if (host.contains("abc.com")) {
            this.mWebView.loadUrl(this.mUrl);
        }
    } catch (MalformedURLException e) {
        e.printStackTrace();
    }
}
```
Which added locals for java.net.URL from $r5 to {$r5, $r2} 
```java
public void onResume()
{
    com.test.ActivityName $r0;
    java.lang.String $r1;
    boolean $z0;
    android.webkit.WebView $r3;
    java.lang.Throwable $r4;
    java.net.URL r5;
    java.net.MalformedURLException r6;
    $r0 := @this: com.test.ActivityName;
    specialinvoke $r0.<androidx.appcompat.app.AppCompatActivity: void onResume()>();
    r5 = new java.net.URL;  //no $r2
    $r1 = $r0.<com.test.ActivityName: java.lang.String mUrl>;
    label1:
    specialinvoke r5.<java.net.URL: void <init>(java.lang.String)>($r1); 
    $r1 = virtualinvoke r5.<java.net.URL: java.lang.String getHost()>();
    $z0 = virtualinvoke $r1.<java.lang.String: boolean contains(java.lang.CharSequence)>("abc.com");
}
```
Which the `split_new` changes the jimple to 
```java
1    public void onResume() {
2        com.test.ActivityName $r0;
3        java.lang.String $r1;
4        java.net.URL $r2, r5;
5        boolean $z0;
6        android.webkit.WebView $r3;
7        java.lang.Throwable $r4;
8        java.net.MalformedURLException r6;
9        $r0 := @this: com.test.ActivityName;
10        specialinvoke $r0.<androidx.appcompat.app.AppCompatActivity: void onResume()>();
11        r5 = new java.net.URL;
12        $r2 = r5; //<- new $r2 introduced
13        $r1 = $r0.<com.test.ActivityName: java.lang.String mUrl>;
14        label1:
15        specialinvoke r5.<java.net.URL: void <init>(java.lang.String)>($r1);
16        $r1 = virtualinvoke $r2.<java.net.URL: java.lang.String getHost()>(); //<- $r2 is used
17        $z0 = virtualinvoke $r1.<java.lang.String: boolean contains(java.lang.CharSequence)>("abc.com”);
18    }
```
Which introduces some additional burden for follow up analysis (backward alias needed)
I'm not sure about the purpose of `split_new`. Would some one shed some light on this? Would removing this function break something?

The test case (apk) is at
https://github.com/secure-software-engineering/FlowDroid/files/6245241/Issue332.zip

**Comment by StevenArzt** [comment]
We have at some point introduced a local splitting, because Dalvik code may re-use the same initialization for different types afterwards, e.g., initialize a register to zero, and then use it as a number in one branch, as an object in second branch, and as an array in a third branch. There is no compatible typing for this, unless we split the initialization into three different assignments to three different locals. Back then, we decided that splitting more locals was likely better then having Jimple code that does not have a valid typing. This may lead to over-splitting in cases where it is not necessary, but avoids these total failures in case we need the heavy splitting.

**Comment by flankerhqd** [comment]
Hi Steven:

Thanks for the reply. 

Based on the observation, it seems the `split_new` was used specially for when a new object is created, i.e. for this case, the `new URL` statement. (https://github.com/soot-oss/soot/blob/65acc21e2d2dfeb055603b280d5a760208373988/src/main/java/soot/jimple/toolkits/typing/fast/TypeResolver.java#L529)

Is it serving the same purpose, as you previously mentioned?

Thanks.

**Comment by flankerhqd** [comment]
Figured out a way to fix that. Closing it now. Thanks.
