### ISSUE TITLE
java.lang.RuntimeException: Invalid Array Type occured in FillArrayDataInstruction: java.lang.Object

### ISSUE THREAD

**Issue by jpstotz** [soot-oss/soot#1806]
Used version: branch `develop` 34f871e4e24ca4dd18b4a1bff701c9eff56f2f00

**To reproduce**
Try to retrieve the body of `<X.D8D: X.1n9 AGs(X.1oJ,int,int)>`

**Stacktrace**
```
java.lang.RuntimeException: Invalid Array Type occured in FillArrayDataInstruction: com.facebook.flexlayout.styles.FlexItemCallback
	at soot.dexpler.instructions.FillArrayDataInstruction.getArrayElement(FillArrayDataInstruction.java:195)
	at soot.dexpler.instructions.FillArrayDataInstruction.jimplify(FillArrayDataInstruction.java:101)
	at soot.dexpler.DexBody.jimplify(DexBody.java:634)
	at soot.dexpler.DexMethod$1.getBody(DexMethod.java:120)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:446)

```

[com.facebook.orca_337.1.0.11.118 (297415372) - stripped.apk.zip](https://github.com/soot-oss/soot/files/7642259/com.facebook.orca_337.1.0.11.118.297415372.-.stripped.apk.zip)

**Comment by jpstotz** [comment]
I got again a very similar error on a different app:

```
java.lang.RuntimeException: Invalid Array Type occured in FillArrayDataInstruction: java.lang.Object
	at soot.dexpler.instructions.FillArrayDataInstruction.getArrayElement(FillArrayDataInstruction.java:195)
	at soot.dexpler.instructions.FillArrayDataInstruction.jimplify(FillArrayDataInstruction.java:101)
	at soot.dexpler.DexBody.jimplify(DexBody.java:639)
	at soot.dexpler.DexMethod$1.getBody(DexMethod.java:117)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:454)
	at soot.SootMethod.retrieveActiveBody(SootMethod.java:409)
```

@StevenArzt I am a bit surprised because based on the Soot source code it seems like Soot does support arrays with primitives like `byte[]`, `char[]`, `int[]`, `long[]` and so on but not simple arrays like `java.lang.Object[]`?

**Comment by StevenArzt** [comment]
I'm not even sure whether the array filling commands in the Dalvik IR support objects. I have only seen them with primitives so far. If they support objects, then someone needs to add support for that to Soot.

**Comment by jpstotz** [comment]
I haven't looked into the spec of `fill-array-data` but it seems that FillArrayDataInstruction makes too many assumptions and thus fails on complex cases:

I have identified two problems:

1. FillArrayDataInstruction simply takes the first `new-array` instruction it finds that operates on the same register to determine the array type. The possibility that there are multiple `new-array` instructions with different types using the same register seems not to be considered by the code (if I interpret it correctly).  

2. In the app I am trying to load the array is a return value from a function call, therefore no matter what `new-array` instruction is found it will belong to a different array. As the same register is used with other array types it returns the wrong type. 

These two problems make FillArrayDataInstruction fail.

**Comment by StevenArzt** [comment]
Do you have the time to fix the ``FillArrayDataInstruction``?

**Comment by jpstotz** [comment]
@StevenArzt I will try to do so. 

From my perspective the current implementation of `FillArrayDataInstruction` tries to re-implement the wheel:

FillArrayDataInstruction is executed in a very early stage when lifting DEX byte code to Jimple. 
Finding where a variable/register is assigned to get the type of the variable is something Soot will do anyway at a later stage using an existing analysis.  

From my understanding of soot it would be better to not trying to identify the exact data type in FillArrayDataInstruction.
Instead we should focus on the constant data that is included in the `fill-array-data` instruction and based on it's value make it e.g. a `Integer1Type`(aka `[0..1]`) or one of the other intermediate types. 

Then the DEX byte code lifting can continue and later, when we have a Jimple body we can apply a `LocalDefs` analysis to get the point where the array is defined/assigned and thus get the type of the array and then convert the intermediate types into a concrete final type.

**Comment by StevenArzt** [comment]
That sounds reasoble. It's definitely worth a try.
