### ISSUE TITLE
Endless loop in UseChecker

### ISSUE THREAD

**Issue by jpstotz** [soot-oss/soot#1812]
**Describe the bug**
Retrieving the active body of a certain method causes an endless loop (does not finish after more than 48 hours).
`<org.telegram.messenger.MessagesController: int addDialogToFolder(java.util.ArrayList,int,int,java.util.ArrayList,long)>`

This is caused by an endless while loop in `soot.jimple.toolkits.typing.fast.UseChecker`
https://github.com/soot-oss/soot/blob/develop/src/main/java/soot/jimple/toolkits/typing/fast/UseChecker.java#L298-L323

@MarcMil As far as I can see this loop was introduced by you in 8af4b1e50aa982d2b68c9d868e982d0158d922b4. Can you explain a bit how it is supposed to work and how you make sure it ends?

**To reproduce**
```
File apkFile = new File("org.telegram.messenger_8.2.7 (24703) - stripped.apk");

Options o = Options.v();
o.set_verbose(true);
o.set_process_multiple_dex(true);
o.set_allow_phantom_refs(true);
o.set_whole_program(true);
o.set_process_dir(Collections.singletonList(apkFile.getAbsolutePath()));
o.set_prepend_classpath(false);
o.set_process_multiple_dex(true);
o.set_coffi(false);

File androidJarsDir = new File("<path to soot android jars>");
o.set_android_jars(androidJarsDir.getAbsolutePath());
o.set_src_prec(Options.src_prec_apk);

Main.v().autoSetOptions();

Scene.v().loadNecessaryClasses();

SootClass sootClass = Scene.v().getSootClass("org.telegram.messenger.MessagesController");
SootMethod m = sootClass.getMethod("int addDialogToFolder(java.util.ArrayList,int,int,java.util.ArrayList,long)"); 
Body body = m.retrieveActiveBody();
System.out.println(body);

```
[org.telegram.messenger_8.2.7 (24703) - stripped.apk.zip](https://github.com/soot-oss/soot/files/7675082/org.telegram.messenger_8.2.7.24703.-.stripped.apk.zip)

**Comment by MarcMil** [comment]
My changes should not change the previous semantics of the loop significantly. It would be interesting to know whether the previous version of the loop runs into the same problem (I'd assume that it does).

**Comment by MarcMil** [comment]
In any case, it would be interesting to have the exact APK you were using.

**Comment by jpstotz** [comment]
@MarcMil  Sorry forgot to append the necessary classes.dex. See my updated first post.

**Comment by jpstotz** [comment]
@MarcMil When I revert `UseChecker.java` to https://raw.githubusercontent.com/soot-oss/soot/deac637b4c54a65633db868e3c7dfb0d832ee8bd/src/main/java/soot/jimple/toolkits/typing/fast/UseChecker.java loading the mentioned method works without any noticeable delay.

**Comment by MarcMil** [comment]
Alright. I assumed it was the outer loop that does not terminate. The use-def chain seems to be in a loop here. With the fix it should work now.

**Comment by MarcMil** [comment]
This inner loop should check whether it finds the definition of an array, thus determining the type of variables in statements which read an element from this array.

**Comment by jpstotz** [comment]
@MarcMil Thanks for fixing
