### ISSUE TITLE
Outer class not set in SootClass 

### ISSUE THREAD

**Issue by johanneslerch** [soot-oss/soot#183]
Hi,

i was recently trying to access outer classes and used SootClass.getOuterClass for that. But, i realised the accessed field is never written. SootClass.setOuterClass seems to be not called if applying soot on Java bytecode. Eclipse shows the following callers of that method:
soot.javaToJimple.ClassResolver 
soot.JastAddJ.ClassDecl
soot.JastAddJ.InterfaceDecl

According to Eric there should be some caller from the coffi package. 
I labelled this as bug and not enhancement, because Eric thinks it has been working in the past for bytecode.

Does someone know what happened to that functionality? Would also be nice if someone could confirm this issue as at least to my experience it is most of the time not a bug in soot, but in the usage of soot.

Regards,
Johannes

**Comment by scg03** [comment]
The fixes #183 for Coffi in the commit 348c20359802693f65e1c54b50b89b69068ba65e seems to be missing.

**Comment by StevenArzt** [comment]
@scg03 Which fixes are you exactly referring to? Util.java got patched for Coffi.
