### ISSUE TITLE
Can soot accept the .dex file as input directly?

### ISSUE THREAD

**Issue by 99zikke** [soot-oss/soot#1838]
There are some shelled apks that I want to analyze. And I get some .dex files after I remove their shells. I want to know can soot accept the .dex file as input directly? I didn't see this option for .dex file in the interface : Options.v().set_src_prec(Options.src_prec_XXX);. 

By the way, the reason why I didn't choose the option "Options.v().set_src_prec(Options. src_prec_class);" is that when I use the dex2jar.jar to convert the .dex files to class.jar files, sometimes an error will cause the conversion to fail.

I'd really appreciate it if you could help me.

**Comment by jpstotz** [comment]
Have you tried to just use `Options.src_prec_apk` and then provide the dex file as input? I think internally Soot uses the file extension to select the necessary class loader:
https://github.com/soot-oss/soot/blob/develop/src/main/java/soot/SourceLocator.java#L114-L123

**Comment by 99zikke** [comment]
@jpstotz Yes, this worked! 
Thank you very much!
