### ISSUE TITLE
About implicit control flow analyais

### ISSUE THREAD

**Issue by YuXinFan** [soot-oss/soot#1868]
I'm doing an interprocedural taint analysis of a subset of Java language programs using soot's `DefaultJimpleIFDSTabulationProblem`.
The `IFDS` is the only one I find in soot for interprocedural analysis. But a key feature I want is implicit control flow analysis, eg:
```Java
int a; int b;
int richer = 0; int max = a;
if ( max < b ){
   max = b;
   richer = 1;
}
```

as `a` and `b` are tainted, so the condition `max < b ` is tainted and results in both `richer` and `max` being tainted. 
But seems IFDS doesn't have the flow from condition to statements inside the subblock of control statements. 

Does soot contain functionality for doing this?

**Comment by StevenArzt** [comment]
If you want to do taint analysis with Soot, have a look at [FlowDroid](https://github.com/secure-software-engineering/FlowDroid). That's a full taint analysis implementation using IFDS. It also supports implicit taints, i.e., control flow dependencies.

**Comment by YuXinFan** [comment]
@StevenArzt Thanks.  Your Thesis of FlowDroid is helpful.
