### ISSUE TITLE
CallGraph's removeEdges method maybe has a bug.

### ISSUE THREAD

**Issue by gdbhub** [soot-oss/soot#1874]
https://github.com/soot-oss/soot/blob/develop/src/main/java/soot/jimple/toolkits/callgraph/CallGraph.java

CallGraph's removeEdges  method maybe has a bug.

```java
  public boolean removeEdges(Collection<Edge> edges) {
    if (!edges.removeAll(edges)) {
      return false;
    }
    for (Edge e : edges) {
      removeEdge(e, false);
    }
    reader.remove(edges);
    return true;
  }
```

replace
>  if (!edges.removeAll(edges))

to

>  if (!this.edges.removeAll(edges)) {

**Comment by jpstotz** [comment]
Indeed, the code `edges.removeAll(edges)` doesn't make much sense and nobody noticed it for two years (code was added in https://github.com/soot-oss/soot/commit/ea001e0e7ebd1c74a31d610ca7488dc5b0cc47c by @MarcMil).

**Comment by StevenArzt** [comment]
That's indeed a bug. Can you open a merge request with a fix?

**Comment by gdbhub** [comment]
😓 my first pr.
