### ISSUE TITLE
soot.SootResolver$SootClassNotFoundException when trying to process a compiled akka agent .class file

### ISSUE THREAD

**Issue by eikNamo** [soot-oss/soot#1888]
Steps to reproduce:
1.) Go to the output directory of compiled .class files
2.) Issue the command bellow

Files used to reproduce: 
1.) Classic Akka actor framework
2.) Scala java library that is provided with IntelliJ IDEA (versions can be found in the paths of the command below)

Soot version: <pre>trunk</pre>

Command line:
<pre>java -cp ..\sootclasses-trunk-jar-with-dependencies.jar soot.Main -cp '.;C:\Users\mzdan\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\typesafe\akka\akka-actor_2.12\2.5.13\akka-actor_2.12-2.5.13.jar;C:\Users\mzdan\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\modules\scala-java8-compat_2.12\0.8.0\scala-java8-compat_2.12-0.8.0.jar;C:\Users\mzdan\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala-library\2.12.15\scala-library-2.12.15.jar;C:\Users\mzdan\.jdks\corretto-17.0.3\lib\jrt-fs.jar;C:\Users\mzdan\IdeaProjects\akka-quickstart-scala\thesis-tests\target\scala-2.12\classes\initial_test\BasicAgent$.class' -pp -process-dir .</pre>

Max Memory:
<pre>3623MB</pre>

Stack trace:
<pre>soot.SootResolver$SootClassNotFoundException: couldn&#39;t find class: initial_test.BasicAgent$ (is your soot-class-path set properly?)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:245)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:221)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:182)
	at soot.SootResolver.resolveClass(SootResolver.java:141)
	at soot.Scene.loadClass(Scene.java:1009)
	at soot.Scene.loadClassAndSupport(Scene.java:994)
	at soot.Scene.loadNecessaryClasses(Scene.java:1822)
	at soot.Main.run(Main.java:241)
	at soot.Main.main(Main.java:141)
</pre>

Basically, for some reason, the soot cannot find and use the .class file even when it is in the same directory where the analysis is happening AND when the path to "initial_test.BasicAgent$.class" file is explicitly stated with "-cp" parameter

The directory where the command is executed:
<pre>    Directory: C:\Users\mzdan\IdeaProjects\akka-quickstart-scala\thesis-tests\target\scala-2.12\classes\initial_test

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        2022-07-08     21:54           4213 BasicAgent$.class
-a----        2022-07-08     21:54           2903 BasicAgent$Counter$$anonfun$countReceive$1.class
-a----        2022-07-08     21:54            702 BasicAgent$Counter$.class
-a----        2022-07-08     21:54           1919 BasicAgent$Counter$Decrement$.class
-a----        2022-07-08     21:54           1919 BasicAgent$Counter$Increment$.class
-a----        2022-07-08     21:54           1903 BasicAgent$Counter$Print$.class
-a----        2022-07-08     21:54           4186 BasicAgent$Counter.class
-a----        2022-07-08     21:54            803 BasicAgent$delayedInit$body.class
-a----        2022-07-08     21:54           2412 BasicAgent.class
-a----        2022-07-17     13:03           3144 SootPlayground$.class
-a----        2022-07-17     13:03            831 SootPlayground$delayedInit$body.class
-a----        2022-07-17     13:03           1148 SootPlayground.class
</pre>

P.S. If needed, I can provide the .class file(s)

**Comment by jpstotz** [comment]
I don't think you can include a class file directly in the `cp` argument of Java. You always specify the root directory where the packages and class files are located. If I remember correctly Java uses the file path to search for the class file that should be loaded. So you have to add `C:\Users\mzdan\IdeaProjects\akka-quickstart-scala\thesis-tests\target\scala-2.12\classes` to the class path.

**Comment by eikNamo** [comment]
I see, I assumed that Soot would find them since it is analyzing the whole directory where the same class file is located. In any case, that change fixed it but it seems I'm still missing certain dependencies/class files that I need to include.

I also have some classpath issues when trying to get/load java.lang.Object into Soot within Scala (mainly that it couldn't find it) but I assume it is because of my own lack of knowledge. So I would be really grateful if I could get some suggestions/answers in the discussion section here https://github.com/soot-oss/soot/discussions/1889
