### ISSUE TITLE
The isVisible() method in FastHierarchy are invoked by wrong arguments.

### ISSUE THREAD

**Issue by RichardHoOoOo** [soot-oss/soot#1936]
The `isVisible()` method in `FastHierarchy` are invoked by wrong arguments.

The declaration of `isVisible` is
https://github.com/soot-oss/soot/blob/79477e8eb9f03dc8c554484fda3dae1f7b5c63cf/src/main/java/soot/FastHierarchy.java#L597

The callsites are
https://github.com/soot-oss/soot/blob/79477e8eb9f03dc8c554484fda3dae1f7b5c63cf/src/main/java/soot/FastHierarchy.java#L865

https://github.com/soot-oss/soot/blob/79477e8eb9f03dc8c554484fda3dae1f7b5c63cf/src/main/java/soot/FastHierarchy.java#L900

Obviously, the 1st parameter should be the class to check and the 2nd parameter should be the class declaring the method got from an invoke expression. But when `isVisible` is invoked, arguments are passed in at wrong places. For example, `declaringClass` should be passed to the 2nd parameter, but it is actually passed to the 1st parameter.

This bug was originally found when I was using FlowDroid. Please refer to this [issue](https://github.com/secure-software-engineering/FlowDroid/issues/546) to see the bug reproduction and consequences.

**Comment by StevenArzt** [comment]
Can you open a pull request? That's really an interesting bug that needs to be fixed. I wonder why this hasn't lead to many other very strange bugs before, given that it should heavily affect callgraph generation.

**Comment by RichardHoOoOo** [comment]
Hold on @StevenArzt , it turns out fixing by switching the arguments introduces new issues.

For example

```
abstract class K0 {
    protected void foo() {...}
}

class K1 extends K0 {
}
```

If I call `foo` like this `new K1().foo();`, the edge to `K0:foo()` does not appear in the call graph. If I do not apply the "fix", the call graph is correct.

I tried to debug the problem and I found the problem occurs in the following code snippet
https://github.com/soot-oss/soot/blob/ea2f0c2956fda48698416dd342233f7df15b5d76/src/main/java/soot/jimple/toolkits/callgraph/VirtualCalls.java#L104-L105

In the above case, `cls` is `x.x.K1` and `callee` is `<x.x.K1: void foo()>` (although `foo` is declared in `K0`). Eventually, the following loop will run 2 times

https://github.com/soot-oss/soot/blob/ea2f0c2956fda48698416dd342233f7df15b5d76/src/main/java/soot/FastHierarchy.java#L862-L876

In the 1st round, `candidate` is null because we cannot find `foo` in `K1`. In the 2nd round, `isVisible` is invoked as `isVisible(K1, K0, ...)`, therefore `<x.x.K0: void foo()>` is returned.

If we apply the fix by switching the arguments, `isVisible` is invoked as `isVisible(K0, K1, ...)` in the 2nd round, therefore nothing is returned. Then the call graph is wrong.

Do you have a better idea of how to fix the issue?

**Comment by StevenArzt** [comment]
I'm slightly confused. If we switch the parameters, the second round call should be ``isVisible(K0, K0, ...)``, because the method ``foo`` is declared in ``K0``, so ``declaringClass`` should always be ``K0``. I don't see how the declared callee can be ``K1.foo``.

**Comment by RichardHoOoOo** [comment]
I agree the `declaringClass` should always be `K0`, but if you output it at the beginning of `resolveMethod`, you will see `K1`, which is out of my expectation

https://github.com/soot-oss/soot/blob/79477e8eb9f03dc8c554484fda3dae1f7b5c63cf/src/main/java/soot/FastHierarchy.java#L842

**Comment by StevenArzt** [comment]
That might be the case, but I doubt that it's correct. That would imply that there is a method ``foo`` declared in ``K1``. Maybe that's our core problem. If there was a ``foo`` method in ``K1``, it would actually be correct to rule out ``K0.foo()`` as a callee.

What is your call stack? If it comes from the overload L767, this would mean that someone created a ``SootMethod`` for ``K1.foo``, which would be plain wrong.

https://github.com/soot-oss/soot/blob/79477e8eb9f03dc8c554484fda3dae1f7b5c63cf/src/main/java/soot/FastHierarchy.java#L767

**Comment by RichardHoOoOo** [comment]
@StevenArzt  Yes, it comes from L767

BTW, I check the smali code and it looks like Android compiles it this way
```
.line 223
    new-instance v0, Lcom/example/myapplication/K1;

    invoke-direct {v0}, Lcom/example/myapplication/K1;-><init>()V

    invoke-virtual {v0}, Lcom/example/myapplication/K1;->foo()V
```

But there is no `foo` in `K1` in the smali code

**Comment by StevenArzt** [comment]
ok, then you have different call hierarchy, i.e., not from a ``SootMethod``. Instead, you have a ``MethodRef`` that points to a non-existing method and the purpose of lines L862 and following would be to traverse the hierarchy to resolve it. That actually sheds a different light on the issue.

In that case, swapping the arguments no longer seems right. ``From`` should actually be the ``declaringClassx``, i.e., the declared target of our dispatch. If the bytecode tries to invoke the non-existing method ``K1.foo()``, the actual callee must be visible from K1. Implicitly, think as if there was a ``K1.foo()`` that simply calls ``super.foo()``. The actual callee must therefore be visible from ``K1`` and its hypothetical super call. The target is then the concrete type, i.e., the callee of the hypothetical super call. If you look at it this way, the code is correct and the fix is wrong.

**Comment by RichardHoOoOo** [comment]
Yes, I agree with you from this perspective. But if we change the code like this, i.e., override `foo` in `K1`.

```
abstract class K0 {
    protected void foo() {...}
}

class K1 extends K0 {
   protected void foo() {...}
}
``` 

This time, invoking  `new K1().foo();` results in `... ==> <K0: void foo()>` in the call graph. But the correct one should be `... ==> <K1: void foo()>`. Switching arguments can obviously fix this case.

**Comment by StevenArzt** [comment]
In that case, we should get ``isVisible(K1, K1, ...)``, because ``declaringClass`` is obviously ``K1``, and ``baseType`` should also be ``K1``, so we should start with ``concreteType = K1`` in the first round. ``isVisible`` should return ``true``, and we should return that candidate, if I'm not mistaken.

I don't have a debugging instance right now, so I'm just reasoning about the algorithm.

**Comment by RichardHoOoOo** [comment]
Hi @StevenArzt , please ignore the deleted rely, that was wrong. Let's just go back to the FlowDroid case. I reorganize it this way

```
abstract class K0 {
    protected void foo() {
        goo();
    }

    protected void goo() {...}
}

class K1 extends K0 {
    protected void foo() {
        super.foo();
    }

    protected void goo() {...}
}
```

This time, calling `new K1().foo();` results in `<x.x.K0: void foo()> ==> <x.x.K0: void goo()>`if we do not switch the arguments.

If we switch the arguments, the result is `<x.x.K0: void foo()> ==> <x.x.K1: void goo()>`.

So in this example, switching the arguments can fix the issue.

**Comment by RichardHoOoOo** [comment]
In this case, the `concreteType = K1` and `declaringClass = K0` when `goo` is invoked. 

In the 1st round, `isVisible(K0, K1, ..)` returns false.
In the 2nd round, `isVisible(K0, K0, ..)` returns true. Therefore `<x.x.K0: void goo()>` is returned.

After switching the arguments, in the 1st round, `isVisible(K1, K0, ..)` returns true. Therefore, <x.x.K1: void goo()>` is returned.

**Comment by StevenArzt** [comment]
Right. I think the core difference is that the declared callee doesn't exist in the first case, whereas it does exist in the second case. I was already wondering earlier on whether removing the visibility check would be better in the first case, i.e., when the declared callee doesn't exist. In that case, you look for the dispatch target by walking the inheritance chain, which is pretty much the same thing that the visibility checker does.

If that works, we can swap the arguments in the second case and just don't check visibility in the first case.

**Comment by RichardHoOoOo** [comment]
So we can have a check right before L862 to see if the callee exist or not. If it does not exist, we walk through the inheritance chain. Otherwise, we go into the loop at L862 with arguments being swapped. Am I right?

**Comment by StevenArzt** [comment]
Yes, that's basically the idea. With that fix, we should ensure that the Soot and FlowDroid test cases still work. That's alredy a larger number of test cases to gain some confidence.

We can also re-run the test cases of our commercial code scanner once the new Soot version is compiled. Those test cases are pretty large, so we would gain even more confidence.
