### ISSUE TITLE
Does soot support generating jimple files for java>=17?

### ISSUE THREAD

**Issue by michaelphop** [soot-oss/soot#1997]
Or I need always to run my projects for up to specific java version (jimple generation wise)?

Thanks.

**Comment by StevenArzt** [comment]
The Jimple should be fairly agnostic of the classfile version of the input files. Some Jimple features such as ``invoke-dynamic`` might be used or not depending on what is in your input file. If you read in older class files, they will not contain dynamic invokes, and hence you won't have them in your Jimple code.

I'm not sure I understand your question correctly, though.

**Comment by michaelphop** [comment]
Thanks.
Yes I was asking whether Jimple is agnostic of the classfile version.
