### ISSUE TITLE
I want know upgrade release note

### ISSUE THREAD

**Issue by gai410388544** [soot-oss/soot#2058]
I want to see some information from release4.2.1 to release4.4.1

**Comment by StevenArzt** [comment]
Are you looking for a list of changes? We don't really maintain a changelog. From what I remember, there were a lot of smaller changes and bugfixes.

**Comment by gai410388544** [comment]
Yes, I found some changes are added switch configuration and interface changes (virtualCalls.resolveNonSpecial), so I want to know how to configure will same as 4.2.1

**Comment by gai410388544** [comment]
是的，我发现还有一些改动是增加了开关配置和接口的变化（virtualCalls.resolveNonSpecial），所以我想知道

**Comment by gai410388544** [comment]
Yes, I found that there are some changes added to the switch configuration and interface changes (virtualCalls.resolveNonSpecial), so I wonder
