### ISSUE TITLE
ConcurrentModificationException when trying to use Dexpler and Dava

### ISSUE THREAD

**Issue by GeoffreyHecht** [soot-oss/soot#207]
Hello,

I'm trying to use Dexpler to generate .java files from apk following the instruction provided on http://www.abartel.net/dexpler/ and I'm getting the following output when trying on the snake.apk provided as example ( http://www.abartel.net/static/dexpler/snake.apk ) :

Soot started on Tue May 13 13:30:21 EDT 201
Could not find sdk version in Android manifest! Using default: 15
Using '/home/geoffrey/These/decompiler/android-platforms//android-15/android.jar' as android.jar
Warning: java.lang.NoClassDefFoundError is a phantom class!
Warning: java.lang.StringBuffer is a phantom class!
Warning: java.lang.Boolean is a phantom class!
Warning: java.lang.Long is a phantom class!
Warning: java.lang.Integer is a phantom class!
Warning: java.lang.Short is a phantom class!
Warning: java.lang.Float is a phantom class!
Warning: java.lang.Double is a phantom class!
Warning: java.lang.Throwable is a phantom class!
Warning: java.lang.Class is a phantom class!
Warning: java.lang.Character is a phantom class!
Warning: java.lang.AssertionError is a phantom class!
Warning: java.lang.Byte is a phantom class!
Warning: java.lang.Void is a phantom class!
Warning: java.lang.ClassFormatError is a phantom class!
Warning: java.lang.InstantiationError is a phantom class!
Warning: java.lang.Runnable is a phantom class!
Warning: java.lang.ref.Finalizer is a phantom class!
Warning: java.lang.IncompatibleClassChangeError is a phantom class!
Warning: java.lang.NoSuchFieldError is a phantom class!
Warning: java.lang.StackOverflowError is a phantom class!
Warning: java.lang.Thread is a phantom class!
Warning: java.lang.IllegalAccessError is a phantom class!
Warning: java.lang.ArrayStoreException is a phantom class!
Warning: java.lang.NoSuchMethodError is a phantom class!
Warning: java.lang.LinkageError is a phantom class!
Warning: java.lang.ExceptionInInitializerError is a phantom class!
Warning: java.lang.InternalError is a phantom class!
Warning: java.lang.VerifyError is a phantom class!
Warning: java.io.Serializable is a phantom class!
Warning: java.lang.ArrayIndexOutOfBoundsException is a phantom class!
Warning: java.lang.ClassCastException is a phantom class!
Warning: java.lang.ArithmeticException is a phantom class!
Warning: java.lang.IndexOutOfBoundsException is a phantom class!
Warning: java.lang.AbstractMethodError is a phantom class!
Warning: java.lang.Object is a phantom class!
Warning: java.lang.ThreadDeath is a phantom class!
Warning: java.lang.String is a phantom class!
Warning: java.lang.UnknownError is a phantom class!
Warning: java.lang.ClassCircularityError is a phantom class!
Warning: java.lang.Cloneable is a phantom class!
Warning: java.lang.NegativeArraySizeException is a phantom class!
Warning: java.lang.UnsatisfiedLinkError is a phantom class!
Warning: java.lang.Error is a phantom class!
Warning: java.lang.OutOfMemoryError is a phantom class!
Warning: java.lang.IllegalMonitorStateException is a phantom class!
Warning: java.lang.RuntimeException is a phantom class!
Warning: java.lang.NullPointerException is a phantom class!
Warning: java.lang.ClassNotFoundException is a phantom class!
Warning: is a phantom class!
Warning: android.app.Activity is a phantom class!
Warning: android.content.Context is a phantom class!
Warning: android.content.res.Resources is a phantom class!
Warning: android.content.res.TypedArray is a phantom class!
Warning: android.graphics.Bitmap$Config is a phantom class!
Warning: android.graphics.Bitmap is a phantom class!
Warning: android.graphics.Canvas is a phantom class!
Warning: android.graphics.Paint is a phantom class!
Warning: android.graphics.drawable.Drawable is a phantom class!
Warning: android.os.Bundle is a phantom class!
Warning: android.os.Handler is a phantom class!
Warning: android.os.Message is a phantom class!
Warning: android.util.AttributeSet is a phantom class!
Warning: android.util.Log is a phantom class!
Warning: android.view.KeyEvent is a phantom class!
Warning: android.view.View is a phantom class!
Warning: android.widget.TextView is a phantom class!
Warning: java.io.PrintStream is a phantom class!
Warning: java.lang.CharSequence is a phantom class!
Warning: java.lang.Math is a phantom class!
Warning: java.lang.StringBuilder is a phantom class!
Warning: java.lang.System is a phantom class!
Warning: java.lang.reflect.Array is a phantom class!
Warning: java.util.ArrayList is a phantom class!
Warning: java.util.Iterator is a phantom class!
Warning: java.util.Random is a phantom class!
array element type: (filled narr)int
Decompiling com.example.android.snake.SnakeView... 
Decompiling com.example.android.snake.SnakeView$RefreshHandler... 
Decompiling com.example.android.snake.SnakeView$Coordinate... 
Decompiling com.example.android.snake.R$attr... 
Decompiling com.example.android.snake.R$string... 
Decompiling com.example.android.snake.R$drawable... 
Decompiling com.example.android.snake.R$styleable... 
Decompiling com.example.android.snake.R$layout... 
Decompiling com.example.android.snake.TileView... 
Decompiling com.example.android.snake.Snake... 
Decompiling com.example.android.snake.R$id... 
Decompiling com.example.android.snake.R... 
Decompiling ...
Analyzing ./out/dava/src/com/example/android/snake/SnakeView.java... 
Exception in thread "main" java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)
at java.util.ArrayList$Itr.next(ArrayList.java:831)
at soot.PackManager.postProcessDAVA(PackManager.java:665)
at soot.PackManager.writeOutput(PackManager.java:501)
at soot.Main.run(Main.java:205)
at soot.Main.main(Main.java:146)

I'm using the last develop version of Soot and the following script http://pastebin.com/4qjJLKru.
I can't figure what can be the source of this exception ?

Thank you for your help,

Geoffrey.

**Comment by pavanupb** [comment]
Closed due to inactivity. Please re-open if still relevant.
