### ISSUE TITLE
Outdated snapshot version

### ISSUE THREAD

**Issue by rillig** [soot-oss/soot#2074]
https://soot-oss.github.io/soot/ says:
>     <version>4.1.0-SNAPSHOT</version>

The linked Sonatype repository only has versions 4.5.0-SNAPSHOT and 4.6.0-SNAPSHOT.

**Comment by StevenArzt** [comment]
The text on the website is a bit outdated and we have released new Soot versions in the meantime. I have updated the website source and the build is currently running.
