### ISSUE TITLE
no apk file given error

### ISSUE THREAD

**Issue by mangeshkaslikar** [soot-oss/soot#208]
Hi 

I was running the AndroidInstrument.java available on the Soot Blog available at the link. 

http://www.bodden.de/2013/01/08/soot-android-instrumentation/

I was getting the following error : 

Soot started on Thu May 15 21:19:12 EDT 2014
Exception in thread "main" java.lang.RuntimeException: no apk file given
at soot.Scene.defaultClassPath(Scene.java:469)
at soot.Scene.getSootClassPath(Scene.java:223)
at soot.SourceLocator.getClassSource(SourceLocator.java:64)
at soot.Scene.tryLoadClass(Scene.java:630)
at soot.Scene.loadBasicClasses(Scene.java:1207)
at soot.Scene.loadNecessaryClasses(Scene.java:1286)
at soot.Main.run(Main.java:172)
at soot.Main.main(Main.java:146)
at AndroidInstrument.main(AndroidInstrument.java:81)

I am running this file from the Run Configuration option in eclipse . In the arguments tab , I provided the following line as program arguments : 

-android-jars A:\Softwares\adt-bundle-windows-x86_64-20131030\adt-bundle-windows-x86_64-20131030\sdk\Soot Lib\android.jar -process-dir A:\Android Projects\SimpleMessenger\bin\SimpleMessenger.apk

The "path/to/android-platforms" according to the blog is this android jar file which i took from this link :  https://github.com/Sable/android-platforms/blob/master/android-17/android.jar

Please tell where I might be going wrong . 

Regards
Mangesh

**Comment by HFA22SCM36R** [comment]
Hi,

I was trying to run and execute soot, but was getting this, can anyone please guide me on this.

java -jar sootclasses-trunk-jar-with-dependencies.jar -w -allow-phantom-refs -android-jars /mnt/c/Users/harsh/Desktop/andriod-platforms/ -src-prec apk -process-multiple-dex -process-dir ~ /mnt/c/Users/harsh/Desktop/demo.apk -output-dir /mnt/c/Users/harsh/Desktop/test -output-format d -dump-cfg ALL
Soot started on Thu Oct 20 15:18:15 EDT 2022
java.lang.RuntimeException: no apk file given
        at soot.Scene.defaultAndroidClassPath(Scene.java:646)
        at soot.Scene.defaultClassPath(Scene.java:585)
        at soot.Scene.getSootClassPath(Scene.java:310)
        at soot.SourceLocator.getClassSource(SourceLocator.java:179)
        at soot.Scene.tryLoadClass(Scene.java:967)
        at soot.Scene.loadBasicClasses(Scene.java:1708)
        at soot.Scene.loadNecessaryClasses(Scene.java:1807)
        at soot.Main.run(Main.java:241)
        at soot.Main.main(Main.java:141)


Ouuups... something went wrong! Sorry about that.
Follow these steps to fix the problem:
1.) Are you sure you used the right command line?
    Click here to double-check:
    https://github.com/Sable/soot/wiki/Options-and-JavaDoc

2.) Not sure whether it's a bug? Feel free to discuss
    the issue on the Soot mailing list:
    https://github.com/Sable/soot/wiki/Getting-help

3.) Sure it's a bug? Click this link to report it.
    https://github.com/Sable/soot/issues/new?title=java.lang.RuntimeException+when+...&body=Steps+to+reproduce%3A%0A1.%29+...%0A%0AFiles+used+to+reproduce%3A+%0A...%0A%0ASoot+version%3A+%3Cpre%3Etrunk%3C%2Fpre%3E%0A%0ACommand+line%3A%0A%3Cpre%3E-w+-allow-phantom-refs+-android-jars+%2Fmnt%2Fc%2FUsers%2Fharsh%2FDesktop%2Fandriod-platforms%2F+-src-prec+apk+-process-multiple-dex+-process-dir+%2Fhome%2Flabss+%2Fmnt%2Fc%2FUsers%2Fharsh%2FDesktop%2Fdemo.apk+-output-dir+%2Fmnt%2Fc%2FUsers%2Fharsh%2FDesktop%2Ftest+-output-format+d+-dump-cfg+ALL%3C%2Fpre%3E%0A%0AMax+Memory%3A%0A%3Cpre%3E1783MB%3C%2Fpre%3E%0A%0AStack+trace%3A%0A%3Cpre%3Ejava.lang.RuntimeException%3A+no+apk+file+given%0A%09at+soot.Scene.defaultAndroidClassPath%28Scene.java%3A646%29%0A%09at+soot.Scene.defaultClassPath%28Scene.java%3A585%29%0A%09at+soot.Scene.getSootClassPath%28Scene.java%3A310%29%0A%09at+soot.SourceLocator.getClassSource%28SourceLocator.java%3A179%29%0A%09at+soot.Scene.tryLoadClass%28Scene.java%3A967%29%0A%09at+soot.Scene.loadBasicClasses%28Scene.java%3A1708%29%0A%09at+soot.Scene.loadNecessaryClasses%28Scene.java%3A1807%29%0A%09at+soot.Main.run%28Main.java%3A241%29%0A%09at+soot.Main.main%28Main.java%3A141%29%0A%3C%2Fpre%3E
    Please be as precise as possible when giving us
    information on how to reproduce the problem. Thanks!
