### ISSUE TITLE
Cannot Find the mailing list 

### ISSUE THREAD

**Issue by kartikeyagg** [soot-oss/soot#2092]
Can not find the mailing list mentioned at https://github.com/soot-oss/soot

(http://www.sable.mcgill.ca/mailman/listinfo/soot-list/)

![Screenshot from 2024-08-25 14-47-46](https://github.com/user-attachments/assets/bfc9cfe4-c3f8-4098-a8cf-2171685fad73)

**Comment by StevenArzt** [comment]
I don't think the mailing list exists anymore. I have removed the respective sentence from the README.
