### ISSUE TITLE
SootClass.getJavaStyleName() returns Java class name without package name

### ISSUE THREAD

**Issue by jpstotz** [soot-oss/soot#2120]
`soot.SootClass` has two methods: 

* [getShortJavaStyleName()](https://github.com/soot-oss/soot/blob/21d341fb3e28ef4c3c890ff3154120f873e47ceb/src/main/java/soot/SootClass.java#L932)
* [getJavaStyleName()](https://github.com/soot-oss/soot/blob/21d341fb3e28ef4c3c890ff3154120f873e47ceb/src/main/java/soot/SootClass.java#L918)

My assumption was now that `getJavaStyleName` returns the class name including package name and the `getShortJavaStyleName` just the class name, similar to `getName()`/`getShortName()`.

However to my surprise `getJavaStyleName()` returns by default `shortName` - which is the same as `getShortJavaStyleName()` returns.

Note that both methods do not contain any JavaDoc description (and I assume there are also no uni tests), therefore it is not clear if this is a bug or a misunderstanding.

**Comment by StevenArzt** [comment]
My initial understanding is equal to yours, i.e., ``getJavaStyleName´´ returning the fully-qualified class name including the package.

I don't think many projects use these methods, so feel free to change them and add proper JavaDoc.

**Comment by jpstotz** [comment]
It is used soot-internally in the Dava part, e.g. [DavaUnitPrinter.java](https://github.com/soot-oss/soot/blob/21d341fb3e28ef4c3c890ff3154120f873e47ceb/src/main/java/soot/dava/DavaUnitPrinter.java#L101) - not sure if it expects it to return the short name or the long name in this context.

**Comment by StevenArzt** [comment]
Dava is dead. That's what the D is for. I strongly encourage deleting Dava from Soot at some point.
