### ISSUE TITLE
Dava problems with assignment between new and <init> call

### ISSUE THREAD

**Issue by MarcMil** [soot-oss/soot#322]
Portion of the input jimple code:
        r7 = new java.util.IdentityHashMap;
        $r6 = r7;
        specialinvoke r7.<java.util.IdentityHashMap: void <init>()>();

```
 label1:
    interfaceinvoke $r6.<java.util.Map: java.lang.Object put(java.lang.Object,java.lang.Object)>($r2, $r3);
```

is getting transformed into

```
    IdentityHashMap r7;
    Map $r2;
    $r2 = (Map) a.get($r4);

    if ($r2 == null)
    {
       //Jimple output from above starts at this line
        $r2 = r7; //this assignment should be after the new statement
        r7 = new IdentityHashMap();
        a.put($r4, r7);
    }

    $r2.put($r5, $r3); //$r2 may be still null, although it has a value in the Jimple code above
```

Demo project can be found under 
https://www.dropbox.com/s/rnpt0r71agvjumn/Dava%20Problem%20AssignmentDuringCstr.zip?dl=0

**Comment by pavanupb** [comment]
@MarcMil Please re-open the issue if this is still relevant.
