### ISSUE TITLE
APK patching (incorrect order of local parameter)

### ISSUE THREAD

**Issue by mikhail247** [soot-oss/soot#363]
Here's the Java code executed within JTP phase

Local list_ref_t = Jimple.v().newLocal("list_ref_0", RefType.v("java.util.ArrayList"));
Chain<Local> local_chain = body.getLocals(); 
local_chain.add(list_ref_t);
... // use of list_ref_t

Here is the produced smali file
.method public openFile(Landroid/net/Uri;Ljava/lang/String;)Landroid/os/ParcelFileDescriptor;
    .locals 11
    .param p1, "uri"    # Landroid/net/Uri;
    .param p2, "mode"    # Ljava/lang/String;

```
.local p0, "$r0":Lorg/moca/db/BinaryProvider;, ""
.local p1, "$r1":Landroid/net/Uri;, ""
.local p2, "$r2":Ljava/lang/String;, ""
new-instance p2, Ljava/util/ArrayList;
```

...

Soot should have named p2 as v# (i.e. v<sum number>). Code generated by Soot causes an app to crash because it's not able to pass verification phase.

**Comment by StevenArzt** [comment]
Can you please provide your complete code? With that snippet alone, it's hard to judge what happens there. A minimal example that I can download and run would be best.

**Comment by mikhail247** [comment]
Hi,

I've attached a runnable code snippet and the app that I used for testing.
Dalvik class Verifier throws an exception because of incorrect code
produced by Soot, i.e. Soot adds an extra argument to a method.

thanks,
Mikhail

**Comment by StevenArzt** [comment]
The attachment did not arrive here. Can you please send it to me directly via e-mail? Just use Steven.Arzt@cased.de

**Comment by ericbodden** [comment]
What's the status of this issue?

**Comment by pavanupb** [comment]
@mikhail247 Please re-open the issue if this is still relevant.
