### ISSUE TITLE
soot has any option  can turn off it's debug log?

### ISSUE THREAD

**Issue by WangYeOtw** [soot-oss/soot#438]
soot log is too much ,like this :

Transforming yyyy ...
Transforming xxxx....
.........

I didn't find option to turn off it. any body can help me?

**Comment by johanneslerch** [comment]
Oh, i know your pain. You can remove the output like i did here [1]. 
But i agree, having an option for this would be the cleaner solution that would not require a fork ;-)

[1] https://github.com/johanneslerch/soot/commit/a7f285bde0dffaedf2272e16db8ee6c858e2e2ec

**Comment by StevenArzt** [comment]
We actually do have pull requests for changing Soot's logging: #401 and #407 . Both approaches have advantages and disadvantages. Neither is tested and can easily be integrated - partly, because the pull requests are not up to date. If you want to work on this, feel free to get in touch.

**Comment by WangYeOtw** [comment]
@StevenArzt , if my code integrate  with  #401 or #407, while soot has any update, i can't use soot jars directly download  from nightly build , and i also need to do integrate for every version?  if it is, I hope you can integrate  #401 or #407 in soot, provide option for user to control the log.

**Comment by StevenArzt** [comment]
As I said, these pull requests need work. if you can integrate them into the current development branch and get a stable new version out of it, I am happy to merge that into the Soot development branch. Then you only need to do the work once and support the development of Soot for all the users.

**Comment by jpstotz** [comment]
@StevenArzt You say that these pull requests need work. Could you please go a little more into detail? 

What are the major aspects that need to be addressed by a pull request for introducing slf4j as logging system for Soot for being accepted by the Soot maintainers?

**Comment by ericbodden** [comment]
Hi all.

May I ask what license this framework is under? We will be undergoing an IP screening soon, so that issue will be important.

Cheers
Eric

--
Sent via my mobile

On Oct 20, 2017 16:57, "Jan S." <notifications@github.com> wrote:

@StevenArzt<https://github.com/stevenarzt> You say that these pull requests need work. Could you please go a little more into detail?

What are the major aspects that need to be addressed by a pull request for introducing slf4j as logging system for Soot for being accepted by the Soot maintainers?

**Comment by jpstotz** [comment]
SLF4J the commonly used logging Framenwork uses the [MIT license](https://www.slf4j.org/license.html). AFAIR Jasmin and Heros also use SLF4J. 

At run-time usually an SLF4J implementation like Logback is used. Logback is available under [EPL v1.0 and the LGPL 2.1](https://logback.qos.ch/license.html).

**Comment by ericbodden** [comment]
Ok then that should be fine. Thanks! In the meantime, as a good workaround you can just overwrite the OutputStream G.out by one that does not print anything. That's a quite simple way to disable all logging.

**Comment by jpstotz** [comment]
The current develop branch now uses nearly completely slf4j for printing outputs. Therefore soot debug log can be completely or selectively (per class) disabled using the underlaying logging framework (usually logback).

**Comment by pavanupb** [comment]
@WangYeOtw Please re-open if this is still relevant.
