### ISSUE TITLE
Improve documentation on how to obtain releases

### ISSUE THREAD

**Issue by mernst** [soot-oss/soot#446]
https://github.com/Sable/soot/wiki/Introduction:-Soot-as-a-command-line-tool says:
You can always download the latest release version of Soot from the official Soot download page.

It would be helpful if that linked to the official Soot download page.

https://github.com/Sable/soot/wiki/Running-Soot has the same problem:  it mentions "the Soot download page" but that text isn't a link.  Later that documents mentions http://www.sable.mcgill.ca/soot/soot_download.html, but that URL just redirects to http://sable.github.io/soot/ which doesn't contain the word "download" anywhere.

Eventually I found 
https://www.sable.mcgill.ca/soot/soot_download.html
(note that it's https rather than http).

It would be nice to make it clearer how to download Soot.

**Comment by StevenArzt** [comment]
The download site you found is outdated. The newest nightly builds are available from here: https://ssebuild.cased.de/nightly/soot/. In general, the Soot website at McGill is not maintained anymore, the pages on Github are up-to date.

On https://sable.github.io/soot/, there is a section "How do I obtain the nightly builds" with a the same link I posted above. We should maybe have this link at other places, too.

**Comment by mernst** [comment]
Thanks for your reply, but I don't feel that this issue is really resolved.
Multiple wiki pages at GitHub mention "the official Soot download page" gave no link.  A Google search for the Soot download yielded pages at McGill.  This is frustrating to users and wastes their time.

Some simple action items are:
 * update each of the wiki pages I mentioned to provide a link.
 * get the McGill webpages updated to link to the new official Soot download page.
 * use consistent wording throughout; "official download page" suggests a rather different meaning than "nightly builds".

**Comment by ericbodden** [comment]
Thanks a lot for your input Michael. I agree with your assessment. Let's update the Wiki in the following way:

Where we refer to official releases, link to:
https://github.com/Sable/soot/releases

Where we refer to nightly builds, link to https://ssebuild.cased.de/nightly/soot/

Steven I have already updated the page Michael mentioned.

**Comment by ericbodden** [comment]
By the way, we should probably also make the release-page more informative.

**Comment by akwick** [comment]
The mentioned URL for the nightly build is linked in the above mentioned tutorial and by now outdated. I assume the new URL is https://soot-build.cs.uni-paderborn.de/public/.

**Comment by pavanupb** [comment]
@mernst Please re-open if this is still relevant.

**Comment by mernst** [comment]
Thanks for updating the documentation.
