### ISSUE TITLE
soot.jimple.toolkits.typing.TypeAssigner.replaceNullType(Body) confuses exception handling

### ISSUE THREAD

**Issue by martinschaef** [soot-oss/soot#485]
I'm playing around with transforming exceptions and there are a few cases where I hit the wall because there is a trap, but nothing throws the corresponding exception. For example, in Ant I analyze the procedure org.apache.tools.ant.taskdefs.condition.Socket: boolean eval(), which looks as follows:

``` java
    public boolean eval() throws BuildException {
        if (server == null) {
            throw new BuildException("No server specified in socket "
                                     + "condition");
        }
        if (port == 0) {
            throw new BuildException("No port specified in socket condition");
        }
        log("Checking for listener at " + server + ":" + port,
            Project.MSG_VERBOSE);
        java.net.Socket s = null;
        try {
            s = new java.net.Socket(server, port);
        } catch (IOException e) {
            return false;
        } finally {
          if (s != null) {
            try {
              s.close();
            } catch (IOException ioe) {
              // Intentionally left blank
            }
          }
        }
        return true;
    }
```

Now, replaceNullType starts replacing statements which it thinks are bad and I end up having the following blocks in the Jimple:

```
 label06:
    r20 = new java.lang.NullPointerException;
    specialinvoke r20.<java.lang.NullPointerException: void <init>(java.lang.String)>("This statement would have triggered an Exception: virtualinvoke s#1.<java.net.Socket: void close()>()");
    throw r20;
 label07:
    $r17 := @caughtexception;
catch java.io.IOException from label06 to label07 with label07;
```

As you can see, replaceNullType replaced s.close() by a NullPointerException (which is a bit ambitious) but leaves the trap for IOException in the code which causes my analysis to crash.

**Comment by Alexandre-Bartel** [comment]
Thank you for reporting this. Could you give the command line you are using for Soot to reproduce this issue as well as a test case in form of a .java or .class?

**Comment by martinschaef** [comment]
We are using class files. Unfortunately, I can't give you command line args because we are using soot as a library so we are not calling the actual main. 
We compile ant first, then run soot on the folder ant/build/classes/ with the following flags set:

sootOpt.set_soot_classpath(cp);
sootOpt.set_src_prec(soot.options.Options.src_prec_class);
List<String> processDirs = new LinkedList<String>();
processDirs.add("path/to/ant/build/classes/");
sootOpt.set_process_dir(processDirs);
sootOpt.set_keep_line_number(true);
sootOpt.set_prepend_classpath(true); // -pp
sootOpt.set_output_format(soot.options.Options.output_format_none);
sootOpt.set_allow_phantom_refs(true);

**Comment by pavanupb** [comment]
@martinschaef Please re-open the issue if this is still relevant.
