### ISSUE TITLE
Weird renaming happened during analysis

### ISSUE THREAD

**Issue by majestyhao** [soot-oss/soot#500]
Hi,

I am implementing a simple intra-procedure taint analysis using Soot and I wrote a small program to test my analysis. Here is the test program:
1.  private void testTaintForwardVar() {
2.      int x = source();
3.      int y = x, k = 3;
4.      x = k;
5.      sink(y);
6.  }

Variable "x" should not be considered as tainted since it was re-assigned by variable k. However, the program under Jimple becomes: 

i0 = specialinvoke r0.<playSoot.MyClass: int source()>()
i1 = i0
b2 = 3
b3 = b2

"x" automatically changed from i0 to b3, which made my "kills" not effect any more.

How to fix such problem by linking b2 and i0?

Thanks.

**Comment by ericbodden** [comment]
Hello.

> Variable "x" should not be considered as tainted since it was re-assigned by variable k. However, the program under Jimple becomes:
> 
> i0 = specialinvoke r0.()
> i1 = i0
> b2 = 3
> b3 = b2
> 
> "x" automatically changed from i0 to b3, which makes my "kills" not effect any more.

Can you show us the complete Jimple? Even though the “kill” does not kill the variable you thought it would I am pretty sure that no taint actually reaches the sink, does it?

Cheers,
Eric

**Comment by majestyhao** [comment]
Java code:
	private void testTaintForwardVar() {
		int x = source();
		int y = x, k = 3;
		x = k;
		sink(y);
		System.out.print("\n");
	}
	
	private int source() {
		// ultimate answer of the universe 
		return 42;
	}
	
	private void sink(int x) {
		System.out.print(x);
	}

The analysis result I got from Jimple:
found Source! i0 = specialinvoke r0.<playSoot.MyClass: int source()>()---------------------------------------
r0 := @this: playSoot.MyClass
Taint in: {}
Taint out: {}
---------------------------------------
---------------------------------------
i0 = specialinvoke r0.<playSoot.MyClass: int source()>()
Taint in: {}
Taint out: {i0: int}
---------------------------------------
---------------------------------------
i1 = i0
Taint in: {i0: int}
Taint out: {i0: int, i1: int}
---------------------------------------
---------------------------------------
b2 = 3
Taint in: {i0: int, i1: int}
Taint out: {i0: int, i1: int}
---------------------------------------
---------------------------------------
b3 = b2
Taint in: {i0: int, i1: int}
Taint out: {i0: int, i1: int}
---------------------------------------
---------------------------------------
specialinvoke r0.<playSoot.MyClass: void sink(int)>(i1)
found a sink!
Taint in: {i0: int, i1: int}
Taint out: {i0: int, i1: int}
---------------------------------------
---------------------------------------
$r1 = <java.lang.System: java.io.PrintStream out>
Taint in: {i0: int, i1: int}
Taint out: {i0: int, i1: int}
---------------------------------------
---------------------------------------
virtualinvoke $r1.<java.io.PrintStream: void print(java.lang.String)>("\n")
Taint in: {i0: int, i1: int}
Taint out: {i0: int, i1: int}
---------------------------------------
---------------------------------------
return
Taint in: {i0: int, i1: int}
Taint out: {i0: int, i1: int}

**Comment by StevenArzt** [comment]
For the Java code you posted, I would expect a leak to be reported.

```
private void testTaintForwardVar() {
 int x = source();
 int y = x, k = 3;
 x = k;
 sink(y);
 System.out.print("\n");
 }
```

The source value gets assigned to "x", then copied to "y". The value of "y" is never overwritten and ends up in the sink.

**Comment by pavanupb** [comment]
@majestyhao Please re-open if this is still relevant.
