### ISSUE TITLE
Incorrect optimization of nested try-catch

### ISSUE THREAD

**Issue by nave-mvn** [soot-oss/soot#507]
I have come across an instance of incorrect optimization by the soot compiler in the case of a nested try-catch
Tester.java is the original source file. To reproduce this, please follow the below steps.
1. Compile Tester.java with javac to produce a Tester.class file
2. Feed the Tester.class file from step 1 as input to the Soot compiler
3. Decompile the resulting Tester.class file from step 2 to produce the decompiled source file

Tester.java.decompiled is an example file produced from step 3.
As you can see, the check isFile() is outside the outer try-catch in the Tester.java.decompiled file whereas it is inside the outer try-catch in the original source file
 Please also note that isFile() does indeed throw a SecurityException. So, in the soot compiled file, this exception will not be caught

**Comment by Nave-Neel** [comment]
Sorry, attaching the sources
[tester.zip](https://github.com/Sable/soot/files/55987/tester.zip)

**Comment by pavanupb** [comment]
@nave-mvn Please re-open the issue if this is still relevant.
