### ISSUE TITLE
java.util.ConcurrentModificationException: Scene changed for Hierarchy!

### ISSUE THREAD

**Issue by vitaliiavdiienko** [soot-oss/soot#512]
Dear Soot developers,

i am trying to leverage Hierarchy from Soot and in most of cases I receive a strange exception while using it:

`Exception in thread "main" java.util.ConcurrentModificationException: Scene changed for Hierarchy!
    at soot.Hierarchy.checkState(Hierarchy.java:149)
    at soot.Hierarchy.getSubclassesOf(Hierarchy.java:174)
    at soot.Hierarchy.isClassSuperclassOf(Hierarchy.java:455)`

My code is the following:
        `Options.v().set_src_prec(Options.src_prec_apk);
        Options.v().set_output_format(Options.output_format_jimple);    
        Options.v().set_exclude(exclude);
        Options.v().set_force_android_jar(androidJar);
        Options.v().set_android_jars(androidJar);
        Options.v().set_allow_phantom_refs(true);
        Options.v().set_process_dir(Collections.singletonList(apkName));
        Options.v().set_soot_classpath(binOfClasses + File.pathSeparator + androidJar);
               Scene.v().loadNecessaryClasses();
               PackManager.v().runPacks();`

```
     final Iterator<SootClass> classes = Scene.v().getApplicationClasses().iterator();
        while(classes.hasNext()){
            SootClass c = classes.next();
            if(Scene.v().getActiveHierarchy().isClassSuperclassOf(
                                           Scene.v().getSootClass("android.app.Service"), c)){
                System.out.println(c);
            }
        }`
```

Can you tell me what I am doing wrong?

P.S. You can test it on `DroidBench/apk/GeneralJava/StaticInitialization1.apk`

Thank you in advance.

Best Regards,
Vitalii

**Comment by umang78** [comment]
In place of Iterator use SnapShot Iterator
**Example:**  
for(Iterator<Unit> iter = methodUnits.snapshotIterator(); iter.hasNext();) 
{
  final Unit u = iter.next();
}

**Comment by pavanupb** [comment]
@vitaliiavdiienko Please re-open the issue if this is still relevant.
