### ISSUE TITLE
java.lang.RuntimeException when outputting Dava (apk)

### ISSUE THREAD

**Issue by elephantom** [soot-oss/soot#513]
Steps to reproduce:
1.) I am using AndroidInstrument.java to run Soot an APKs. This apk, along with many others, fails with an RuntimeException error with the message "Could not verify approximated Synchronized body!". (I am happy to post a list of apks with this issue if that would be helpful). The only change I've made to AndroidInstrument is changing the output format to Dava.

Files used to reproduce: 
at.tomtasche.reader_34.apk, available at https://f-droid.org/repo/at.tomtasche.reader_34.apk

Soot version: <pre>trunk</pre>

Command line:

<pre>-android-jars /path/to/android-sdk-linux/platforms -allow-phantom-refs -p db.transformations enabled:true -process-dir apks/at.tomtasche.reader_34.apk</pre>

Max Memory:

<pre>1746MB</pre>

Stack trace:
<pre>java.lang.RuntimeException: Could not verify approximated Synchronized body!
Method:
# &#60;at.andiwand.commons.lwxml.visitor.LWXMLHost: void fireEvent(at.andiwand.commons.lwxml.LWXMLEvent,at.andiwand.commons.lwxml.reader.LWXMLReader)&#62;Body:

[this := this: at.andiwand.commons.lwxml.visitor.LWXMLHost, $r1 := @parameter0: at.andiwand.commons.lwxml.LWXMLEvent, $r2 := @parameter1: at.andiwand.commons.lwxml.reader.LWXMLReader, entermonitor this, $r3 = null, $r4 = null, if $r1.&#60;at.andiwand.commons.lwxml.LWXMLEvent: boolean hasValue()&#62;() == false goto (branch), goto [?= $r3 = $r2.&#60;at.andiwand.commons.lwxml.reader.LWXMLReader: java.lang.String readValue()&#62;()], goto [?= (branch)], $r3 = $r2.&#60;at.andiwand.commons.lwxml.reader.LWXMLReader: java.lang.String readValue()&#62;(), if $r1.&#60;at.andiwand.commons.lwxml.LWXMLEvent: boolean hasFollowingValue()&#62;() == false goto (branch), goto [?= $r4 = $r2.&#60;at.andiwand.commons.lwxml.reader.LWXMLReader: java.lang.String readFollowingValue()&#62;()], goto [?= (branch)], $r4 = $r2.&#60;at.andiwand.commons.lwxml.reader.LWXMLReader: java.lang.String readFollowingValue()&#62;(), lookupswitch(staticinvoke &#60;at.andiwand.commons.lwxml.visitor.LWXMLHost: int[] $SWITCH_TABLE$at$andiwand$commons$lwxml$LWXMLEvent()&#62;()[$r1.&#60;at.andiwand.commons.lwxml.LWXMLEvent: int ordinal()&#62;()]) {     case 3: goto goto [?= this.&#60;at.andiwand.commons.lwxml.visitor.LWXMLHost: void fireVisitProcessingInstruction(java.lang.String,java.lang.String)&#62;($r3, $r4)];     case 4: goto goto [?= throw new java.lang.IllegalStateException(&#34;unsupported event&#34;)];     case 5: goto goto [?= this.&#60;at.andiwand.commons.lwxml.visitor.LWXMLHost: void fireVisitComment(java.lang.String)&#62;($r3)];     case 6: goto goto [?= this.&#60;at.andiwand.commons.lwxml.visitor.LWXMLHost: void fireVisitCDATA(java.lang.String)&#62;($r3)];     case 7: goto goto [?= this.&#60;at.andiwand.commons.lwxml.visitor.LWXMLHost: void fireVisitCharacters(java.lang.String)&#62;($r3)];     case 8: goto goto [?= this.&#60;at.andiwand.commons.lwxml.visitor.LWXMLHost: void fireVisitStartElement(java.lang.String)&#62;($r3)];     case 9: goto goto [?= throw new java.lang.IllegalStateException(&#34;unsupported event&#34;)];     case 10: goto goto [?= this.&#60;at.andiwand.commons.lwxml.visitor.LWXMLHost: void fireVisitEndElement(java.lang.String)&#62;($r3)];     case 11: goto goto [?= this.&#60;at.andiwand.commons.lwxml.visitor.LWXMLHost: void fireVisitAttribute(java.lang.String,java.lang.String)&#62;($r3, $r4)];     case 12: goto goto [?= throw new java.lang.IllegalStateException(&#34;unsupported event&#34;)];     case 13: goto goto [?= this.&#60;at.andiwand.commons.lwxml.visitor.LWXMLHost: void fireVisitEndAttributeList()&#62;()];     default: goto goto [?= throw new java.lang.IllegalStateException(&#34;unsupported event&#34;)]; }, goto [?= throw new java.lang.IllegalStateException(&#34;unsupported event&#34;)], goto [?= this.&#60;at.andiwand.commons.lwxml.visitor.LWXMLHost: void fireVisitEndAttributeList()&#62;()], goto [?= throw new java.lang.IllegalStateException(&#34;unsupported event&#34;)], goto [?= this.&#60;at.andiwand.commons.lwxml.visitor.LWXMLHost: void fireVisitAttribute(java.lang.String,java.lang.String)&#62;($r3, $r4)], goto [?= this.&#60;at.andiwand.commons.lwxml.visitor.LWXMLHost: void fireVisitEndElement(java.lang.String)&#62;($r3)], goto [?= throw new java.lang.IllegalStateException(&#34;unsupported event&#34;)], goto [?= this.&#60;at.andiwand.commons.lwxml.visitor.LWXMLHost: void fireVisitStartElement(java.lang.String)&#62;($r3)], goto [?= this.&#60;at.andiwand.commons.lwxml.visitor.LWXMLHost: void fireVisitCharacters(java.lang.String)&#62;($r3)], goto [?= this.&#60;at.andiwand.commons.lwxml.visitor.LWXMLHost: void fireVisitCDATA(java.lang.String)&#62;($r3)], goto [?= this.&#60;at.andiwand.commons.lwxml.visitor.LWXMLHost: void fireVisitComment(java.lang.String)&#62;

**Comment by pavanupb** [comment]
@elephantom Please re-open the issue if this is still relevant.
