### ISSUE TITLE
Wrong declaring class for invoke Unit in java.util.AbstractSet

### ISSUE THREAD

**Issue by akamath32** [soot-oss/soot#522]
Hi,
The function `boolean equals(java.lang.Object)` in `java.util.AbstractSet` has a virtual invoke to the function `containsAll` defined in `java.util.AbstractCollection`. 

However while printing the Jimple code using Soot of `java.util.AbstractSet`, the virtual invoke instruction shows the declaring class of `containsAll` to be `java.util.AbstractSet` as follows:

**$z1 = virtualinvoke r0.<java.util.AbstractSet: boolean containsAll(java.util.Collection)>(r2);**

I have attached a small Java code which prints the Jimple units of `java.util.AbstractSet` and the bytecode printed using `javap` as proof of this issue.

Thank You
[AbstractSet.txt](https://github.com/Sable/soot/files/77785/AbstractSet.txt)

[TestCase.txt](https://github.com/Sable/soot/files/77789/TestCase.txt)

**Comment by pavanupb** [comment]
@akamath32 Please re-open the issue if this is still relevant.
