### ISSUE TITLE
soot producing incorrect goto instructions when the target offset is zero

### ISSUE THREAD

**Issue by madberries** [soot-oss/soot#532]
Something as simple as the following method will result in unverifiable dalvik bytecode...

public void run() { int x = 0; while (true) { ++x; } }

After deadcode elimination on the unused local, this will result in a single goto instruction with a zero offset.  However, according to https://source.android.com/devices/tech/dalvik/dalvik-bytecode.html the goto and goto-16 instruction cannot have an offset of zero.  Under this circumstance, these goto instructions need to be replaced with a goto-32.

**Comment by pavanupb** [comment]
@madberries Please re-open the issue if this is still relevant.
