### ISSUE TITLE
Extra Traps added in Jimple code

### ISSUE THREAD

**Issue by nave-mvn** [soot-oss/soot#540]
Hello,

I am doing some instrumentation with the Jython library, specifically with the PythonPartialParser class when I ran into an issue.

The jimple generated single_input() method contains 10 different traps (5 for RecognitionException, 5 for Throwable) when in the original method, there is no traps present. There is no code that is executed inside of these new traps, the exception is just thrown back up. The original method does have a "throws RecognitionException definition" present but it is not clear why this could lead to new traps being generated in the jimple. 

I have attached the class file for the PythonPartialParser class and the resulting jimple.
[Extra_Traps.zip](https://github.com/Sable/soot/files/138846/Extra_Traps.zip)

**Comment by pavanupb** [comment]
@nave-mvn Please re-open if this is still relevant.
