### ISSUE TITLE
Error when converting .jimple files to .class files

### ISSUE THREAD

**Issue by xwangsd** [soot-oss/soot#544]
Hi,

I was converting .jimple files to .class files according to the instructions here:
https://github.com/Sable/soot/wiki/Running-Soot
"You can instruct Soot to convert .java or .class files to .jimple files or the other way around. You can even generate .jimple file from .java, and modify the .jimple with a normal text editor and then convert your .jimple file to .class, virtually hand-optimizing your program. So it means you can simplify your task by Soot easily."

However, I encountered some errors during the conversion. 
In particular, the problem is: sometimes I can successfully convert .jimples files to .class files, but most of time I cannot. 

The message I got when it succeeded was the following:

<pre>
Soot started on Sat Feb 27 14:31:19 CST 2016
Warning: java.lang.invoke.LambdaMetafactory is a phantom class!
Transforming Transforming A... 
B... 
Writing to sootOutput/B.jimple
Writing to sootOutput/A.jimple
Soot finished on Sat Feb 27 14:31:20 CST 2016
Soot has run for 0 min. 0 sec.
Soot started on Sat Feb 27 14:31:20 CST 2016
Warning: java.lang.invoke.LambdaMetafactory is a phantom class!
Transforming Transforming B... 
A... 
Writing to build/B.class
Writing to build/A.class
Soot finished on Sat Feb 27 14:31:21 CST 2016
Soot has run for 0 min. 1 sec.
</pre>

The ERROR message I got when it fails is the following:

<pre>
Soot started on Sat Feb 27 14:31:16 CST 2016
Warning: java.lang.invoke.LambdaMetafactory is a phantom class!
Transforming B... 
Transforming A... 
Writing to sootOutput/B.jimple
Writing to sootOutput/A.jimple
Soot finished on Sat Feb 27 14:30:23 CST 2016
Soot has run for 0 min. 0 sec.
Soot started on Sat Feb 27 14:30:23 CST 2016
Warning: java.lang.invoke.LambdaMetafactory is a phantom class!
[Thread-3] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: null
java.lang.NullPointerException
    at soot.toolkits.graph.UnitGraph.<init>(UnitGraph.java:76)
    at soot.toolkits.graph.ExceptionalUnitGraph.<init>(ExceptionalUnitGraph.java:158)
    at soot.jimple.toolkits.scalar.UnreachableCodeEliminator.internalTransform(UnreachableCodeEliminator.java:79)
    at soot.BodyTransformer.transform(BodyTransformer.java:51)
    at soot.Transform.apply(Transform.java:105)
    at soot.JimpleBodyPack.applyPhaseOptions(JimpleBodyPack.java:61)
    at soot.JimpleBodyPack.internalApply(JimpleBodyPack.java:95)
    at soot.Pack.apply(Pack.java:125)
    at soot.jimple.JimpleMethodSource.getBody(JimpleMethodSource.java:49)
    at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
    at soot.SootMethod.retrieveActiveBody(SootMethod.java:322)
    at soot.PackManager$3.run(PackManager.java:1222)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Exception in thread "Thread-3" java.lang.NullPointerException
    at soot.toolkits.graph.UnitGraph.<init>(UnitGraph.java:76)
    at soot.toolkits.graph.ExceptionalUnitGraph.<init>(ExceptionalUnitGraph.java:158)
    at soot.jimple.toolkits.scalar.UnreachableCodeEliminator.internalTransform(UnreachableCodeEliminator.java:79)
    at soot.BodyTransformer.transform(BodyTransformer.java:51)
    at soot.Transform.apply(Transform.java:105)
    at soot.JimpleBodyPack.applyPhaseOptions(JimpleBodyPack.java:61)
    at soot.JimpleBodyPack.internalApply(JimpleBodyPack.java:95)
    at soot.Pack.apply(Pack.java:125)
    at soot.jimple.JimpleMethodSource.getBody(JimpleMethodSource.java:49)
    at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
    at soot.SootMethod.retrieveActiveBody(SootMethod.java:322)
    at soot.PackManager$3.run(PackManager.java:1222)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
    at soot.toolkits.graph.UnitGraph.<init>(UnitGraph.java:76)
    at soot.toolkits.graph.ExceptionalUnitGraph.<init>(ExceptionalUnitGraph.java:158)
    at soot.jimple.toolkits.scalar.UnreachableCodeEliminator.internalTransform(UnreachableCodeEliminator.java:79)
    at soot.BodyTransformer.transform(BodyTransformer.java:51)
    at soot.Transform.apply(Transform.java:105)
    at soot.JimpleBodyPack.applyPhaseOptions(JimpleBodyPack.java:61)
    at soot.JimpleBodyPack.internalApply(JimpleBodyPack.java:95)
    at soot.Pack.apply(Pack.java:125)
    at soot.jimple.JimpleMethodSource.getBody(JimpleMethodSource.java:49)
    at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
    at soot.SootMethod.retrieveActiveBody(SootMethod.java:322)
    at soot.PackManager$3.run(PackManager.java:1222)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

Ouuups... something went wrong! Sorry about that.
Follow these steps to fix the problem:
1.) Are you sure you used the right command line?
    Click here to double-check:
    https://ssebuild.cased.de/nightly/soot/doc/soot_options.htm

2.) Not sure whether it's a bug? Feel free to discuss
    the issue on the Soot mailing list:
    https://github.com/Sable/soot/wiki/Getting-help

3.) Sure it's a bug? Click this link to report it.
    https://github.com/Sable/soot/issues/new?title=java.lang.NullPointerException+when+...&body=Steps+to+reproduce%3A%0A1.%29+...%0A%0AFiles+used+to+reproduce%3A+%0A...%0A%0ASoot+version%3A+%3Cpre%3Etrunk%3C%2Fpre%3E%0A%0ACommand+line%3A%0A%3Cpre%3E-f+class+-cp+sootOutput%2F+-pp+-allow-phantom-refs+-d+build+-process-dir+sootOutput%3C%2Fpre%3E%0A%0AMax+Memory%3A%0A%3Cpre%3E14306MB%3C%2Fpre%3E%0A%0AStack+trace%3A%0A%3Cpre%3Ejava.lang.NullPointerException%0A%09at+soot.toolkits.graph.UnitGraph.%26%2360%3Binit%26%2362%3B%28UnitGraph.java%3A76%29%0A%09at+soot.toolkits.graph.ExceptionalUnitGraph.%26%2360%3Binit%26%2362%3B%28ExceptionalUnitGraph.java%3A158%29%0A%09at+soot.jimple.toolkits.scalar.UnreachableCodeEliminator.internalTransform%28UnreachableCodeEliminator.java%3A79%29%0A%09at+soot.BodyTransformer.transform%28BodyTransformer.java%3A51%29%0A%09at+soot.Transform.apply%28Transform.java%3A105%29%0A%09at+soot.JimpleBodyPack.applyPhaseOptions%28JimpleBodyPack.java%3A61%29%0A%09at+soot.JimpleBodyPack.internalApply%28JimpleBodyPack.java%3A95%29%0A%09at+soot.Pack.apply%28Pack.java%3A125%29%0A%09at+soot.jimple.JimpleMethodSource.getBody%28JimpleMethodSource.java%3A49%29%0A%09at+soot.SootMethod.getBodyFromMethodSource%28SootMethod.java%3A91%29%0A%09at+soot.SootMethod.retrieveActiveBody%28SootMethod.java%3A322%29%0A%09at+soot.PackManager%243.run%28PackManager.java%3A1222%29%0A%09at+java.util.concurrent.ThreadPoolExecutor.runWorker%28ThreadPoolExecutor.java%3A1145%29%0A%09at+java.util.concurrent.ThreadPoolExecutor%24Worker.run%28ThreadPoolExecutor.java%3A615%29%0A%09at+java.lang.Thread.run%28Thread.java%3A745%29%0A%3C%2Fpre%3E
    Please be as precise as possible when giving us
    information on how to reproduce the problem. Thanks!
</pre>

Soot version: 

<pre>trunk</pre>

Files used to reproduce:

<pre> A.java, B.java </pre> where classes A and B are defined as the following: 
<pre>
A.java
public class A {
public static void main(String[] args) { System.out.println("A"); }
}
B.java
public class B {
public static void main(String[] args) { System.out.println("B"); }
}
</pre>

Script to reproduce (run.sh): 

<pre>
#!/bin/bash
mkdir classes 
javac *.java -d classes
rm -r sootOutput
java -cp lib/soot-trunk.jar soot.Main -f jimple -cp classes -pp -allow-phantom-refs -process-dir classes
java -cp lib/soot-trunk.jar soot.Main -f class -cp sootOutput/ -pp -allow-phantom-refs -d build -process-dir sootOutput
</pre>

Steps to reproduce:

<pre>
1.) in the current directory, you have lib/soot-trunk.jar, run.sh, A.java, B.java
2.) sh run.sh
</pre>

It seems this is some concurrent issue. If I had only one class (jimple) file to process, as far as I tested, there was no problem, however, once I had more than one, most of the time the error appeared. This is very annoying. It would be great if you can help me look into this problem. Thanks.

**Comment by XiaZhang0414** [comment]
Have you solve this problem? I got the same problem but I still not know how to deal with it.

**Comment by xwangsd** [comment]
The best solution I found was to do the instrumentation using soot APIs,
instead of directly manipulating.
I guess directly manipulating the jimple files might probably break the
structures.

Best,

On Thu, Mar 10, 2016 at 10:51 AM, XiaZhang0414 <notifications@github.com>
wrote:

> Have you solve this problem? I got the same problem but I still not know
> how to deal with it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Sable/soot/issues/544#issuecomment-194949035>.
>



-- 
------------------------------------------------------
>> Regards
>> Xinyu Wang
>> Computer Science
>> University of Texas at Austin

**Comment by XiaZhang0414** [comment]
I tried the code. It works. Thank you very much~

**Comment by ZhengqiaoLi** [comment]
@xwangsd 
Hi,I also met the question.But I didn't understand how to deal with it.Can you explain in detail?please.

**Comment by xwangsd** [comment]
I did this a long time ago. 
I didn't figure out the best way to do this. 
The conclusion I made was: 
1). Directly manipulating the jimple files might not always work.
2). Using the APIs soot provided usually works better and it's also quite convenient.

**Comment by ZhengqiaoLi** [comment]
@XiaZhang0414 
Hi,Can you explain in detail?I  used the APIs soot provided,but the question still present.
code snippet:
`Options.v().set_src_prec(Options.src_prec_jimple);
Options.v().set_output_format(Options.output_format_jimple);
Options.v().set_soot_classpath(....);
`
And eclipse program arguments:
`-w
-process-dir G:\\eclipse_Java\\apk转换Jimple\\sootOutput
-android-jars G:\\Soot\\sdk\\platforms\\`
can you help me?

**Comment by XiaZhang0414** [comment]
You can try the following code. What it does is to inject some code after the onClick function.  It always through above exception when I use the current version of soot in command line. So I used an old version of soot.

import java.io.File;
import java.util.Collections;
import java.util.Iterator;
import java.util.Map;
import soot.Body;
import soot.BodyTransformer;
import soot.Local;
import soot.PackManager;
import soot.PatchingChain;
import soot.RefType;
import soot.Scene;
import soot.SootClass;
import soot.SootMethod;
import soot.Transform;
import soot.Unit;
import soot.jimple.Jimple;
import soot.jimple.StringConstant;
import soot.options.Options;

public class InstrumentExample {
	public static void main(String[] args) {
		//prefer Android APK files// -src-prec apk
		Options.v().set_src_prec(Options.src_prec_apk);
		
		String apkFileLocation = "/home/xia/apk_package/FlowDroid/com.tatkovlab.sdcardcleaner.apk";
//		String apkFileLocation = "/home/xia/workspace/AndroidInstrument/sootInput";
		String androidJar = "/opt/android-sdk-linux/platforms";		
		
		Options.v().set_process_dir(Collections.singletonList(apkFileLocation));
		Options.v().set_android_jars(androidJar);
//		Options.v().set_output_dir(args[2]);
		Options.v().set_allow_phantom_refs(true);
		
		//output as APK, too//-f J
		Options.v().set_output_format(Options.output_format_dex);
		
        // resolve the PrintStream and System soot-classes
		Scene.v().addBasicClass("java.io.PrintStream",SootClass.SIGNATURES);
        Scene.v().addBasicClass("java.lang.System",SootClass.SIGNATURES);
        Scene.v().addBasicClass("android.util.Log",SootClass.SIGNATURES);
        
        
        PackManager.v().getPack("jtp").add(new Transform("jtp.myInstrumenter", new BodyTransformer() {

			@Override
			protected void internalTransform(final Body b, String phaseName, @SuppressWarnings("rawtypes") Map options) {
				final PatchingChain<Unit> units = b.getUnits();
				
				SootMethod m = b.getMethod();
				if (m.getName().contains("onClick")){
				
				//important to use snapshotIterator here
				Iterator<Unit> iter = units.snapshotIterator(); 
				if(iter.hasNext()){
				Unit u = iter.next();
				while(iter.hasNext()){
					 u = iter.next();
				}
					
								//System.out.println(stmt.toString());
								//Local tmpRef = addTmpRef(b);
								
								Local tagString = addTagString(b);
								
								  // insert "tmpRef = java.lang.System.out;" 
						        
						        units.insertBefore(Jimple.v().newAssignStmt(tagString, 
					                      StringConstant.v("onClick")), u);
						        
						        Local tmpString = addTmpString(b);
					        // insert "tmpLong = 'HELLO';" 
					        units.insertBefore(Jimple.v().newAssignStmt(tmpString, 
					                      StringConstant.v("Onclick"+m.getDeclaringClass())), u);
					        
					        // insert "tmpRef.println(tmpString);" 
					        SootMethod logCall = Scene.v().getSootClass("android.util.Log").getMethod("int d(java.lang.String,java.lang.String)");                    
					        units.insertBefore(Jimple.v().newInvokeStmt(
					        		 Jimple.v().newStaticInvokeExpr(logCall.makeRef(),tagString, tmpString)), u);
					        
						        //Jimple.v().newIfStmt(condition, target)
						        //check that we did not mess up the Jimple
						        b.validate();
							}
						}
			}		
		}));
        String class_path = androidJar+File.pathSeparator+System.getProperty("java.class.path")+File.pathSeparator
		        +System.getProperty("java.home")+File.separator+ "lib"+File.separator+"rt.jar";//+apkFileLocation+File.pathSeparator
		
        
		String dummyclasspath = Scene.v().defaultClassPath() + class_path;
		System.out.println(dummyclasspath);
		Options.v().set_soot_classpath(dummyclasspath);
		 Scene.v().loadNecessaryClasses();
		//soot.Main.main(args);
        PackManager.v().runPacks();
        PackManager.v().writeOutput();
	}

    private static Local addTmpRef(Body body)
    {
        Local tmpRef = Jimple.v().newLocal("tmpRef", RefType.v("java.io.PrintStream"));
        body.getLocals().add(tmpRef);
        return tmpRef;
    }
    
    private static Local addTmpString(Body body)
    {
        Local tmpString = Jimple.v().newLocal("tmpString", RefType.v("java.lang.String")); 
        body.getLocals().add(tmpString);
        return tmpString;
    }
    
    private static Local addTagString(Body body)
    {
        Local tmpString = Jimple.v().newLocal("tagString", RefType.v("java.lang.String")); 
        body.getLocals().add(tmpString);
        return tmpString;
    }
}

**Comment by ZhengqiaoLi** [comment]
I mainly met the exception when converting jimple to java or jimple.
As the above code, I didn't met the question when using soot-trunk.

**Comment by pavanupb** [comment]
@xwangsd Please re-open if this is still relevant.
