### ISSUE TITLE
RuntimeException "Attempting to push a non-constant cp entry"

### ISSUE THREAD

**Issue by xclerc** [soot-oss/soot#560]
While using the RoboVM compiler (through the jfxmobile plugin),
I stumbled upon the following exception:

```
java.lang.RuntimeException: Attempting to push a non-constant cp entryclass soot.coffi.CONSTANT_MethodHandle_info
  at soot.coffi.CFG.processCPEntry(CFG.java:2730)
  at soot.coffi.CFG.processFlow(CFG.java:1660)
  ...
```

After some investigation, it appears that the problem is raised by
a `ldc` instruction whose index points to a method handle.

According to the specification (version 7), it seems that it is actually
a correct parameter for a `ldc` instruction:
https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-6.html#jvms-6.5.ldc

note: the version of Soot used by the RoboVM compiler being different
from this the code base, the exception is raised at
https://github.com/Sable/soot/blob/develop/src/soot/coffi/CFG.java#L2581

**Comment by StevenArzt** [comment]
Is there a specific reason to use the coffi frontend for Soot? Coffi is outdated and has been replaced with our new ASM-based frontend. The Coffi frontend is known to not support newer bytecode constructs which is one of the reasons why we chose to replace it.

**Comment by xclerc** [comment]
As a simple user of RoboVM, I cannot comment their decision to use Coffi.

However, I understand that I should report a bug to RoboVM rather than to Soot.

Thanks for the information!

**Comment by xclerc** [comment]
For the record, I have posted a question on the RoboVM mailing list:
    https://groups.google.com/forum/#!topic/robovm/wpCMcvG2oy0

**Comment by pavanupb** [comment]
@xclerc Please re-open if this is still relevant.
