### ISSUE TITLE
Soot produces old bytecode version

### ISSUE THREAD

**Issue by martinschaef** [soot-oss/soot#563]
I'm trying to use Soot to instrument class files for use with [Daikon](https://plse.cs.washington.edu/daikon/download/doc/daikon/Front-ends-_0028instrumentation_0029.html#Chicory). Unfortunately, the bytecode produced by Soot crashes Daikon - even if I don't apply any transformation.
The Daikon folks said that the class files produced by soot follow the 1.2 bytecode standard which they do not support anymore.
Is there a way to get more modern bytecode from Soot?

**Comment by StevenArzt** [comment]
Have you tried starting Soot with the -asm-backend option? The switches the Java bytecode backend from Jasmin to ASM which is much newer. We haven't made ASM the new backend standard yet, but it should be fairly stable.

**Comment by martinschaef** [comment]
Ah ... that likes like java7/8 bytecode. Daikon still fails to verify the class file, but that might be Daikons fault. I'll follow up with the Daikon ppl and close the issue then.
Thanks.

**Comment by martinschaef** [comment]
The ASM backend works 'better' but still does some optimizations that don't work with Daikon. More important: it drops the LocalVariableTable which will cause problems.
Any way to keep this information in soot?

**Comment by StevenArzt** [comment]
Are you using the newest version of Soot? We are explicitly writing out local variable information (a relatively new feature, though) to have a proper mapping between VM variables and Jimple locals in the debugger when debugging Java code created by Soot.

**Comment by martinschaef** [comment]
I took the nightly build from March 29. No Local var information in there ... I use the following options:

```java
		soot.options.Options sootOpt = soot.options.Options.v();
		sootOpt.set_keep_line_number(true);
		sootOpt.set_java_version(soot.options.Options.java_version_1_7);
		sootOpt.set_soot_classpath(classPath);
		sootOpt.set_src_prec(soot.options.Options.src_prec_class);
		sootOpt.set_output_format(soot.options.Options.output_format_class);
		sootOpt.set_asm_backend(true);		
		sootOpt.set_keep_offset(true);
```

The resulting class file is java 1.7, so it has been generated with asm (or at least not with jasmin). It has line numbers but no local vars. Am I missing an option?

**Comment by billy-mosse** [comment]
@martinschaef , I have practically the same problem. Could you solve it?

**Comment by martinschaef** [comment]
No. I ended up going with ASM (but haven't worked on this in a long time). Here is my [code](https://github.com/jayhorn/DynSlicer/blob/master/instrumenter/src/main/java/bc_instrumenter/Main.java) if it's of any help - this was not written to be shared and is not polished, so don't judge me ;)

**Comment by billy-mosse** [comment]
Thanks! Let me know if I'm understanding this correctly...(I'm a mathematician and I don't lots of experience in this stuff)

**Comment by martinschaef** [comment]
Yes ... you could argue that Soot is an abstraction layer over ASM to make your live easier. So, everything you can do in Soot, you can also do in ASM; it might just be a lot more work to implement.
The instrumentation that I needed was simple, so it could easily be done without Soot. Feel free to shot me an email if you have more questions.

**Comment by ericbodden** [comment]
Hi all.

Do you know about the option to keep original names? I don't think it's enabled in your case.

Eric

Yes ... you could argue that Soot is an abstraction layer over ASM to make your live easier. So, everything you can do in Soot, you can also do in ASM; it might just be a lot more work to implement.
The instrumentation that I needed was simple, so it could easily be done without Soot. Feel free to shot me an email if you have more questions.

-

**Comment by c001man** [comment]
Hi @ericbodden .

The LocalVariableTable that appears when I use the following options.
```
options.set_write_local_annotations(true);
```
But how could I keep the original names?

**Comment by ericbodden** [comment]
Hello.

This is an option in the “jb” pack. Please try the following command-line option:

-p jb use-original-names:true

You will find this documented here:
https://soot-build.cs.uni-paderborn.de/doc/sootoptions/

Let me know if that works.

Cheers
Eric

**Comment by pavanupb** [comment]
@martinschaef Please re-open if this is still relevant.
