### ISSUE TITLE
Incomplete call graphs with SPARK

### ISSUE THREAD

**Issue by manasthakur** [soot-oss/soot#566]
I am trying to analyze DaCapo's _avrora_ (not using _TamiFlex_). For constructing the call-graph, I was earlier using CHA, which was working fine but was imprecise. After switching to SPARK, however, I found that the call-graph constructed was very small, because of missing edges for significant method calls.

I understand from a reply by @StevenArzt in #439 that this might be because a direct assignment to the receiver is not present in the path to the call. However, I don't understand how to handle such cases.

Is there a way I could fall back to CHA (without incurring the cost of constructing two call graphs, if possible) in cases where there is no outgoing edge for a call-site in the call-graph constructed using SPARK?

**Comment by ericbodden** [comment]
Hello. You cannot possibly expect to construct a complete call graph using pointer analysis (such as SPARK) but without taking care of reflection. You should use TamiFlex - this is what it was designed for. I am afraid there are no shortcuts here.

**Comment by StevenArzt** [comment]
In general, @ericbodden is right. You might be able to do some coarse-grained over-approximation using SPARK's library mode. Have a look here: https://ssebuild.cased.de/nightly/soot/doc/soot_options.htm There is a phase cg.library with multiple possibilities. The original use case of this mode was to support analyzing libraries without knowing the user code, so you have a lot of method calls on parameters of uncalled functions (and thus base objects without type information).

**Comment by manasthakur** [comment]
@StevenArzt : Yes, this seems to be a possibility; I will experiment with it.

@ericbodden : I tried TamiFlex, but saw that there were many phantom classes and methods. I switched to a _build-from-scratch_ version because I found that the missing classes were present in that way. My guess is that it happens because the class files generated by TamiFlex are based on specific runs, which may lead to unsoundness. Please tell me if I am wrong or missing something.

**Comment by ericbodden** [comment]
Hi again.

> @ericbodden : I tried TamiFlex, but saw that there were many phantom classes and methods. I switched to a build-from-scratch version because I found that the missing classes were present in that way. My guess is that it happens because the class files generated by TamiFlex are based on specific runs, which may lead to unsoundness. Please tell me if I am wrong or missing something.

Yes sure, that’s the idea, including classes used on specific runs. But for benchmarks like avrora this is often what people do, so usually it’s not a big deal. But apparently you are interested in more than just a few runs?

Cheers,
Eric

**Comment by pavanupb** [comment]
@manasthakur Please re-open if this is still relevant.
