### ISSUE TITLE
Inconsistent inference of application classes?

### ISSUE THREAD

**Issue by ezal** [soot-oss/soot#569]
What Soot considers as application classes depends on whether Soot processes Java source files or Java byte code files. I would have expected that there's no such dependency.

I attach a small example. When running the program with the flag readSource set, then the output is "Application classes: [B, A]"; when the flag is not set that the output is "Application classes: [A]"
The source files A.java and B.java are found in the 'src' directory. A.class and B.class are found in the 'bin' directory.

I am using the nightly builds.  

[smallsoottest.zip](https://github.com/Sable/soot/files/206736/smallsoottest.zip)

**Comment by ezal** [comment]
I found this comment in the following tutorial: [https://github.com/Sable/soot/wiki/Creating-a-class-from-scratch](url)

> Implementation note: Soot loads these classes from either classfiles or .jimple input files. When the former is used, Soot will load all class names referred to in the constant pool of each class file. Loading from .jimple will make Soot load only the required types.

I guess that's related to the issue I'm mentioning and it means that at least that's expected behaviour.

Is it maybe worth putting the above remark in a more visible place, for instance [https://github.com/Sable/soot/wiki/Running-Soot](url)?

**Comment by pavanupb** [comment]
@ezal Please re-open if this is still relevant.
