### ISSUE TITLE
Creating CallGraph focusing on apk.

### ISSUE THREAD

**Issue by ZhengqiaoLi** [soot-oss/soot#572]
Code Snippets：
    Chain<SootClass> sm = Scene.v().getApplicationClasses();
                Set<String> sccc = new HashSet<String>();

```
            Iterator sm_it = sm.iterator();
            while(sm_it.hasNext()){
                SootClass sootclass = (SootClass) sm_it.next();
                if(!(sootclass.getName().startsWith("java."))&&!(sootclass.getName().startsWith("sun."))&&!(sootclass.getName().startsWith("android."))&&!(sootclass.getName().startsWith("org."))&&!(sootclass.getName().startsWith("soot."))&&!(sootclass.getName().startsWith("javax.")))
                {
                    sccc.add(sootclass.getName());
                }   
            }               
            Iterator sootclass_it = sccc.iterator();
            String mainclass = null;
            while(sootclass_it.hasNext()){
                String sootclass_real = (String)sootclass_it.next();
                if(sootclass_real.equals("com.example.source_a.MainActivity")){
                    mainclass = sootclass_real;
                }
            }
            System.out.println(mainclass);

            CHATransformer.v().transform();
            CallGraph cg = Scene.v().getCallGraph();
            SootClass mainclassmethod = Scene.v().getSootClass(mainclass);
            SootMethod ssssssss = mainclassmethod.getMethodByName("onCreate");
            Iterator targets = new Targets(cg.edgesOutOf(ssssssss));
            while(targets.hasNext()){
                SootMethod tgt = (SootMethod)targets.next();
                System.out.println(ssssssss+" might call "+tgt);
            }
        }});
```

but：
      There is no result！
could you help me？

**Comment by ericbodden** [comment]
What's your command line?

**Comment by ZhengqiaoLi** [comment]
@ericbodden 
Hi:
     Options.v().set_whole_program(true);
		Options.v().set_src_prec(Options.src_prec_apk);
		Options.v().set_output_format(Options.output_format_none);
		Options.v().set_process_dir(Collections.singletonList("G:\\Soot\\Source_A.apk"));
		Options.v().set_force_android_jar("E:\\IT-tools\\adt-bundle-windows-x86-20130219\\adt-bundle-windows-x86-20130219\\sdk\\platforms\\android-17\\android.jar");
		Options.v().set_soot_classpath("E:\\IT-tools\\adt-bundle-windows-x86-20130219\\adt-bundle-windows-x86-20130219\\sdk\\platforms\\android-17\\android.jar");
		Options.v().set_allow_phantom_refs(true);
		Options.v().set_app(true);		
		Scene.v().loadNecessaryClasses();
That‘s all.
Is there anything wrong with it?
please.

**Comment by ericbodden** [comment]
Hmm, it's hard to tell if seeing only bits and pieces of your code. I'd _strongly_ recommend you call Soot's main method, i.e. soot.Main.main. Soot will then construct a call graph automatically if the -w option is used. Then simply execute your remaining code from within a SceneTransformer. This can then access the call graph.

**Comment by ZhengqiaoLi** [comment]
oh, thank you. I'll try this method.

**Comment by ZhengqiaoLi** [comment]
@ericbodden 
Hi. I set program variables:
    -w
    -android-jars G:\\Soot\\sdk\\platforms\\
    -process-dir G:\\Soot\\HelloCallGraph.apk
And
    I used SceneTransformer and soot.Main.main.
But,
    I did not get CallGraph focusing on HelloCallGraph.apk. 

Code Snippets：
    Iterator targets = new Targets(cg.edgesOutOf(ssssssss));
    System.out.println(targets).
The result is : soot.jimple.toolkits.callgraph.Targets@1ada74e
Could you help me?

**Comment by ericbodden** [comment]
Hi.

> The result is : soot.jimple.toolkits.callgraph.Targets@1ada74e

This object is an Iterator. You need to iterate it to access the individual target methods.

Eric

**Comment by ZhengqiaoLi** [comment]
@ericbodden 
Hi,I was very confused about how to create CallGraph focusing on apk.
I want to know whether soot can create CallGraph without flowdroid. Because I did not get CallGraph.
Can you help me write a snippet?
Thank you.

**Comment by pavanupb** [comment]
@ZhengqiaoLi Please re-open if this is still relevant.
