### ISSUE TITLE
StackOverflowerror when println an unit in an apk

### ISSUE THREAD

**Issue by 2048li** [soot-oss/soot#575]
Hi,
when I println the units in an apk, it shows this error:
![sootstackoverflow](https://cloud.githubusercontent.com/assets/7392383/14515782/9d77857e-022f-11e6-85ef-425a9f66846b.png)

it maybe caused by the ring in the switchstmt?
![soottostring](https://cloud.githubusercontent.com/assets/7392383/14515872/54dbe62e-0230-11e6-9e2d-fe46504b6ccd.png)

[ps: the apk is larger than 10MB, so i cannot put here, which email I should send this apk?]

Thanks.

**Comment by StevenArzt** [comment]
With only that small fraction of your analysis code, it's hard to see what the problem is. Most likely, you have an infinite recursion somewhere or one that is just so large that the required stack space exceeds any reasonably boundaries.

**Comment by 2048li** [comment]
Thanks first.The thing is this: i just want to print unit.tostring in an apk, then it shows this error. I think this error maybe caused by the unit.tostring method in soot or just caused by the apk itself.[But if the apk has something wrong, how can it work well?]

**Comment by 2048li** [comment]
Any idea?Thanks!

**Comment by ericbodden** [comment]
How about using a debugger. Should be simple enough to see the problem then...

**Comment by 2048li** [comment]
Actually, when i use the eclipse to debug, it just shows "not responding", but the CPU is fully occupied. My question is that if the apk has a complicated construction[not too large], what would happen with soot to transform the class to jimple? will there be a Infinite loop?
Thanks!

**Comment by pavanupb** [comment]
@2048li Please re-open if this is still relevant.
