### ISSUE TITLE
type parse error : transform int to float?

### ISSUE THREAD

**Issue by 2048li** [soot-oss/soot#579]
Hi,
I used an apk to get call graph, here is the warning:
<img width="1279" alt="error-taotuobense-result" src="https://cloud.githubusercontent.com/assets/7392383/14682896/7659e7a4-075a-11e6-9c67-39c18f4e830a.png">
and then i checked the apk file, the codes are here:
![soottypeerrer2](https://cloud.githubusercontent.com/assets/7392383/14683051/4f823e8c-075b-11e6-9854-8c3cbc0fd415.png)
in this piece of code, the type of v2 and v1_2[0] should be int, 
however, in soot with the debug mode, I find the lefttype is float:
![soottypeerrer](https://cloud.githubusercontent.com/assets/7392383/14683093/815ae512-075b-11e6-9b4a-30e7d7421127.png)
I tried to find where the type transformed but failed.
Any idea? 
Thanks!

**Comment by StevenArzt** [comment]
Can you provide a download link for the APK file?

**Comment by 2048li** [comment]
Thanks. Here is the apk link:
http://pan.baidu.com/s/1pKPYMhX

**Comment by 2048li** [comment]
Hi, @StevenArzt ,
how is this issue going? I find no more than one app counters this problem.
Thanks!

**Comment by pavanupb** [comment]
@2048li Please re-open the issue if this is still relevant.
