### ISSUE TITLE
Unhandled type unknown exception

### ISSUE THREAD

**Issue by edwardmp** [soot-oss/soot#581]
Hi,

Thank you for making this library available. I am trying to generate a call list, but Soot fails even in on the most trivial programs.

Code:

```
        // create a list from args
        List<String> argsList = new ArrayList<>(Arrays.asList(args));

        // add on the following arguments
        argsList.addAll(Arrays.asList(new String[]{
                "-w",
                "-p",
                "jb",
                "enabled:false",
                "-cp",
                "/Users/epoot/Desktop/aevas/lib/javacg-0.1-SNAPSHOT-static.jar:/Library/Java/JavaVirtualMachines/CurrentJDK/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/CurrentJDK/Contents/Home/jre/lib/jce.jar",
                "gr.gousiosg.javacg.stat.ClassVisitor"
        }));

        args = argsList.toArray(new String[0]);
        soot.Main.main(args);
```

> java.lang.RuntimeException: Unhandled type unknown
>   at soot.FastHierarchy.canStoreType(FastHierarchy.java:216)
>   at soot.jimple.toolkits.callgraph.VirtualCalls.resolve(VirtualCalls.java:144)
>   at soot.jimple.toolkits.callgraph.VirtualCalls.resolve(VirtualCalls.java:130)
>   at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.addType(OnFlyCallGraphBuilder.java:452)
>   at soot.jimple.toolkits.callgraph.CallGraphBuilder.build(CallGraphBuilder.java:112)
>   at soot.jimple.toolkits.callgraph.CHATransformer.internalTransform(CHATransformer.java:46)
>   at soot.SceneTransformer.transform(SceneTransformer.java:39)
>   at soot.Transform.apply(Transform.java:90)
>   at soot.RadioScenePack.internalApply(RadioScenePack.java:57)
>   at soot.jimple.toolkits.callgraph.CallGraphPack.internalApply(CallGraphPack.java:49)
>   at soot.Pack.apply(Pack.java:118)
>   at soot.PackManager.runWholeProgramPacks(PackManager.java:570)
>   at soot.PackManager.runPacksNormally(PackManager.java:461)
>   at soot.PackManager.runPacks(PackManager.java:396)
>   at soot.Main.run(Main.java:271)
>   at soot.Main.main(Main.java:147)
>   at eu.sig.aevas.callgraph.WalaStatic.main(WalaStatic.java:26)
>   at eu.sig.aevas.AeVas.main(AeVas.java:13)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:498)
>   at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

I already disabled JB because this led to another exception being thrown:

> java.lang.RuntimeException: Failed to apply jb to <java.lang.invoke.InvokerBytecodeGenerator: void emitNewArray(java.lang.invoke.LambdaForm$Name)>
>   at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:1801)
>   at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:91)
>   at soot.SootMethod.retrieveActiveBody(SootMethod.java:322)
>   at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processNewMethod(OnFlyCallGraphBuilder.java:531)
>   at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processReachables(OnFlyCallGraphBuilder.java:420)
>   at soot.jimple.toolkits.callgraph.CallGraphBuilder.build(CallGraphBuilder.java:96)
>   at soot.jimple.toolkits.callgraph.CHATransformer.internalTransform(CHATransformer.java:46)
>   at soot.SceneTransformer.transform(SceneTransformer.java:39)
>   at soot.Transform.apply(Transform.java:90)
>   at soot.RadioScenePack.internalApply(RadioScenePack.java:57)
>   at soot.jimple.toolkits.callgraph.CallGraphPack.internalApply(CallGraphPack.java:49)
>   at soot.Pack.apply(Pack.java:118)
>   at soot.PackManager.runWholeProgramPacks(PackManager.java:570)
>   at soot.PackManager.runPacksNormally(PackManager.java:461)
>   at soot.PackManager.runPacks(PackManager.java:396)
>   at soot.Main.run(Main.java:271)
>   at soot.Main.main(Main.java:147)
>   at eu.sig.aevas.callgraph.WalaStatic.main(WalaStatic.java:26)
>   at eu.sig.aevas.AeVas.main(AeVas.java:13)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:498)
>   at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
> Caused by: soot.SootMethodRefImpl$ClassResolutionFailedException: Class java.lang.invoke.MethodHandle doesn't have method invoke([]) : java.lang.Object; failed to resolve in superclasses and interfacesLooking in java.lang.invoke.MethodHandle which has methods [<java.lang.invoke.MethodHandle: java.lang.invoke.MethodType type()>, <java.lang.invoke.MethodHandle: void <init>(java.lang.invoke.MethodType,java.lang.invoke.LambdaForm)>, <java.lang.invoke.MethodHandle: java.lang.Object invokeExact(java.lang.Object[])>, <java.lang.invoke.MethodHandle: java.lang.Object invoke(java.lang.Object[])>, <java.lang.invoke.MethodHandle: java.lang.Object invokeBasic(java.lang.Object[])>, <java.lang.invoke.MethodHandle: java.lang.Object linkToVirtual(java.lang.Object[])>, <java.lang.invoke.MethodHandle: java.lang.Object linkToStatic(java.lang.Object[])>, <java.lang.invoke.MethodHandle: java.lang.Object linkToSpecial(java.lang.Object[])>, <java.lang.invoke.MethodHandle: java.lang.Object linkToInterface(java.lang.Object[])>, <java.lang.invoke.MethodHandle: java.lang.Object invokeWithArguments(java.lang.Object[])>, <java.lang.invoke.MethodHandle: java.lang.Object invokeWithArguments(java.util.List)>, <java.lang.invoke.MethodHandle: java.lang.invoke.MethodHandle asType(java.lang.invoke.MethodType)>, <java.lang.invoke.MethodHandle: java.lang.invoke.MethodHandle asTypeCached(java.lang.invoke.MethodType)>, <java.lang.invoke.MethodHandle: java.lang.invoke.MethodHandle asTypeUncached(java.lang.invoke.MethodType)>, <java.lang.invoke.MethodHandle: java.lang.invoke.MethodHandle asSpreader(java.lang.Class,int)>, <java.lang.invoke.MethodHandle: java.lang.invoke.MethodType asSpreaderChecks(java.lang.Class,int)>, <java.lang.invoke.MethodHandle: void spreadArrayChecks(java.lang.Class,int)>, <java.lang.invoke.MethodHandle: java.lang.invoke.MethodHandle asCollector(java.lang.Class,int)>, <java.lang.invoke.MethodHandle: boolean asCollectorChecks(java.lang.Class,int)>, <java.lang.invoke.MethodHandle: java.lang.invoke.MethodHandle asVarargsCollector(java.lang.Class)>, <java.lang.invoke.MethodHandle: boolean isVarargsCollector()>, <java.lang.invoke.MethodHandle: java.lang.invoke.MethodHandle asFixedArity()>, <java.lang.invoke.MethodHandle: java.lang.invoke.MethodHandle bindTo(java.lang.Object)>, <java.lang.invoke.MethodHandle: java.lang.String toString()>, <java.lang.invoke.MethodHandle: java.lang.String standardString()>, <java.lang.invoke.MethodHandle: java.lang.String debugString()>, <java.lang.invoke.MethodHandle: java.lang.invoke.BoundMethodHandle bindArgumentL(int,java.lang.Object)>, <java.lang.invoke.MethodHandle: java.lang.invoke.MethodHandle setVarargs(java.lang.invoke.MemberName)>, <java.lang.invoke.MethodHandle: java.lang.invoke.MethodHandle viewAsType(java.lang.invoke.MethodType,boolean)>, <java.lang.invoke.MethodHandle: boolean viewAsTypeChecks(java.lang.invoke.MethodType,boolean)>, <java.lang.invoke.MethodHandle: java.lang.invoke.LambdaForm internalForm()>, <java.lang.invoke.MethodHandle: java.lang.invoke.MemberName internalMemberName()>, <java.lang.invoke.MethodHandle: java.lang.Class internalCallerClass()>, <java.lang.invoke.MethodHandle: java.lang.invoke.MethodHandleImpl$Intrinsic intrinsicName()>, <java.lang.invoke.MethodHandle: java.lang.invoke.MethodHandle withInternalMemberName(java.lang.invoke.MemberName,boolean)>, <java.lang.invoke.MethodHandle: boolean isInvokeSpecial()>, <java.lang.invoke.MethodHandle: java.lang.Object internalValues()>, <java.lang.invoke.MethodHandle: java.lang.Object internalProperties()>, <java.lang.invoke.MethodHandle: java.lang.invoke.MethodHandle copyWith(java.lang.invoke.MethodType,java.lang.invoke.LambdaForm)>, <java.lang.invoke.MethodHandle: java.lang.invoke.BoundMethodHandle rebind()>, <java.lang.invoke.MethodHandle: void updateForm(java.lang.invoke.LambdaForm)>, <java.lang.invoke.MethodHandle: void customize()>, <java.lang.invoke.MethodHandle: void <clinit>()>]
> Looking in java.lang.Object which has methods [<java.lang.Object: void <init>()>, <java.lang.Object: void registerNatives()>, <java.lang.Object: java.lang.Class getClass()>, <java.lang.Object: int hashCode()>, <java.lang.Object: boolean equals(java.lang.Object)>, <java.lang.Object: java.lang.Object clone()>, <java.lang.Object: java.lang.String toString()>, <java.lang.Object: void notify()>, <java.lang.Object: void notifyAll()>, <java.lang.Object: void wait(long)>, <java.lang.Object: void wait(long,int)>, <java.lang.Object: void wait()>, <java.lang.Object: void finalize()>, <java.lang.Object: void <clinit>()>]
> 
>   at soot.SootMethodRefImpl.resolve(SootMethodRefImpl.java:164)
>   at soot.SootMethodRefImpl.resolve(SootMethodRefImpl.java:109)
>   at soot.toolkits.exceptions.UnitThrowAnalysis.mightThrow(UnitThrowAnalysis.java:298)
>   at soot.toolkits.exceptions.UnitThrowAnalysis$ValueSwitch.caseInstanceInvokeExpr(UnitThrowAnalysis.java:1125)
>   at soot.toolkits.exceptions.UnitThrowAnalysis$ValueSwitch.caseVirtualInvokeExpr(UnitThrowAnalysis.java:970)
>   at soot.jimple.internal.AbstractVirtualInvokeExpr.apply(AbstractVirtualInvokeExpr.java:76)
>   at soot.toolkits.exceptions.UnitThrowAnalysis.mightThrow(UnitThrowAnalysis.java:293)
>   at soot.toolkits.exceptions.UnitThrowAnalysis$UnitSwitch.caseAssignStmt(UnitThrowAnalysis.java:753)
>   at soot.jimple.internal.JAssignStmt.apply(JAssignStmt.java:238)
>   at soot.toolkits.exceptions.UnitThrowAnalysis.mightThrow(UnitThrowAnalysis.java:277)
>   at soot.toolkits.graph.ExceptionalUnitGraph.buildExceptionDests(ExceptionalUnitGraph.java:347)
>   at soot.toolkits.graph.ExceptionalUnitGraph.initialize(ExceptionalUnitGraph.java:272)
>   at soot.toolkits.graph.ExceptionalUnitGraph.<init>(ExceptionalUnitGraph.java:159)
>   at soot.jimple.toolkits.scalar.UnreachableCodeEliminator.internalTransform(UnreachableCodeEliminator.java:79)
>   at soot.BodyTransformer.transform(BodyTransformer.java:51)
>   at soot.Transform.apply(Transform.java:105)
>   at soot.JimpleBodyPack.applyPhaseOptions(JimpleBodyPack.java:61)
>   at soot.JimpleBodyPack.internalApply(JimpleBodyPack.java:95)
>   at soot.Pack.apply(Pack.java:125)
>   at soot.asm.AsmMethodSource.getBody(AsmMethodSource.java:1799)
>   ... 23 more

Any ideas if this is a bug or If I'm doing something wrong?

**Comment by StevenArzt** [comment]
Disabling jb will most likely lead to severe issues during callgraph construction, because the jb pack performs important code preparation tasks. The important question is thus why jb fails. Which version of the JDK are you using in your Soot classpath? Is this an Oracle JDK or OpenJDK? Where can I get these JAR files from if it's not one of the standard JDK distributions?

**Comment by edwardmp** [comment]
Thanks for the quick reply!

So the exact example in Survivor's guide also fails. Indeed, maybe JVM use.

java -showversion .
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

I think this is the default JVM supplied with OS X? JAVA_HOME=/Library/Java/JavaVirtualMachines/CurrentJDK/Contents/Home

**Comment by StevenArzt** [comment]
Do you have a download link for "javacg-0.1-SNAPSHOT-static.jar"?

**Comment by edwardmp** [comment]
Of course! https://www.dropbox.com/s/wwy8vts0dhsbnej/javacg-0.1-SNAPSHOT-static.jar?dl=0
Although I tried it with another toy program, so I don't think it's really related to a specific app

**Comment by edwardmp** [comment]
Any idea if switching JVM version would solve this?

**Comment by StevenArzt** [comment]
This link gives me a HTTP 404 error code.

**Comment by edwardmp** [comment]
Here is a new link:
https://www.dropbox.com/s/a19dv05telk0fht/javacg-0.1-SNAPSHOT-static.jar?dl=0

**Comment by VijayKrishna** [comment]
Was there any resolution this issue?

**Comment by edwardmp** [comment]
@VijayKrishna thanks for the response. I did not continue with using Soot at that point and tried switching to another call graph library but other issues there prevent me from successfully using that library. So I'll look into this tomorrow. I was using Oracle's Java 8 VM on OS X so that would explain why you saw the same error.

Anyway, does soot itself support Java 8 now? Because the website says 7 is the highest supported version.

CC @StevenArzt

**Comment by JunyuPei** [comment]
These question is because you use soot.jar, lack of a lot of dependency. Two ways to deal with these question. 
1. Use the soot project, including the dependency.
2. Add the dependency jar into your project.
