### ISSUE TITLE
A problem about ExceptionalBlockGraph.

### ISSUE THREAD

**Issue by njupt-moon** [soot-oss/soot#585]
@StevenArzt 
Hi!
Here is the code snapshot:
public void tryOperation() {
    try {
        writeContacts();
    } catch(Exception e) {
        e.printStackTrace();
        System.out.println("error");
    } finally {
        nullFunction();
    }
}
The following is the ExceptionalBlockGraph I have got:
 public void tryOperation()
    {
        edu.njupt.dynamicpermission.MainActivity $r0;
        java.lang.Exception $r1;
        java.io.PrintStream $r2;
        java.lang.Throwable $r3;
        $r0 := @this: edu.njupt.dynamicpermission.MainActivity;
     label1:
        virtualinvoke $r0.edu.njupt.dynamicpermission.MainActivity: void writeContacts()();
     label2:
        virtualinvoke $r0.edu.njupt.dynamicpermission.MainActivity: void nullFunction()();
        return;
     label3:
        $r1 := @caughtexception;
     label4:
        virtualinvoke $r1.java.lang.Exception: void printStackTrace()();
        $r2 = java.lang.System: java.io.PrintStream out;
        virtualinvoke $r2.java.io.PrintStream: void println(java.lang.String)("error");
     label5:
        virtualinvoke $r0.<edu.njupt.dynamicpermission.MainActivity: void nullFunction()>();
        return;
     label6:
        $r3 := @caughtexception;
        virtualinvoke $r0.edu.njupt.dynamicpermission.MainActivity: void nullFunction()();
        throw $r3;
        catch java.lang.Exception from label1 to label2 with label3;
        catch java.lang.Throwable from label1 to label2 with label6;
        catch java.lang.Throwable from label4 to label5 with label6;
    }

Block 0:
[preds: ] [succs: 3 8 1 ]
$r0 := @this: edu.njupt.dynamicpermission.MainActivity;

Block 1:
[preds: 0 ] [succs: 3 8 2 ]
virtualinvoke $r0.edu.njupt.dynamicpermission.MainActivity: void writeContacts()();

Block 2:
[preds: 1 ] [succs: ]
virtualinvoke $r0.edu.njupt.dynamicpermission.MainActivity: void nullFunction()();
return;

Block 3:
[preds: 0 1 ] [succs: 4 8 ]
$r1 := @caughtexception;

Block 4:
[preds: 3 ] [succs: 5 8 ]
virtualinvoke $r1.java.lang.Exception: void printStackTrace()();

Block 5:
[preds: 4 ] [succs: 6 8 ]
$r2 = java.lang.System: java.io.PrintStream out;

Block 6:
[preds: 5 ] [succs: 7 8 ]
virtualinvoke $r2.java.io.PrintStream: void println(java.lang.String)("error");

Block 7:
[preds: 6 ] [succs: ]
virtualinvoke $r0.edu.njupt.dynamicpermission.MainActivity: void nullFunction()();
return;

Block 8:
[preds: 0 1 3 4 5 6 ] [succs: ]
$r3 := @caughtexception;
virtualinvoke $r0.edu.njupt.dynamicpermission.MainActivity: void nullFunction()();
throw $r3;

I do not know why the jimple code contains label6, why the ExceptionalBlockGraph contains Block8 and why the end of Block8 contains a throw statement.

**Comment by pavanupb** [comment]
@njupt-moon Please re-open the issue if this is still relevant.
