### ISSUE TITLE
Soot leftshift and bitwise XOR operator bug 

### ISSUE THREAD

**Issue by MadDoxXimba** [soot-oss/soot#619]
Good morning, I’m currently working on a project with my professor where I need to use hadoop, soot and mahout. The goal of this project is to generate logs and for that we are using the soot framework.

Bug occurrence: There are 3 class (wrote by my professor) that am using. These classes are used to insert code in .class files. The inserted codes will help to generate logs (/tmp/traceLog). The bug happened when trying to insert (or transform) a .class file that contain one or both of these operators (leftshift/bitwise XOR).

Here is the exception generated:

`[Thread-16] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: Invalid argument type for shl
java.lang.RuntimeException: Invalid argument type for shl
    at soot.jimple.JasminClass$7$16.defaultCase(JasminClass.java:2538)
    at soot.TypeSwitch.caseUnknownType(TypeSwitch.java:91)
    at soot.UnknownType.apply(UnknownType.java:60)
    at soot.jimple.JasminClass$7.caseShlExpr(JasminClass.java:2518)
    at soot.grimp.internal.GShlExpr.apply(GShlExpr.java:43)
    at soot.jimple.JasminClass.emitValue(JasminClass.java:1608)
    at soot.jimple.JasminClass$7.caseAndExpr(JasminClass.java:1654)
    at soot.grimp.internal.GAndExpr.apply(GAndExpr.java:43)
    at soot.jimple.JasminClass.emitValue(JasminClass.java:1608)
    at soot.jimple.JasminClass$7.caseCmpExpr(JasminClass.java:1865)
    at soot.grimp.internal.GCmpExpr.apply(GCmpExpr.java:43)
    at soot.jimple.JasminClass.emitValue(JasminClass.java:1608)
    at soot.jimple.JasminClass.emitIfStmt(JasminClass.java:783)
    at soot.jimple.JasminClass$5.caseIfStmt(JasminClass.java:1305)
    at soot.jimple.internal.JIfStmt.apply(JIfStmt.java:137)
    at soot.jimple.JasminClass.emitStmt(JasminClass.java:1231)
    at soot.jimple.JasminClass.emitMethodBody(JasminClass.java:476)
    at soot.AbstractJasminClass.emitMethod(AbstractJasminClass.java:769)
    at soot.AbstractJasminClass.<init>(AbstractJasminClass.java:648)
    at soot.jimple.JasminClass.<init>(JasminClass.java:71)
    at soot.PackManager.writeClass(PackManager.java:1119)
    at soot.PackManager.access$100(PackManager.java:137)
    at soot.PackManager$2.run(PackManager.java:673)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: Invalid argument type for shl
    at soot.jimple.JasminClass$7$16.defaultCase(JasminClass.java:2538)
    at soot.TypeSwitch.caseUnknownType(TypeSwitch.java:91)
    at soot.UnknownType.apply(UnknownType.java:60)
    at soot.jimple.JasminClass$7.caseShlExpr(JasminClass.java:2518)
    at soot.grimp.internal.GShlExpr.apply(GShlExpr.java:43)
    at soot.jimple.JasminClass.emitValue(JasminClass.java:1608)
    at soot.jimple.JasminClass$7.caseAndExpr(JasminClass.java:1654)
    at soot.grimp.internal.GAndExpr.apply(GAndExpr.java:43)
    at soot.jimple.JasminClass.emitValue(JasminClass.java:1608)
    at soot.jimple.JasminClass$7.caseCmpExpr(JasminClass.java:1865)
    at soot.grimp.internal.GCmpExpr.apply(GCmpExpr.java:43)
    at soot.jimple.JasminClass.emitValue(JasminClass.java:1608)
    at soot.jimple.JasminClass.emitIfStmt(JasminClass.java:783)
    at soot.jimple.JasminClass$5.caseIfStmt(JasminClass.java:1305)
    at soot.jimple.internal.JIfStmt.apply(JIfStmt.java:137)
    at soot.jimple.JasminClass.emitStmt(JasminClass.java:1231)
    at soot.jimple.JasminClass.emitMethodBody(JasminClass.java:476)
    at soot.AbstractJasminClass.emitMethod(AbstractJasminClass.java:769)
    at soot.AbstractJasminClass.<init>(AbstractJasminClass.java:648)
    at soot.jimple.JasminClass.<init>(JasminClass.java:71)
    at soot.PackManager.writeClass(PackManager.java:1119)
    at soot.PackManager.access$100(PackManager.java:137)
    at soot.PackManager$2.run(PackManager.java:673)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Exception in thread "Thread-16" java.lang.RuntimeException: Invalid argument type for shl
    at soot.jimple.JasminClass$7$16.defaultCase(JasminClass.java:2538)
    at soot.TypeSwitch.caseUnknownType(TypeSwitch.java:91)
    at soot.UnknownType.apply(UnknownType.java:60)
    at soot.jimple.JasminClass$7.caseShlExpr(JasminClass.java:2518)
    at soot.grimp.internal.GShlExpr.apply(GShlExpr.java:43)
    at soot.jimple.JasminClass.emitValue(JasminClass.java:1608)
    at soot.jimple.JasminClass$7.caseAndExpr(JasminClass.java:1654)
    at soot.grimp.internal.GAndExpr.apply(GAndExpr.java:43)
    at soot.jimple.JasminClass.emitValue(JasminClass.java:1608)
    at soot.jimple.JasminClass$7.caseCmpExpr(JasminClass.java:1865)
    at soot.grimp.internal.GCmpExpr.apply(GCmpExpr.java:43)
    at soot.jimple.JasminClass.emitValue(JasminClass.java:1608)
    at soot.jimple.JasminClass.emitIfStmt(JasminClass.java:783)
    at soot.jimple.JasminClass$5.caseIfStmt(JasminClass.java:1305)
    at soot.jimple.internal.JIfStmt.apply(JIfStmt.java:137)
    at soot.jimple.JasminClass.emitStmt(JasminClass.java:1231)
    at soot.jimple.JasminClass.emitMethodBody(JasminClass.java:476)
    at soot.AbstractJasminClass.emitMethod(AbstractJasminClass.java:769)
    at soot.AbstractJasminClass.<init>(AbstractJasminClass.java:648)
    at soot.jimple.JasminClass.<init>(JasminClass.java:71)
    at soot.PackManager.writeClass(PackManager.java:1119)
    at soot.PackManager.access$100(PackManager.java:137)
    at soot.PackManager$2.run(PackManager.java:673)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)`

Futhermore here is the command line that I used:

`java -Xms512M -Xmx1024M -cp $SOOT_HOME/jasminclasses-custom.jar:$SOOT_HOME/polyglotclasses-1.3.5.jar:$SOOT_HOME/soot-trunk.jar:$SOOT_HOME/commons-io-2.4-bin/commons-io-2.4/commons-io-2.4.jar:$SOOT_HOME/log4j-1.2.11.jar:$SOOT_HOME/symja-2015-09-26.jar:/home/joe/Development/sootTools/LogInserterDummy.jar  LoggerMain -cp .:$JAVA_HOME/jre/lib/rt.jar:$JAVA_HOME/jre/lib/jce.jar:/home/joe/yuechun/hadoop-0.20.204.0/hadoop-core-0.20.204.0.jar:/home/joe/yuechun/hadoop-0.20.204.0/hadoop-tools-0.20.204.0.jar:$SOOT_HOME/commons-logging-1.1.3.jar:$SOOT_HOME/commons-cli-1.2.jar:/home/joe/yuechun/mahout-distribution-0.7/mahout-math-0.7.jar:/home/joe/yuechun/mahout-distribution-0.7/lib/guava-r09.jar:/home/joe/yuechun/mahout-distribution-0.7/lib/slf4j-api-1.6.1.jar:/home/joe/yuechun/mahout-distribution-0.7/lib/commons-cli-2.0-mahout.jar:/home/joe/yuechun/mahout-distribution-0.7/lib/commons-lang-2.6.jar:/home/joe/yuechun/mahout-distribution-0.7/lib/lucene-analyzers-3.6.0.jar:/home/joe/yuechun/mahout-distribution-0.7/lib/lucene-core-3.6.0.jar:/home/joe/yuechun/mahout-distribution-0.7/lib/commons-math-2.2.jar:/home/joe/yuechun/mahout-distribution-0.7/lib/uncommons-maths-1.2.2.jar:/home/joe/yuechun/mahout-distribution-0.7/lib/xstream-1.3.1.jar  -src-prec c -f c -include-all -process-dir /home/joe/yuechun/mahoutsrc/mahout-mahout-0.7/core/target/classes -output-dir /home/joe/yuechun/mahoutsrc/mahout-mahout-0.7/core/target/classes-logs -via-grimp`

as you may have noticed, there is a file called LogInserterDummy.jar (this is the classes that I talked earlier). 

I'm running this command line on a:
ubuntu 14.04 LTS / RAM 4 GB / Processor Intel core i7 4790 CPU@3.6GHz*8 / Gallium 0.4 on AMD CEDAR / os 64 bit

In addition, I was able to reproduce the bug on a test case:

Command line:

java -Xms512M -Xmx1024M -cp $SOOT_HOME/jasminclasses-custom.jar:$SOOT_HOME/polyglotclasses-1.3.5.jar:$SOOT_HOME/soot-trunk.jar:$SOOT_HOME/commons-io-2.4-bin/commons-io-2.4/commons-io-2.4.jar:$SOOT_HOME/log4j-1.2.11.jar:$SOOT_HOME/symja-2015-09-26.jar:/home/joe/Development/sootTools/LogInserterDummy.jar  LoggerMain -cp .:$JAVA_HOME/jre/lib/rt.jar:$JAVA_HOME/jre/lib/jce.jar:/home/joe/yuechun/hadoop-0.20.204.0/hadoop-core-0.20.204.0.jar:/home/joe/yuechun/hadoop-0.20.204.0/hadoop-tools-0.20.204.0.jar:$SOOT_HOME/commons-logging-1.1.3.jar:$SOOT_HOME/commons-cli-1.2.jar:/home/joe/yuechun/mahout-distribution-0.7/mahout-math-0.7.jar:/home/joe/yuechun/mahout-distribution-0.7/lib/guava-r09.jar:/home/joe/yuechun/mahout-distribution-0.7/lib/slf4j-api-1.6.1.jar:/home/joe/yuechun/mahout-distribution-0.7/lib/commons-cli-2.0-mahout.jar:/home/joe/yuechun/mahout-distribution-0.7/lib/commons-lang-2.6.jar:/home/joe/yuechun/mahout-distribution-0.7/lib/lucene-analyzers-3.6.0.jar:/home/joe/yuechun/mahout-distribution-0.7/lib/lucene-core-3.6.0.jar:/home/joe/yuechun/mahout-distribution-0.7/lib/commons-math-2.2.jar:/home/joe/yuechun/mahout-distribution-0.7/lib/uncommons-maths-1.2.2.jar:/home/joe/yuechun/mahout-distribution-0.7/lib/xstream-1.3.1.jar  -src-prec c -f c -include-all -process-dir /home/joe/yuechun/64bits-WorkSpace/BitOperator/bin -output-dir /home/joe/yuechun/64bits-WorkSpace/BitOperator/classes-logs -via-grimp

Code (class to be transform):

`package helloWorld;

public class HelloWorld {

```
public static void main(String[] args) {
    // TODO Auto-generated method stub
    int l = 5;
    for (int i = 0; i < 20; i++) {

        System.out.println("****Starting for i = " + i);

        for (int j = 20; j >0; j--) {

            System.out.println(i^j);
            System.out.println(" ^ operator = " + (i^j));
            System.out.println(" << operator = " + (i << j));
            System.out.println(" >> operator = " + (i >> j));
            System.out.println((l & 1L << j) == 0 ? '0' : '1');

        }
        System.out.println("****END****");
    }

}
```

}`

Soot version nightly build

Thanks in advance for spending your time reading through this post :)

LogInserter:
[LogInserter.zip](https://github.com/Sable/soot/files/403439/LogInserter.zip)

**Comment by ericbodden** [comment]
Hello.

Thanks for the note. Could you please have a look at the Jimple code that Soot generates for the respective method? You can use “-f jimple” to have Soot produce Jimple output. It would help to see whether the Jimple looks correct.

Cheers
Eric

**Comment by StevenArzt** [comment]
Hi,

You write that you are using Soot 2.5. This version (albeit being the 
last official release version) is quite old and outdated by now. Can you 
pleae try again using the latest nightly build and check whether the 
problem still occurs?

Best regards,
   Steven

**Comment by MadDoxXimba** [comment]
@StevenArzt 
I made a mistake when I wrote the version of soot I am using is 2.5. It's actually the nightly build that I am using. Sorry for that.

**Comment by MadDoxXimba** [comment]
@ericbodden 
here is the jimple I created with the eclipse plugin:

``public class helloWorld.HelloWorld extends java.lang.Object
{

    public static void main(java.lang.String[])
    {
        java.lang.String[] args;
        int l, i, j, temp$4, temp$7, temp$11, temp$15, temp$22, temp$23, temp$24, temp$26, temp$27;
        java.io.PrintStream temp$0, temp$3, temp$5, temp$9, temp$13, temp$17, temp$25;
        java.lang.StringBuffer temp$1, temp$6, temp$10, temp$14;
        java.lang.String temp$2, temp$8, temp$12, temp$16;
        char temp$18;
        long temp$19, temp$20, temp$21;

        args := @parameter0: java.lang.String[];
        l = 5;
        i = 0;

     label0:
        nop;
        if i < 20 goto label1;

        goto label8;

     label1:
        nop;
        temp$0 = <java.lang.System: java.io.PrintStream out>;
        temp$1 = new java.lang.StringBuffer;
        specialinvoke temp$1.<java.lang.StringBuffer: void <init>()>();
        virtualinvoke temp$1.<java.lang.StringBuffer: java.lang.StringBuffer append(java.lang.Object)>("****Starting for i = ");
        virtualinvoke temp$1.<java.lang.StringBuffer: java.lang.StringBuffer append(int)>(i);
        temp$2 = virtualinvoke temp$1.<java.lang.StringBuffer: java.lang.String toString()>();
        virtualinvoke temp$0.<java.io.PrintStream: void println(java.lang.String)>(temp$2);
        j = 20;

     label2:
        nop;
        if j > 0 goto label3;

        goto label7;

     label3:
        nop;
        temp$3 = <java.lang.System: java.io.PrintStream out>;
        temp$4 = i ^ j;
        virtualinvoke temp$3.<java.io.PrintStream: void println(int)>(temp$4);
        temp$5 = <java.lang.System: java.io.PrintStream out>;
        temp$6 = new java.lang.StringBuffer;
        specialinvoke temp$6.<java.lang.StringBuffer: void <init>()>();
        virtualinvoke temp$6.<java.lang.StringBuffer: java.lang.StringBuffer append(java.lang.Object)>(" ^ operator = ");
        temp$7 = i ^ j;
        virtualinvoke temp$6.<java.lang.StringBuffer: java.lang.StringBuffer append(int)>(temp$7);
        temp$8 = virtualinvoke temp$6.<java.lang.StringBuffer: java.lang.String toString()>();
        virtualinvoke temp$5.<java.io.PrintStream: void println(java.lang.String)>(temp$8);
        temp$9 = <java.lang.System: java.io.PrintStream out>;
        temp$10 = new java.lang.StringBuffer;
        specialinvoke temp$10.<java.lang.StringBuffer: void <init>()>();
        virtualinvoke temp$10.<java.lang.StringBuffer: java.lang.StringBuffer append(java.lang.Object)>(" << operator = ");
        temp$11 = i << j;
        virtualinvoke temp$10.<java.lang.StringBuffer: java.lang.StringBuffer append(int)>(temp$11);
        temp$12 = virtualinvoke temp$10.<java.lang.StringBuffer: java.lang.String toString()>();
        virtualinvoke temp$9.<java.io.PrintStream: void println(java.lang.String)>(temp$12);
        temp$13 = <java.lang.System: java.io.PrintStream out>;
        temp$14 = new java.lang.StringBuffer;
        specialinvoke temp$14.<java.lang.StringBuffer: void <init>()>();
        virtualinvoke temp$14.<java.lang.StringBuffer: java.lang.StringBuffer append(java.lang.Object)>(" >> operator = ");
        temp$15 = i >> j;
        virtualinvoke temp$14.<java.lang.StringBuffer: java.lang.StringBuffer append(int)>(temp$15);
        temp$16 = virtualinvoke temp$14.<java.lang.StringBuffer: java.lang.String toString()>();
        virtualinvoke temp$13.<java.io.PrintStream: void println(java.lang.String)>(temp$16);
        temp$17 = <java.lang.System: java.io.PrintStream out>;
        temp$19 = 1L << j;
        temp$20 = (long) l;
        temp$21 = temp$20 & temp$19;
        temp$22 = temp$21 cmp 0L;
        if temp$22 != 0 goto label5;

        goto label4;

     label4:
        nop;
        temp$18 = 48;
        goto label6;

     label5:
        nop;
        temp$18 = 49;

     label6:
        nop;
        virtualinvoke temp$17.<java.io.PrintStream: void println(char)>(temp$18);
        nop;
        temp$23 = j;
        temp$24 = temp$23 + -1;
        j = temp$24;
        goto label2;

     label7:
        nop;
        temp$25 = <java.lang.System: java.io.PrintStream out>;
        virtualinvoke temp$25.<java.io.PrintStream: void println(java.lang.String)>("****END****");
        nop;
        temp$26 = i;
        temp$27 = temp$26 + 1;
        i = temp$27;
        goto label0;

     label8:
        nop;
        return;
    }

    public void <init>()
    {
        helloWorld.HelloWorld this;

        this := @this: helloWorld.HelloWorld;
        specialinvoke this.<java.lang.Object: void <init>()>();
        return;
    }
}

and here is the grimp:

`public class helloWorld.HelloWorld extends java.lang.Object
{

    public static void main(java.lang.String[])
    {
        java.lang.String[] args;
        int l, i, j, temp$4, temp$7, temp$11, temp$15, temp$22, temp$23, temp$24, temp$26, temp$27;
        java.io.PrintStream temp$0, temp$3, temp$5, temp$9, temp$13, temp$17, temp$25;
        java.lang.StringBuffer temp$1, temp$6, temp$10, temp$14;
        java.lang.String temp$2, temp$8, temp$12, temp$16;
        char temp$18;
        long temp$19, temp$20, temp$21;

        args := @parameter0: java.lang.String[];
        l = 5;
        i = 0;

     label0:
        nop;
        if i < 20 goto label1;

        goto label8;

     label1:
        nop;
        temp$0 = <java.lang.System: java.io.PrintStream out>;
        temp$1 = new java.lang.StringBuffer;
        specialinvoke temp$1.<java.lang.StringBuffer: void <init>()>();
        virtualinvoke temp$1.<java.lang.StringBuffer: java.lang.StringBuffer append(java.lang.Object)>("****Starting for i = ");
        virtualinvoke temp$1.<java.lang.StringBuffer: java.lang.StringBuffer append(int)>(i);
        temp$2 = virtualinvoke temp$1.<java.lang.StringBuffer: java.lang.String toString()>();
        virtualinvoke temp$0.<java.io.PrintStream: void println(java.lang.String)>(temp$2);
        j = 20;

     label2:
        nop;
        if j > 0 goto label3;

        goto label7;

     label3:
        nop;
        temp$3 = <java.lang.System: java.io.PrintStream out>;
        temp$4 = i ^ j;
        virtualinvoke temp$3.<java.io.PrintStream: void println(int)>(temp$4);
        temp$5 = <java.lang.System: java.io.PrintStream out>;
        temp$6 = new java.lang.StringBuffer;
        specialinvoke temp$6.<java.lang.StringBuffer: void <init>()>();
        virtualinvoke temp$6.<java.lang.StringBuffer: java.lang.StringBuffer append(java.lang.Object)>(" ^ operator = ");
        temp$7 = i ^ j;
        virtualinvoke temp$6.<java.lang.StringBuffer: java.lang.StringBuffer append(int)>(temp$7);
        temp$8 = virtualinvoke temp$6.<java.lang.StringBuffer: java.lang.String toString()>();
        virtualinvoke temp$5.<java.io.PrintStream: void println(java.lang.String)>(temp$8);
        temp$9 = <java.lang.System: java.io.PrintStream out>;
        temp$10 = new java.lang.StringBuffer;
        specialinvoke temp$10.<java.lang.StringBuffer: void <init>()>();
        virtualinvoke temp$10.<java.lang.StringBuffer: java.lang.StringBuffer append(java.lang.Object)>(" << operator = ");
        temp$11 = i << j;
        virtualinvoke temp$10.<java.lang.StringBuffer: java.lang.StringBuffer append(int)>(temp$11);
        temp$12 = virtualinvoke temp$10.<java.lang.StringBuffer: java.lang.String toString()>();
        virtualinvoke temp$9.<java.io.PrintStream: void println(java.lang.String)>(temp$12);
        temp$13 = <java.lang.System: java.io.PrintStream out>;
        temp$14 = new java.lang.StringBuffer;
        specialinvoke temp$14.<java.lang.StringBuffer: void <init>()>();
        virtualinvoke temp$14.<java.lang.StringBuffer: java.lang.StringBuffer append(java.lang.Object)>(" >> operator = ");
        temp$15 = i >> j;
        virtualinvoke temp$14.<java.lang.StringBuffer: java.lang.StringBuffer append(int)>(temp$15);
        temp$16 = virtualinvoke temp$14.<java.lang.StringBuffer: java.lang.String toString()>();
        virtualinvoke temp$13.<java.io.PrintStream: void println(java.lang.String)>(temp$16);
        temp$17 = <java.lang.System: java.io.PrintStream out>;
        temp$19 = 1L << j;
        temp$20 = (long) l;
        temp$21 = temp$20 & temp$19;
        temp$22 = temp$21 cmp 0L;
        if temp$22 != 0 goto label5;

        goto label4;

     label4:
        nop;
        temp$18 = 48;
        goto label6;

     label5:
        nop;
        temp$18 = 49;

     label6:
        nop;
        virtualinvoke temp$17.<java.io.PrintStream: void println(char)>(temp$18);
        nop;
        temp$23 = j;
        temp$24 = temp$23 + -1;
        j = temp$24;
        goto label2;

     label7:
        nop;
        temp$25 = <java.lang.System: java.io.PrintStream out>;
        virtualinvoke temp$25.<java.io.PrintStream: void println(java.lang.String)>("****END****");
        nop;
        temp$26 = i;
        temp$27 = temp$26 + 1;
        i = temp$27;
        goto label0;

     label8:
        nop;
        return;
    }

    public void <init>()
    {
        helloWorld.HelloWorld this;

        this := @this: helloWorld.HelloWorld;
        specialinvoke this.<java.lang.Object: void <init>()>();
        return;
    }
}
`

**Comment by MadDoxXimba** [comment]
The LogInserterDummy do nothing but using the soot gb phase. The code is as follows:
`

public class LoggerMain {

	public static void main(String[] args) {
		PackManager.v().getPack( "gb" ).add( 
				new Transform("gb.LogInserter", new BodyTransformer() {
				      protected void internalTransform(Body body, String phase, Map options) {
				        new LogInserter(body);
				      }
				    }) );
		soot.Main.main(args);
	}
	
	public static class LogInserter{
		public LogInserter(Body aBody) {
                          return;
                }
         }
}

`
The exception happens when writing to class files.
For example,  log is as 
"Writing to <class path>/<classname>.class"

**Comment by voyager1983** [comment]
It seems the exception happens when "<<" or ">>" operators are applied on the long type number.

**Comment by pavanupb** [comment]
@MadDoxXimba Please re-open the issue if this is still relevant.
