### ISSUE TITLE
Add support for MethodHandle Constants 

### ISSUE THREAD

**Issue by akbertram** [soot-oss/soot#636]
I would like to add support for MethodHandle constants to Soot, which we need in order to be able to fully integrate Soot into Renjin's [GCC-Bridge](http://www.renjin.org/blog/2016-01-31-introducing-gcc-bridge.html). Right now, we can only use it on a case-by-case basis for C that doesn't use function pointers.

**Comment by pavanupb** [comment]
@akbertram Please re-open if this is still relevant.
