### ISSUE TITLE
Legacy-Free Soot

### ISSUE THREAD

**Issue by StevenArzt** [soot-oss/soot#654]
Soot has grown over the past years with lots of cool projects and features being added. By now, the code base has a considerable size and complexity. However, not all of these features are commonly used, some seem to have no users at all anymore. I feel that we need to have a discussion in the community of which parts of Soot we want to actively maintain in the long term and what we want cut of the main Soot code tree. There are some modules that only very few people (if any) use, but that still need to be maintained and taken care of when running build systems, refactoring code, or simply running automated tests. Here's a (most likely incomplete) list of stuff that, in my opinion, we should remove from the main development tree at some point:

1) The Java source front-end based on JastAddJ 1.0. The old JastAddJ is not maintained anymore, the old SVNs don't even exist anymore, our build machines are hosting local copies to be able to fulfill the dependencies. The API of JastAddJ 1 is incompatible with JastAddJ 2, so this code won't be of any use moving forward. Furthermore, JastAddJ 1 only supports code up to Java 1.5, so you can't use Soot's source code front-end for any halfway recent code anyway.

2) Dava. We tried to use it in one of our internal projects, uncovered a whole host of bugs, and abandoned it at some point, because it never got stable enough for productive use. Back then, we didn't have the resources to get Dava fully right. Furthermore, there are much better decompilers under the LGPL license by now, so, at least for us, there's little point in having Dava around or working on it anymore.

3) The Jasmin backend. We have long since switched to a new ASM-based backend which is doing fine in lots of heavily-tested projects on our side, while there are several known issues with Jasmin. Particularly, Jasmin cannot provide the type annotations required by modern JVMs.

My proposal is to call what we have Soot 3.0 at some point and have a real release, given that the last release is not only dated, but ancient by now. After that, we can make the proposed removals and start with a clean development branch for going forward.

Do you have other candidates for removal or any objections to the above list? Note that we might factor these parts out into a separate "legacy" project in case people still want to have them for reference, and still get them out of the development branch.

Joining in some of the other maintainers: @ericbodden @ljhendren @patricklam

**Comment by ericbodden** [comment]
Hi Steven.

Thanks for bringing this up, I appreciate the initiative and I generally agree with the plan to “clean up” Soot. The points you propose make sense to me but we should probably also discuss if for such a 3.0 version, which would be a breaking change, we don’t even want to go a step further and restructure some parts of Soot to make it more future-proof.

I remember for instance that for years we have been thinking of parallelizing Jimplification and @patricklam had a good go at this once but using the current structure it’s apparently just too hard to get right. This is something we might want to look into again.

Laurie, Patrick what are your thoughts?

Best wishes
Eric

**Comment by patricklam** [comment]
This all sounds good to me. We do have a different Java source front-end,
yes?

**Comment by ericbodden** [comment]
> This all sounds good to me. We do have a different Java source front-end,
> yes?

Right now I don’t believe we do. So that’s definitely something we should discuss. Coincidentally just this week somebody emailed me because he was interested in updating it to Java 8 (using JastAdd). Hence I don’t think we should reject the frontend so easily - unless we have a better option. Something we could do, though, is make it an optional package. That would definitely make the rest of Soot easier to build.

Cheers
Eric

**Comment by patricklam** [comment]
Parallelizing? Yeah, I've thought that we could do that with recent
technology, in particular a good race detection tool to support the effort.
It seems like it should be doable as a course project but maybe it has to
be a master's project?

**Comment by patricklam** [comment]
As it turns out, I do have a master's student who just started. Might be
good to get him doing that.

**Comment by StevenArzt** [comment]
We don't have a stable replacement source front-end right now. Some students of mine started this as a course project (based on the AST created by the javac compiler from OpenJDK), but their code needs completion and testing. If you have someone who wants to take on that, I am happy to share the code.

I'm all for refactorings and restructuring for a 3.0 version of Soot. A structure that would allow us to more easily integrate the parallelization would definitely be helpful. Furthermore, there are some performance bootlenecks that we need to address in a more general way. For instance, some operations on Jimple bodies such as obtaining the "this" reference iterate over the body each and every time (because they assume that bodies can change arbitrarily at anytime and we have no other mechanism to take care of that), which makes them a nice hotspot in almost any kind of static analysis, because these methods are called all over the place. There's more like that to be found.

**Comment by ericbodden** [comment]
I am closing this for now, as much of this will be handled by the FutureSoot DFG project.
