### ISSUE TITLE
Soot replacing variable names with others found in the same file

### ISSUE THREAD

**Issue by clydevassallo** [soot-oss/soot#656]
Soot is replacing my variables with names of other variables in the file.
Consider line 200 in the input file, the _update_ variable name is replace with _bUserId_ in the OutputJimple. _bUserId_ is used in line 110 of the input file and has nothing to do with the statement in line 200.

Input File:
[basket_jsp.txt](https://github.com/Sable/soot/files/544149/basket_jsp.txt)

RespectiveMethodActiveBody:
[jspServiceMethodActiveBody.txt](https://github.com/Sable/soot/files/544147/jspServiceMethodActiveBody.txt)

OutputJimple:
[org.apache.jsp.root.basket_jsp.txt](https://github.com/Sable/soot/files/544150/org.apache.jsp.root.basket_jsp.txt)

This only happens when "use-original-names" is set to true.

**Comment by ericbodden** [comment]
Hello.

Have you read about the —keep-original-names option?

Eric

**Comment by pavanupb** [comment]
@clydevassallo Please re-open if this is still relevant.
