### ISSUE TITLE
ConcurrentmodificationException: Scene changed for hierarchy

### ISSUE THREAD

**Issue by 2048li** [soot-oss/soot#661]
Hi,
Excuse me, I use soot to get the activity hierarchy of one apk, I did in the following steps:
"
...inialisesoot[load one apk];
Hierarchy hierarchy = Scent.v().getActivityHierarchy();
for (SootClass sc: Scene.v().getApplicationClasses()){
if (!hierarchy.getDirectSubclassesOf(sc).isEmpty)
...}
"
And then I got the error:
"Exception in thread "main" java.util.ConcurrentModificationException: Scene changed for hierarchy!"
But during this process, the scene is from the same apk. And then I printed the state and hierarchy for each sootclass and found they are the same. So why it throws ConcurrentModificationException? 
And I do not understand why there is "checkstate()" method in the Hierarchy.class.

Thanks!

**Comment by pavanupb** [comment]
@2048li Please re-open the issue if this is still relevant.
