### ISSUE TITLE
Instrumenting Android Apps

### ISSUE THREAD

**Issue by gazzaz86** [soot-oss/soot#662]
I am trying to instrument Android app. And, I would like to know the right command line to do it using my my driver class called AndroidInstrument.java

I have been trying the following but it did not work. 
java -Xmx2g -jar soot-trunk.jar -allow-phantom-refs -cp ".:soot-2.5.0.jar:/usr/local/android-studio/jre/jre/lib/rt.jar" AndroidInstrument -android-jars "/home/ali/Android/Sdk/platforms" -process-dir "HelloWorld.apk"

I got the following error:
Error: Failed to load java.util.Map$Entry
Thanks in advance.

**Comment by campiador** [comment]
any luck?

**Comment by pavanupb** [comment]
@gazzaz86 Please re-open the issue if this is still relevant.
