### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: couldn't find class: java.lang.Object with Hello.java

### ISSUE THREAD

**Issue by mmendozap** [soot-oss/soot#669]
I have been following the tutorial. java -cp lib/soot-2.5.0.jar soot.Main -cp . -pp A B works fine, but when I try to convert the Hello.class into .jimple: java -cp lib/soot-2.5.0.jar soot.Main -cp . -pp -f jimple Hello ,it doesn't  work. I get the error "Exception in thread "main" java.lang.RuntimeException: couldn't find class: java.lang.Object (is your soot-class-path set properly?) Try adding rt.jar to Soot's classpath "' 

I already tried with the rt.jar path, but this should be solved when using -pp

**Comment by pavanupb** [comment]
@mmendozap Please re-open the issue if this is still relevant.
