### ISSUE TITLE
CallGraph construction is missing button callbacks defined in layout files

### ISSUE THREAD

**Issue by gianlucascoccia** [soot-oss/soot#670]
I'm trying to use Soot to perform some analysis on Android apps. 
I have a simple app that in its MainActivity layout files defines several button.
When I try to build the Call Graph of my app all these methods are missing (also absent from  ReachableMethods).
I can't really understand why this happens, my code is derived from examples from the soot mailing list and other sources and I'm performing the exact same steps that they do. Could it be possible that soots misses some callbacks in layout files? My code follows, the app I'm using is attached.

                File apk = new File("./inputs/app-debug.apk");
		File sAs = new File("./inputs/sourcesAndSinks.txt");
		File androidJars = new File("./inputs/android-jars");
		File androidCallbacks = new File("./inputs/AndroidCallbacks.txt");
		
		SetupApplication setupApplication = new SetupApplication(androidJars.toString(), apk.toString());
		setupApplication.calculateSourcesSinksEntrypoints(sAs.toString());
		soot.G.reset();
		
		Options.v().set_src_prec(Options.src_prec_apk);
		Options.v().set_process_dir(Collections.singletonList(apk.toString()));
		Options.v().set_android_jars(androidJars.toString());
		Options.v().set_whole_program(true);
		Options.v().set_allow_phantom_refs(true);
		Options.v().set_output_format(Options.output_format_none);
		Options.v().setPhaseOption("cg.spark", "on");
		Options.v().setPhaseOption("cg.spark", "verbose");
        new SootConfigForAndroid().setSootOptions(Options.v());
		
		Scene.v().loadNecessaryClasses();
		
		
		//Build the call graph
		SootMethod entryPoint = setupApplication.getEntryPointCreator().createDummyMain();
		entryPoint.getActiveBody().validate();
		
		Options.v().set_main_class(entryPoint.getSignature());
		Scene.v().setEntryPoints(Collections.singletonList(entryPoint));
		
		PackManager.v().runPacks();
		
		//Find all methods containing permission requests
		ArrayList<SootMethod> permissionRequests = new ArrayList<SootMethod>();
		try{
			for (SootClass a : Scene.v().getApplicationClasses() ){
				for (SootMethod sm : a.getMethods()){
					if (sm.isConcrete()) {
						Iterator stmtIt = sm.retrieveActiveBody().getUnits().iterator();
						while(stmtIt.hasNext()){
							Stmt stmt = (Stmt) stmtIt.next();
							if(Utils.isPermissionRequest(stmt)){
								//Exclude permission requests contained in the android support lib
								if(!a.getName().startsWith("android.support")){
									permissionRequests.add(sm);
								}
							}
						}
					}
				}
			}
		} catch (Exception e) {
		   System.out.println(e.getMessage());
		}
		
		if(!permissionRequests.isEmpty()){
			
			PrintWriter p = new PrintWriter("graph.txt");
			CallGraph cg = Scene.v().getCallGraph();
	        for (Iterator<Edge> edgeIt = cg.iterator(); edgeIt.hasNext(); ) {
	            Edge e = edgeIt.next();
	            if(e.getSrc().toString().contains("Main"))
	            p.println(e);
	        }
			
			for(SootMethod m : permissionRequests){
				System.out.println(m.getName());
				ReachableMethods rm = Scene.v().getReachableMethods();
				System.out.println(rm.contains(m)); // <-- PRINTS FALSE :(
			}
		}`

[app-debug.apk.zip](https://github.com/Sable/soot/files/592126/app-debug.apk.zip)
@StevenArzt @ericbodden

**Comment by jyotigajrani** [comment]
Hello,

Have you solved the problem??
Actually, I am also facing same problem.

Thanks

**Comment by mbenz89** [comment]
This is a very old way of invoking FlowDroid. Can you try this:
```
SetupApplication setupApplication = new SetupApplication(PATH_TO_APK, PATH_TO_PLATFORMS_DIR);
SetupApplication.constructCallgraph()
```

**Comment by jyotigajrani** [comment]
Thanks a lot for reply...
Actually I am not getting method constructCallgraph() in SetupApplication?
Is it version issue?
If yes, which version I have to use.

**Comment by jyotigajrani** [comment]
I downloaded soot-infoflow-android.jar from FlowDroid2.0 (https://github.com/secure-software-engineering/soot-infoflow-android/releases/tag/FlowDroid_2.0) but that also do not show constructCallgraph() method.

**Comment by mbenz89** [comment]
It's the old repository. Have a look here: https://github.com/secure-software-engineering/FlowDroid

**Comment by jyotigajrani** [comment]
Thanks....
It is required methods....
I wish you could help once again..
Earlier I was using dumpCallGraph(Scene.v().getCallGraph()) for callgraph iteration and further tasks; 
However, constructCallgraph() doesnot return anything....so how can I pass the generated CallGraph...
or how can I iterate the callgraph in this case.
Please reply with some code hints, if possible.

Thanks a lot...

**Comment by jyotigajrani** [comment]
Thanks..

**Comment by pavanupb** [comment]
@gianlucascoccia Hope your question is answered.
