### ISSUE TITLE
Cannot generate APK

### ISSUE THREAD

**Issue by khalidal** [soot-oss/soot#679]
I followed the tutorial on how to set soot on eclipse, and I copied "Instrumenting Android Apps with Soot". I generated jimple file for java class. In the tutorial says to run  "-android-jars path/to/android-platforms -process-dir your.apk" to generate APK file. I am using eclipse to the instrumentation. How do I generate APK file in eclipse? and this is my code:

	public static void main(String[] args) {
		
		//prefer Android APK files// -src-prec apk
		
		
		//output as APK, too//-f J
		
		Options.v().set_src_prec(Options.src_prec_apk);
		Options.v().set_output_format(Options.output_format_dex);
	
		 final String apk = "./apk/RV2013.apk";
	     final String androidJAR = "./lib/android.jar";
			G.reset();
			Options.v().set_allow_phantom_refs(true);
			Options.v().set_src_prec(Options.src_prec_apk);
			Options.v().set_output_format(Options.output_format_dex);
			//Options.v().set_output_format(Options.output_format_jimple);
			Options.v().set_android_jars(androidJAR);
			Options.v().set_process_dir(Collections.singletonList(apk));
			Options.v().set_src_prec(Options.src_prec_apk);
			Options.v().set_soot_classpath(androidJAR);
			Scene.v().loadNecessaryClasses();
			
	       
			
		
        // resolve the PrintStream and System soot-classes
		Scene.v().addBasicClass("java.io.PrintStream",SootClass.SIGNATURES);
        Scene.v().addBasicClass("java.lang.System",SootClass.SIGNATURES);
        
        

        PackManager.v().getPack("jtp").add(new Transform("jtp.myInstrumenter", new BodyTransformer() {

			@Override
			protected void internalTransform(final Body b, String phaseName, @SuppressWarnings("rawtypes") Map options) {
				final PatchingChain<Unit> units = b.getUnits();
				
				//important to use snapshotIterator here
				for(Iterator<Unit> iter = units.snapshotIterator(); iter.hasNext();) {
					final Unit u = iter.next();
					u.apply(new AbstractStmtSwitch() {
						
						public void caseInvokeStmt(InvokeStmt stmt) {
							InvokeExpr invokeExpr = stmt.getInvokeExpr();
						//	if(invokeExpr.getMethod().getName().equals("onDraw")) {

								Local tmpRef = addTmpRef(b);
								Local tmpString = addTmpString(b);
								
								  // insert "tmpRef = java.lang.System.out;" 
						        units.insertBefore(Jimple.v().newAssignStmt( 
						                      tmpRef, Jimple.v().newStaticFieldRef( 
						                      Scene.v().getField("<java.lang.System: java.io.PrintStream out>").makeRef())), u);

						        // insert "tmpLong = 'HELLO';" 
						        units.insertBefore(Jimple.v().newAssignStmt(tmpString, 
						                      StringConstant.v("HELLO")), u);
						        
						        // insert "tmpRef.println(tmpString);" 
						        SootMethod toCall = Scene.v().getSootClass("java.io.PrintStream").getMethod("void println(java.lang.String)");                    
						        units.insertBefore(Jimple.v().newInvokeStmt(
						                      Jimple.v().newVirtualInvokeExpr(tmpRef, toCall.makeRef(), tmpString)), u);
						        
						        //check that we did not mess up the Jimple
						        b.validate();
						//	}
						}
						
					});
				}
			}

		}));
		
        soot.Main.main(args);
   
		
	}

**Comment by Msbeih** [comment]
?

**Comment by pavanupb** [comment]
@khalidal Please re-open the issue if this is still relevant.
