### ISSUE TITLE
Syntax errors in Java source input are ignored

### ISSUE THREAD

**Issue by Waldo1637** [soot-oss/soot#685]
Consider the java file `SyntaxTest.java` with the following contents (with syntax errors):
```java
public class SyntaxTest {
    public static void main(String[] args) {
        syntaxErr_noSemicolon();
        syntaxErr_extraSymbol();
    }
    private static double syntaxErr_noSemicolon() {
        double val = 123.3
        return val
    }
    private static int syntaxErr_extraSymbol() {
        int val += 12;
        return val;
    }
}
```
Running `java -jar soot-trunk.jar -pp -cp . SyntaxTest` does not report the syntax errors but instead produces a `SystaxTest.class` as output with a close approximation of the code!

Consider another example, `SyntaxTest2.java` that contains a try-with-resources, a feature not supported in the current version of JustAddJ, so effectively a syntax error:
```java
import java.util.Scanner;
public class SyntaxTest2 {
    public static void main(String[] args) {
	String s = null;
        try (Scanner input = new Scanner(System.in)) {
            s = input.nextLine();
        }
    }
}
```
Running `java -jar soot-trunk.jar -pp -cp . SyntaxTest2` does not report the syntax errors but instead produces a `SystaxTest2.class` as output. This time, the generated class file is not even in valid class file format.

**Comment by Waldo1637** [comment]
In `soot.JastAddInitialResolver#formAst(...)`, the `CompilationUnit`, `u`,  contains the syntax errors in an internal collection (i.e. `parseErrors`) but `CompilationUnit#errorCheck(errors)` (call in [line 58](https://github.com/Sable/soot/blob/develop/src/soot/JastAddInitialResolver.java#L58)) does not propagate the syntax errors to the parameter `errors` as it does for the semantic errors.

**Comment by pavanupb** [comment]
@Waldo1637 Please re-open the issue if this is still relevant.

**Comment by Waldo1637** [comment]
My initial comment provided two complete test cases and the command line to run them so you should be able to just run those and see if the resulting class file will execute in the JVM. I am not currently running the most recent version of Soot so I cannot easily check if the issue has been resolved.

**Comment by mbenz89** [comment]
Soot's Java frontend is no longer maintained. At some point, Soot will get a new source code frontend which hopefully is not affected by this bug then.
