### ISSUE TITLE
how to transform the lookupswitchStmt into a sequence IfStmt in the Jimple

### ISSUE THREAD

**Issue by nuaa040840308** [soot-oss/soot#688]
I want to execute each case of a switch control. Thus, I need to transform the lookupswtichStmt into a sequence of IfStmts.
Could someone give me some advice about doing this?

**Comment by martinschaef** [comment]
I wrote some code for that a while ago [here](https://github.com/jayhorn/jayhorn/blob/devel/soottocfg/src/main/java/soottocfg/soot/transformers/SwitchStatementRemover.java).

**Comment by pavanupb** [comment]
@nuaa040840308 Please re-open if this issue is still relevant.
