### ISSUE TITLE
Tag annotations do not work (properly) in Java files

### ISSUE THREAD

**Issue by alshain** [soot-oss/soot#69]
The null pointer analysis example as described in the [Soot survivor's guide, page 20](http://www.brics.dk/SootGuide/sootsurvivorsguide.pdf) does not have Eclipse show any markers whatsoever.

In my own examples, I got `StringTag` that I put on statements to show up as a marker in Eclipse, if and only if I pass the `--keep-line-numbers` option.

Manually tagging `ValueBox`es has the same effect as running the NullPointerColorer example.

The XML file records _all_ tags, however, some information is lost:
- For `ColorTag`s on statements, the line is recorded, `spos` and `epos` are zero. -> No marker generated
- For `StringTag`s on statements, the line is recorded, `spos` and `epos` are zero -> Marker generated, hint shown on hover.
- For `StringTag` in combination with `ColorTag`, it works the same as for `StringTag`, but still no highlight shown.
- For String/ColorTags on ValueBoxes, line information is lost completely, as are `epos` and `spos`

The Jimple position information is saved correctly in all cases.

**Comment by pavanupb** [comment]
Closed due to inactivity. Please re-open if still relevant.
