### ISSUE TITLE
GC Memory Limit Exceeded error in FlowDroid

### ISSUE THREAD

**Issue by Garima0002** [soot-oss/soot#691]
Dear Sir,

I am trying to analyse the Real-time applications on the FlowDroid. It determines the sources and sinks but after that, it goes out of memory.

I have used 128 heap memory to run the analysis with the default options. The applications I have used are of size 6-10GB  

![hdfc-gc overhead](https://cloud.githubusercontent.com/assets/25261833/22237731/b119ba9a-e233-11e6-8b84-d84951feab7b.png)

Sir can Flowdroid do analysis on mutlicores?

Thanks in advance.

**Comment by ericbodden** [comment]
You have used 128 GB?

Cheers
Eric

**Comment by Garima0002** [comment]
Yes sir.

**Comment by pavanupb** [comment]
@Garima0002 Closed due to inactivity. Please re-open if still relevant.
