### ISSUE TITLE
The declared package "soot.toolkits.scalar" does not match the expected package ""

### ISSUE THREAD

**Issue by Giovarco** [soot-oss/soot#694]
Hello,

I copied and pasted [GuaranteedDefs example](https://svn.sable.mcgill.ca/soot/soot/releases/soot-2.3.0/src/soot/toolkits/scalar/GuaranteedDefs.java) in Eclipse, but when I try to compile the code an error happens:

**The declared package "soot.toolkits.scalar" does not match the expected package ""**

What does it mean?

Moreover, what is the easiest way to create an unit graph to input to GuaranteedDefs?

**Comment by pavanupb** [comment]
@Giovarco Closed due to inactivity. Please re-open if still relevant.
