### ISSUE TITLE
A question regarding use-original-names

### ISSUE THREAD

**Issue by anantoni** [soot-oss/soot#709]
Hello everyone,

I'm trying to produce correct Jimple for the following program: 

```
package demo;

import extras.*;

import java.util.ArrayList;
import java.util.List;

public class Main {

    public static void main(String[] args) {

        List<Test> mylist1 = new ArrayList<>();
        List<Test2> mylist2 = new ArrayList<>();
        mylist1.add(new Test());
        mylist2.add(new Test2());

        for (Test element : mylist1) {
            element.speak();
        }

        for (Test2 FOO : mylist2) {
            FOO.speak();
        }
    }
}
```

My initial problem (from last year) was that naming the variable in the second loop "element" instead of FOO, would lead Soot to producing Jimple that was declaring "element" with two different types (Test, Test2). 

I think the commit by @StevenArzt  on 02/03/2017 with the fix in the Local Packer tries to handle this issue temporarily, so the second "element" variable becomes something like "element#4" since it is not packed with the rest of the split element variables.

 What I did not expect however, is the behaviour I'm witnessing for the piece of code I post. Variable "FOO" seems to have been missed entirely and "element#4" is used for the second loop. I'm using the latest soot-trunk.jar but I also tried to disable all the transformers running in JimpleBodyPack prior to the Local Packer in the Soot source and retried, however the problem seems to occur at the early stages of the pipeline when the Jimple body for the method is intially produced. So I end up with the following Jimple code:

```
public class demo.Main extends java.lang.Object
{

    public void <init>()
    {
        demo.Main this;

        this := @this: demo.Main;

        specialinvoke this.<java.lang.Object: void <init>()>();

        return;
    }

    public static void main(java.lang.String[])
    {
        java.lang.String[] args;
        java.util.ArrayList $r0, $r1;
        extras.Test $r2, element;
        extras.Test2 $r3, element#4;
        boolean $z2, $z3;
        java.lang.Object $r4, $r5;
        java.util.Iterator l3;

        args := @parameter0: java.lang.String[];

        $r0 = new java.util.ArrayList;

        specialinvoke $r0.<java.util.ArrayList: void <init>()>();

        $r1 = new java.util.ArrayList;

        specialinvoke $r1.<java.util.ArrayList: void <init>()>();

        $r2 = new extras.Test;

        specialinvoke $r2.<extras.Test: void <init>()>();

        interfaceinvoke $r0.<java.util.List: boolean add(java.lang.Object)>($r2);

        $r3 = new extras.Test2;

        specialinvoke $r3.<extras.Test2: void <init>()>();

        interfaceinvoke $r1.<java.util.List: boolean add(java.lang.Object)>($r3);

        l3 = interfaceinvoke $r0.<java.util.List: java.util.Iterator iterator()>();

     label1:
        $z2 = interfaceinvoke l3.<java.util.Iterator: boolean hasNext()>();

        if $z2 == 0 goto label2;

        $r5 = interfaceinvoke l3.<java.util.Iterator: java.lang.Object next()>();

        element = (extras.Test) $r5;

        virtualinvoke element.<extras.Test: void speak()>();

        goto label1;

     label2:
        l3 = interfaceinvoke $r1.<java.util.List: java.util.Iterator iterator()>();

     label3:
        $z3 = interfaceinvoke l3.<java.util.Iterator: boolean hasNext()>();

        if $z3 == 0 goto label4;

        $r4 = interfaceinvoke l3.<java.util.Iterator: java.lang.Object next()>();

        element#4 = (extras.Test2) $r4;

        virtualinvoke element#4.<extras.Test2: void speak()>();

        goto label3;

     label4:
        return;
    }
}

```

My understanding is that both the types and names (when enabling use-original-names) of variables in Jimple are inferred, but while I understand the complication of having multiple variables with the same name in different scopes of the same method I have not found the root cause for this particular example where the variables have different names.

Based on the above I would like to ask whether this is the expected behaviour at the moment and whether you have in mind a potential fix for this. It is probably worth mentioning that I'm producing Jimple from Java bytecode rather than Java source code. 

With the latest soot-trunk.jar use-original-names produces "l*" variables when running java-to-jimple, which I think means that it can't infer the correct names for the variables. However, a few days ago java-to-jimple produced the same behaviour as bytecode-to-jimple if I remember correctly.

In general, whenever I have access the source code of a program would you advise me to run java-to-jimple with use-original-names instead of bytecode-to-jimple or is the pipeline pretty much the same (Something like java->bytecode->jimple) so it would lead to identical results?

The source code is the following:
[demo-src.tar.gz](https://github.com/Sable/soot/files/847401/demo-src.tar.gz)

The commands I'm issuing are:

`java -cp soot-trunk.jar soot.Main -process-dir demo.jar -f J -d out -p jb use-original-names
`
for bytecode-to-jimple, and

`java -cp soot-trunk.jar soot.Main -process-dir demo-src -f J -d out -p jb use-original-names
`
for java-to-jimple.

Best regards,
Anastasios

**Comment by pavanupb** [comment]
@anantoni Closed due to inactivity. Please re-open if still relevant.
