### ISSUE TITLE
How to build soot? Update listed dependencies

### ISSUE THREAD

**Issue by alshain** [soot-oss/soot#71]
I tried cloning the repo to develop on the Eclipse plugin myself, however, the Eclipse project depends on the soot project, which I was unable to build.

The README.md says that the project depends on jasmin and heros, I cloned them both and built them.

Next I got an error about SootJastAddJ being missing. Googling revealed this and I imported the Eclipse project:

```
https://svn.sable.mcgill.ca/abc/trunk/JastAddExtensions/
```

The build of soot now progresses further until the following error:

```
eclipse-ee-3.7-indigo-workspace\JastAddExtensions\SootJastAddJ\build.xml:18: taskdef class JFlex.anttask.JFlexTask cannot be found
```

I don't know how to continue. What do I have to do?

**Comment by seanmkauffman** [comment]
I'm attempting to build soot from source and running into many of the same problems experienced by users on this bug report.  It seems that the build script was never fixed and good instructions do not exist.  It seems to me that, if the problem was never fixed, the bug should stay open.

**Comment by StevenArzt** [comment]
@seanmkauffman Please provide the exact steps you took in an attempt to build Soot and the results you got. Note that unless you are directly working on the Soot source code (adding features, fixing bugs, etc.), you are recommended to use the nightly builds we provide. They are created in a controlled environment and reliable.

**Comment by sohah** [comment]
I am having the same problem with building soot! Used Soot 2.5.0, tried to set the ant.settings but ran into dependencies problems. I am now cloning the development branch and I tried to run the local-nightly build but still received an error while building hero for not being able to find slf4j-simple-1.7.5.jar, and when I worked around that now i'm having another error from local-nightly build "cp: /Users/sohahussein/autobuild/settings/soot/ant.settings.template: No such file or directory".
It has taken too long from me already to try to build Soot. Can someone please provide me with a clear instruction on how to build Soot?

**Comment by anddann** [comment]
@sohah I'm building Soot on the command line using the following steps:
- clone the 'develop' branch
- rename `ant.settings.template` to `ant.settings`
- run `ant options`
- run `ant singletons`
- run `mvn clean compile package`
All build artifacts are stored in the folder target/.
However, you can download a complete soot bundle from https://soot-build.cs.upb.de/nightly/

**Comment by sohah** [comment]
@anddann Thanks a lot!. I followed exactly your steps and things were great until the very last maven command, i received this error "sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target ".

here
[ERROR] Failed to execute goal on project soot: Could not resolve dependencies for project ca.mcgill.sable:soot:jar:3.0.0-SNAPSHOT: Failed to collect dependencies at heros:heros:jar:0.0.1-SNAPSHOT: Failed to read artifact descriptor for heros:heros:jar:0.0.1-SNAPSHOT: Could not transfer artifact heros:heros:pom:0.0.1-SNAPSHOT from/to soot-snapshot (https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-snapshot/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.


Any idea what is going on? 

Many Thanks!

**Comment by anddann** [comment]
@sohah Which java version do you use?
Soot's nexus server https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-snapshot/ is reachable via https using let's encrypt certificates.
Some older java/maven versions do not support/reject them.
I'm using java 1.8.0_144.

**Comment by sohah** [comment]
@anddann It worked like a charm! It was the java version. Many thanks!

**Comment by sohah** [comment]
@anddann I am having a problem running it. I am running the sootclasses-trunk. I am getting an error when I run 
java -jar sootclasses-trunk.jar -cp /Users/sohahussein/git/sootbranch/soot/libs/polyglot.jar:/Users/sohahussein/Downloads/jasminclasses-2.5.0.jar soot.Main -cp  .:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/rt.jar Hello


Soot started on Tue Sep 19 04:33:45 CDT 2017
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/cache/CacheLoader
	at soot.Scene.tryLoadClass(Scene.java:815)
	at soot.Scene.loadBasicClasses(Scene.java:1498)
	at soot.Scene.loadNecessaryClasses(Scene.java:1581)
	at soot.Main.run(Main.java:250)
	at soot.Main.main(Main.java:147)
Caused by: java.lang.ClassNotFoundException: com.google.common.cache.CacheLoader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more


Thanks a lot!

**Comment by anddann** [comment]
By default maven does not include any dependencies in the resulting jar file `sootclasses-trunk.jar` specifies them in the file `sootclasses-trunk.jar:META-INF/maven/pom.xml`.
If you need a full soot jar including all dependencies run `mvn assembly:single`
The resulting jar file `sootclasses-trunk-jar-with-dependencies.jar` contains all dependencies.
Or use the provided jar file https://soot-build.cs.upb.de/nightly/

**Comment by sohah** [comment]
Worked! with sootclassesdependencies.jar. Thanks a lot.
