### ISSUE TITLE
Point-To Analysis for Field Definition

### ISSUE THREAD

**Issue by llmhyy** [soot-oss/soot#716]
Hi all,
I am using GeomPTA/Spark to apply point-to analysis of my code. It seems some alias variable is missing in the result. I am not sure whether it is problem of how I use the Soot API.

The example code is as follows:
```
1.  class QuickSort{
2.  int[] arr;
3.  public int[] sort(int[] array) {
4.  	arr = array;
5.  //	qSort(0, arr.length - 1);
6.  	return arr;
7.  }
	
8.  public static void main(String[] arg){
9.  	int[] unsortedArray = new int[]{10, 3, 2,6,7,12,9,1,1,2};
10.	QuickSort sort = new QuickSort();
11.	int[] expected = sort.sort(unsortedArray);
12.}
13.}
```
I am trying to analyze the alias variable of `unsortedArray`. I used both GeomPTA and Spark with the following code:
```
PointsToAnalysis pta = Scene.v().getPointsToAnalysis();
PAG geomPTA = (PAG) pta;
PointsToSet set = geomPTA.reachingObjects((Local) val);
```
The above `val` is the `unsortedArray` variable, in the set, I can only find the `AllocNode` of 1 newarray (int)[10] in method `main`. However, isn't field `arr` (i.e., `arr=array` in line 4 ) should be included? Moreover, I cannot use `PAG.reachingObject()` method to search for points-to set for an instance field. Can anyone indicate how to do it? 

I am looking forward to your advice and help!

**Comment by pavanupb** [comment]
@llmhyy Closed due to inactivity. Please re-open if still relevant.
