### ISSUE TITLE
Option for number of threads to use

### ISSUE THREAD

**Issue by tim-hoffman** [soot-oss/soot#719]
There should be an option to explicitly set the number of threads to use in `PackManager#runBodyPacks(java.util.Iterator)` instead of always using `Runtime.getRuntime().availableProcessors()` in case some packs/transformers added by the user are not thread safe so the user wishes to revert to using a single thread.

**Comment by pavanupb** [comment]
@Waldo1637 Closed due to inactivity. Please re-open if still relevant.

**Comment by Waldo1637** [comment]
A quick look at the source shows nothing has changed so I'm not sure why this was closed.
See: https://github.com/soot-oss/soot/blob/3e9684eeac5611c4baed73eefb1738383063db6c/src/main/java/soot/PackManager.java#L654

**Comment by mbenz89** [comment]
@Waldo1637 Would you like to propose a PR for this issue?
