### ISSUE TITLE
Pointer Assignment Graph

### ISSUE THREAD

**Issue by Roy-NJU** [soot-oss/soot#721]
Hi:
   Who knows the meaning of the numbers in a pag, and how can we generate the pag visually（get the pointer sets each variable points to）? Following is the segment of the pag:
Allocations:
1 1 1 1
2 1 1 2
3 1 1 3
4 2 1 1
4 2 1 2
4 3 1 1
4 4 1 1
4 1 2 1
4 5 1 1
4 1 1 4
4 3 1 2
4 6 1 1
4 7 1 1
4 8 1 1
4 9 1 1
4 1 1 5
4 1 3 1
4 1 1 6
4 1 1 7
4 1 1 8
4 1 1 9
4 8 1 2
4 10 1 1
Declared Types:
1 1
1 152
1 153
1 154
2 2
2 152
2 153
2 154
3 3
3 152
3 153
3 154
4 4
4 152
4 153

**Comment by pavanupb** [comment]
@Roy-NJU Please re-open if the issue is still relevant
