### ISSUE TITLE
CombinedDUAnalysis doesn't converge 

### ISSUE THREAD

**Issue by YjyJeff** [soot-oss/soot#727]
I want to use CombineDUAnalysis to get the DU-Chain of a method. However, I find that given some method, the CombinedDUAnalysis doesn't converge(It will not stop run forever). My code is very simple:
`CombinedDUAnalysis cdua = new CombinedDUAnalysis(graph)`
Why does the algorithm doesn't converge ? It's a bug of the algorithm of my method? How to fix it ? Thanks in advance !

**Comment by pavanupb** [comment]
@YjyJeff Closed due to inactivity. Please re-open if still relevant.
