### ISSUE TITLE
Spark callgraph missing edge for "println" function

### ISSUE THREAD

**Issue by Waldo1637** [soot-oss/soot#729]
Test case:
``` 
public static void main(String[] args) {
        System.out.println("hello");
    }
```
Running Soot in whole-shimple mode with cg.spark enabled, the generated call graph does not contain an edge out of the statement (see`CallGraph#edgesOutOf`) to the `<java.io.PrintStream: void println(java.lang.String)>` function as expected. However, if cg.spark is not enabled (i.e. the default CHA is used), then the call graph does contain the expected edge.

**Comment by Waldo1637** [comment]
It seems the issue is actually due to another option I was using: -no-bodies-for-excluded. It's not clear to me why not loading bodies for the internal JDK methods would prevent the call graph construction from recognizing them as the target for an invoke statement. Shouldn't resolving the method at level "SIGNATURES" be sufficient to tell if the method has a body (i.e. non-abstract) and can be called by a particular invoke statement?

**Comment by pavanupb** [comment]
@Waldo1637 Closed due to inactivity. Please re-open if still relevant.
