### ISSUE TITLE
Bad dex header output

### ISSUE THREAD

**Issue by ftc** [soot-oss/soot#731]
I have been using Soot for Android instrumentation and the dex output recently broke (it seems to be working with a 7 month old nightly build jar).  I have tried the most basic operation of reading a dex file in and printing it back out, however it still results in a dex file which will not load on a phone.  I would be happy to upload the dex file as well, ~~however it is just a very simple example application and I believe the problem is reproducible with most any android apk.~~

```
        Options.v().set_src_prec(Options.src_prec_apk)
        Options.v().set_output_format(Options.output_format_dex)
        Options.v().set_android_jars(config.androidJars)
        Options.v().set_allow_phantom_refs(true)
        Options.v().set_whole_program(true)
        Options.v().set_process_dir(List(config.apkPath).asJava)
        Options.v().set_output_dir(config.outputDir)
        Options.v().set_keep_line_number(true)
        Options.v().set_process_multiple_dex(true)
        val path: String = Scene.v().getSootClassPath
        Scene.v().setSootClassPath(path + ":" + config.instDir +":" + sys.env("JAVA_HOME") + "/jre/lib/rt.jar")

        PhaseOptions.v().setPhaseOption("cg", "enabled:false");

        val config1: Array[String] = TraceRunnerOptions.getSootConfig(config)

        soot.Main.main(config1);

```

**Comment by ftc** [comment]
Edit: it appears to only happen when I run it on projects I created and not in general. I have uploaded an APK that causes the failure here:



[app-debug.apk.zip](https://github.com/Sable/soot/files/988488/app-debug.apk.zip)

**Comment by ftc** [comment]
Workaround:

Change the constructor in DexPrinter.java to the following:
```
	public DexPrinter() {
		int api = Scene.v().getAndroidAPIVersion();
		if(api > 23)
			api = 23;
		Opcodes opcodes = Opcodes.forApi(api);
		dexFile = new DexBuilder(opcodes);
	}
```

I think this may be a problem with dexlib2.  I am going to post an issue there as well, unfortunately I am not sure how to test dexlib2 outside of soot.

**Comment by pavanupb** [comment]
@ftc Closed due to inactivity. Please re-open if still relevant.
