### ISSUE TITLE
Paddle is no longer compatible with Soot

### ISSUE THREAD

**Issue by Waldo1637** [soot-oss/soot#737]
The most recent version of Paddle that I am able to find (https://github.com/Sable/paddle or https://svn.sable.mcgill.ca/soot/paddle/) uses classes that are no longer a part of Soot.
Specifically, `soot.jimple.paddle.DependencyManager` references `soot.util.Heap` which was removed from Soot on Aug 5, 2014 (bf80f84f02b0c019210335cc3befb1fbb27fcf89). Is there a newer version of Paddle available anywhere or is it no longer supported?

**Comment by ericbodden** [comment]
Hmm, to me this looks like a bit of an over-eager cleanup back in 2014. @StevenArzt would you mind reverting the commit (bf80f84)? We can then think about removing this package for the next major release.

**Comment by pavanupb** [comment]
@Waldo1637 Closed due to inactivity. Please re-open if still relevant.
