### ISSUE TITLE
Error :  Trying to create interface invoke expression for non-interface type

### ISSUE THREAD

**Issue by ddecadall** [soot-oss/soot#738]
Hi, All. I want to insert  toString() method between getText() and toString() into follow code:
   $r2 = $r0.<de.ecspride.RV2013: android.widget.EditText phoneNr>
   $r5 = virtualinvoke $r2.<android.widget.EditText: android.text.Editable getText()>()
   $r6 = interfaceinvoke $r5.<android.text.Editable: java.lang.String toString()>()
I first find the unit of  line 2 and then find the local of $r5 and construct new interfaceinvokeexpr by Jimple.v().newInstanceInvokeExpr(),  however it seems that  it cant create interface invoke expression for non interface type,   can you please tell me where is the error.  my code is as follow:

    `DefinitionStmt tmp_assign =(DefinitionStmt)u;
     Value tmp_value = tmp_assign.getLeftOp();
     Local tmp_local = (Local) tmp_value;
     InterfaceInvokeExpr tmp_interfaceinvokeExpr =  
                                            generateToStringMethod(body,tmp_local);`

    InterfaceInvokeExpr generateToStringMethod(Body body, Local edittext){
    	    SootMethod tostringmethod = Scene.v().getMethod("<java.lang.Object: java.lang.String toString()>");
           InterfaceInvokeExpr tmp_expr =   Jimple.v().newInterfaceInvokeExpr(edittext, tostringmethod.makeRef());
    	return tmp_expr;
    }

**Comment by pavanupb** [comment]
@ddecadall Closed due to inactivity. Please re-open if still relevant.
