### ISSUE TITLE
InternalTypingError when analyzing a library .apk generated from .jar by dx.jar

### ISSUE THREAD

**Issue by AndyXan** [soot-oss/soot#743]
Complex Title for describing a trivial problem.

I'm analysing Android Libraries with soot. In this process i'm taking libraries from the maven repository in .aar / .jar format and transform them into .apk with the standard android tool dx.jar (25) and multi-dex enabled, resulting in a simple .apk file. 

For 2000 cases, soot can analyse those files without problem, for one case theres an internal typing error exception. This only happens when analysing the .apk file generated with dx.jar, not with the original .jar version of the library.

Short Version: Tested with current nightly build (30.05.2017)
```
Works Fine!
java -jar ./soot-trunk.jar -cp .:/opt/oracle_java/jdk1.8.0_111/jre/lib/rt.jar -allow-phantom-refs -output-format jimple -process-dir jdom_b6.jar -d output/

Transform:
java -jar /home/wittmann/Android/Sdk/build-tools/25.0.0/lib/dx.jar --dex --multi-dex --verbose --no-optimize --output=jdom_b6.apk jdom_b6.jar

Fails:
java -jar ./soot-trunk.jar -cp .:/opt/oracle_java/jdk1.8.0_111/jre/lib/rt.jar -android-jars ~/Android/Sdk/platforms/android-25/android.jar -src-prec apk -allow-phantom-refs -output-format jimple -process-dir jdom_b6.apk -d output/
 
Unexpected type null
	at soot.jimple.toolkits.typing.integer.ClassHierarchy.typeNode(ClassHierarchy.java:181)
	at soot.jimple.toolkits.typing.integer.TypeResolver.typeVariable(TypeResolver.java:102)
	at soot.jimple.toolkits.typing.integer.ConstraintCollector.caseAssignStmt(ConstraintCollector.java:401)
	at soot.jimple.internal.JAssignStmt.apply(JAssignStmt.java:238)

At Chain Entry: 77, JAssStmt: tmp$1152991394 = ([0..1]) tmp$52104962 
in Method: <org.jdom.output.XMLOutputter: void printElementContent(org.jdom.Element,java.io.Writer,int,org.jdom.output.NamespaceStack,java.util.List)>

```

[apkandjar.zip](https://github.com/Sable/soot/files/1038162/apkandjar.zip)

**Comment by pavanupb** [comment]
@AndyXan Closed due to inactivity. Please re-open if still relevant.
