### ISSUE TITLE
VEX IR exporter

### ISSUE THREAD

**Issue by fabiox77** [soot-oss/soot#746]
Hi all,
Have you ever thought to improve soot allowing him to export into VEX IR?

Thanks

**Comment by ericbodden** [comment]
Hello.

I remember I briefly looked into it but currently we are lacking the resources to implement this. It would be a welcome extension to Soot!

Cheers
Eric

**Comment by fabiox77** [comment]
Hello,
Thanks for your answer. Could you give us an idea how this should be implemented? What format is easier to translate into VEX?

Thanks

**Comment by pavanupb** [comment]
@fabiox77 Closed due to inactivity. Please re-open if still relevant.
