### ISSUE TITLE
Information about SootField

### ISSUE THREAD

**Issue by thiagodnf** [soot-oss/soot#749]
Hello, how are you? I have a good question for you.

Is it possible to know which SootField is called/accessed by a SootMethod? Or, which are the SootFields that a SootMethod calls? I think that CallGraph does not have this information.

Thanks for helping me

**Comment by ericbodden** [comment]
Hi.

A Callgraph is the right data structure to use if you want to know which methods are called by a given method. If you want to know which fields are being accessed you will have to find this out manually:

- Traverse the method’s JimpleBody, looking at each individual Stmt.
- Inspect the Stmt to see if it contains a field reference:
https://www.sable.mcgill.ca/soot/doc/soot/jimple/Stmt.html#containsFieldRef()
- Extract the field reference using:
https://www.sable.mcgill.ca/soot/doc/soot/jimple/Stmt.html#getFieldRef()

Cheers
Eric

**Comment by thiagodnf** [comment]
Thanks @ericbodden 

I have another question. Is there some option to find all relationship (or call) among methods even a method that it is never called? I found that a method should be called to appear on CallGraph, doesn't it?

**Comment by pavanupb** [comment]
@thiagodnf Closed due to inactivity. Please re-open if still relevant.
