### ISSUE TITLE
Query about soot.Type

### ISSUE THREAD

**Issue by DongShuaike** [soot-oss/soot#751]
Hi, I was working on analyzing methods used in android apps. However, some functions are overloaded which makes getting the SootMethod using only function name difficult. I referred to some early-posted blogs and found that there are two ways to deal with it. 1. `Using the signature of the method`. 2. `Using the parameterList to distinguish.`. However, the material illustrating how to define `customized Type` seems scarce.

The signature of that method is `<com.baidu.android.a.d.c: java.lang.String a(android.content.Context,java.lang.String)>` and the code I was using is like below. 

    PackManager.v().getPack("wjtp").add(new Transform("wjtp.myTransform", new SceneTransformer() {
    @Override
    protected void internalTransform(String phaseName, Map<String, String> options) {
        SootClass a = Scene.v().getSootClass("com.baidu.android.a.d.c");

        Type type_context = new Type() {
            @Override
            public String toString() {
                return "android.content.Context";
            }
        };
        Type type_string = new Type() {
            @Override
            public String toString() {
                return "java.lang.String";
            }
        };

        LinkedList<Type> llst = new LinkedList<>(Arrays.asList(type_context, type_string));
        SootMethod src = a.getMethod("a",llst);
        //<com.baidu.android.a.d.c: java.lang.String a(android.content.Context,java.lang.String)>	[android.content.Context, java.lang.String]

        /*
        * If there are lots of methods with the same name, a RuntimeException will be thrown saying "ambiguous method"
        * To avoid this error, use getMethod(String name, List parameterTypes) instead.
        * */
        printPossibleCallers(src);
        }
    }));
    PackManager.v().runPacks();

The error info is `Exception in thread "main" java.lang.RuntimeException: couldn't find method a([android.content.Context, java.lang.String]) in com.baidu.android.a.d.c`. In my point of view, the way I defined the customized type `android.content.Context` and `java.lang.String` was wrong, but I failed to find the right way to define them.

Besides, there is another question about `signature` and `subsignature`.
When I used `SootMethod src = a.getMethod("<com.baidu.android.a.d.c: java.lang.String a(android.content.Context,java.lang.String)>");` to get a method, an exception is also thrown. What about the right way to get a method object using its signature and what are the differences between `subsignature` and `signature`?

Thanks.

**Comment by pavanupb** [comment]
@DongShuaike Closed due to inactivity. Please re-open if still relevant.
