### ISSUE TITLE
Different call graphs generated when analyzing the same project either in .apk and .class

### ISSUE THREAD

**Issue by frankFic** [soot-oss/soot#758]
Hi,

I am using Soot to analyze Android apps and somehow found out that the call graph generated by Soot when analyzing the generated .apk file is different from the call graph generated for the intermediate .class file.

Specifically I use CHATransformer to generate the call graph:
```
CHATransformer.v().transform();
callGraph = Scene.v().getCallGraph();
```

I was analyzing k-9 mail. 
On line [40 K9AlarmManager.java](https://github.com/k9mail/k-9/blob/master/k9mail/src/main/java/com/fsck/k9/helper/K9AlarmManager.java#L40), it defines a method called `setAndAllowWhileIdle`.
It is invoked on [line 33 in the same class](https://github.com/k9mail/k-9/blob/master/k9mail/src/main/java/com/fsck/k9/helper/K9AlarmManager.java#L33).

When soot is analyzing the .class files, it can identify the call edge but when analyzing the generated .apk file. Soot fails to identify the link.

For your information, I am using the nightly build on 31 Jul.

Thanks in advance for your attention.

**Comment by frankFic** [comment]
I just tested that when using spark, I still have this problem. Please let me know if more information is needed.

**Comment by pavanupb** [comment]
@frankFic Please re-open if this issue is still relevant.
