### ISSUE TITLE
SPARK primitives

### ISSUE THREAD

**Issue by t81lal** [soot-oss/soot#767]
Hi there,
I have been reading through the implementation of SPARK in soot and was wondering why primitive typed variables are not represented in the pointer assignment graph. Could it not be argued that operations producing primitive values create pointers to primitive values? alternatively how would one probe the pointer analysis for the possible runtime values of integer field?
Thanks.

**Comment by TheBiblMan** [comment]
.

**Comment by pavanupb** [comment]
@t81lal Please re-open if this issue is still relevant.
