### ISSUE TITLE
 Soot Instrumentation exception fired while transforming the code 

### ISSUE THREAD

**Issue by maldil** [soot-oss/soot#831]
Hi all,

Following exception is fired while transforming android application back to .apk file, after successful `body.validation()`. I am quite not sure about the exception message. Can anybody explain me about the exception and suggest a way to get rid of the exception ?

**Exception message**
```
[Thread-7] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: There is a path from 'retFragMan = new android.app.FragmentManager' to the usage 'return retFragMan' where <init> does not get called in between.
There is a path from 'retFragMan = new android.app.FragmentManager' to the usage 'return retFragMan' where <init> does not get called in between.
```
**Trace is as below**
```
Transforming android.app.Activity... 
[Thread-7] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: There is a path from 'retFragMan = new android.app.FragmentManager' to the usage 'return retFragMan' where <init> does not get called in between.
There is a path from 'retFragMan = new android.app.FragmentManager' to the usage 'return retFragMan' where <init> does not get called in between.
	at soot.jimple.validation.NewValidator.checkForInitializerOnPath(NewValidator.java:182)
	at soot.jimple.validation.NewValidator.validate(NewValidator.java:77)
	at soot.jimple.JimpleBody.validate(JimpleBody.java:114)
	at soot.jimple.JimpleBody.validate(JimpleBody.java:97)
	at soot.PackManager.runBodyPacks(PackManager.java:975)
	at soot.PackManager.access$000(PackManager.java:112)
	at soot.PackManager$1.run(PackManager.java:620)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "Thread-7" There is a path from 'retFragMan = new android.app.FragmentManager' to the usage 'return retFragMan' where <init> does not get called in between.
	at soot.jimple.validation.NewValidator.checkForInitializerOnPath(NewValidator.java:182)
	at soot.jimple.validation.NewValidator.validate(NewValidator.java:77)
	at soot.jimple.JimpleBody.validate(JimpleBody.java:114)
	at soot.jimple.JimpleBody.validate(JimpleBody.java:97)
	at soot.PackManager.runBodyPacks(PackManager.java:975)
	at soot.PackManager.access$000(PackManager.java:112)
	at soot.PackManager$1.run(PackManager.java:620)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
There is a path from 'retFragMan = new android.app.FragmentManager' to the usage 'return retFragMan' where <init> does not get called in between.
	at soot.jimple.validation.NewValidator.checkForInitializerOnPath(NewValidator.java:182)
	at soot.jimple.validation.NewValidator.validate(NewValidator.java:77)
	at soot.jimple.JimpleBody.validate(JimpleBody.java:114)
	at soot.jimple.JimpleBody.validate(JimpleBody.java:97)
	at soot.PackManager.runBodyPacks(PackManager.java:975)
	at soot.PackManager.access$000(PackManager.java:112)
	at soot.PackManager$1.run(PackManager.java:620)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
RemoteTestNG finishing: 100686 ms
```

**The exception is fired from the below validation.**
```
  while(assignCheck2.hasNext()) {
                        ValueBox box1 = (ValueBox)assignCheck2.next();
                        Value used = box1.getValue();
                        if(aliasingLocals.contains(used)) {
                            exception.add(new ValidationException(newStmt, String.format("There is a path from \'%s\' to the usage \'%s\' where <init> does not get called in between.", new Object[]{newStmt, curStmt})));
                            return false;
                        }
                    }
```

**Comment by mbenz89** [comment]
Hi.

This means you need to add a call to the constructor of the object after creating it and before using it.
Try to insert a “special invoke” call to “<init>” after you insert a “new <Object>” statement.

Manuel



Von: mali <notifications@github.com>
Antworten an: Sable/soot <reply@reply.github.com>
Datum: Montag, 20. November 2017 um 15:44
An: Sable/soot <soot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [Sable/soot] Soot Instrumentation exception fired while transforming the code (#831)


Hi all,

Following exception is fired while transforming android application back to .apk file, after successful body.validation(). I am quite not sure about the exception message. Can anybody explain me about the exception and suggest a way to get rid of the exception ?

[Thread-7] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: There is a path from 'retFragMan = new android.app.FragmentManager' to the usage 'return retFragMan' where <init> does not get called in between.

There is a path from 'retFragMan = new android.app.FragmentManager' to the usage 'return retFragMan' where <init> does not get called in between.

The exception is fired from the below validation.

  while(assignCheck2.hasNext()) {

                        ValueBox box1 = (ValueBox)assignCheck2.next();

                        Value used = box1.getValue();

                        if(aliasingLocals.contains(used)) {

                            exception.add(new ValidationException(newStmt, String.format("There is a path from \'%s\' to the usage \'%s\' where <init> does not get called in between.", new Object[]{newStmt, curStmt})));

                            return false;

                        }

                    }

**Comment by maldil** [comment]
@mbenz89 thank you for your kindness.
Actually I didn't create an object , what I did was
1.  Modified  couple of methods in the application.  (invoked additional methods)
2. Added a parent class to couple of classes. 
Will this has impact on the above exception ?

**Comment by mbenz89** [comment]
I am not sure at this point. Does it also happen if you do not instrument anything? 
Might also be bug in the validator or a special case. Can you try if it occurs even if you do not instrument something?

**Comment by maldil** [comment]
@mbenz89 Thank you for the feedback. 
I ran the instrumentation code again by commenting the modifying code inside the method `protected void internalTransform(String s, Map<String, String> map)`. But the result was same. It fires the above exception. I have attached the relevant .apk file herewith [APK](https://www.dropbox.com/s/yyz385l7zc7wjig/video.mp3converter.apk?dl=0)

**Comment by mbenz89** [comment]
I will have a look at the APK when I have time for it, thanks! I disabled the verifier for now. 
Please retry with the newest build.

**Comment by maldil** [comment]
@mbenz89 thank you for the prompt response. I ran the code again but the exception is still there. I use following version and hope it as the recent build. 
```
<dependency>
            <groupId>ca.mcgill.sable</groupId>
            <artifactId>soot</artifactId>
            <version>3.0.0-SNAPSHOT</version>
</dependency>
``` 
Please let me know once you enable the validation and found the reason for the issue.

**Comment by maldil** [comment]
@mbenz89 I noticed the change 
```
public boolean isBasicValidator() {
        return false;
    }
``` 
is not available in my local repository. I will looking to this. Thank you.

**Comment by mbenz89** [comment]
Yes, they should be pushed. Maybe try to clear your local repository.

@StevenArzt The issue is in `soot.jimple.infoflow.cfg.LibraryClassPatcher#patchActivityGetFragmentManager`, where you create a new instance of a FragmentManager without calling <init> afterward. I would appreciate a fix so that we can enable the `NewValidator` again.

Manuel

**Comment by maldil** [comment]
@mbenz89 thank you for your kind response on this. Please let me know once you enable the validation again.

**Comment by maldil** [comment]
@mbenz89 @StevenArzt 
Even though the basic validator is off `isBasicValidator() { return false; }` some of the exceptions are still firing. Those exceptions are firing even without modifications for the applications. I ran this for several applications and the exceptions are firing for most of the applications. Only small amount of applications were transformed successfully, but those are crashing in the emulator and phone. I opened an issue for this separately. 
I am stuck on this, because applications are not transformable back to apk file even without modifications.   I hope your help on this.

```
[Thread-8] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: 
Warning: Bad use of primitive type at $f1 = $r3[0] in <com.inmobi.re.container.mraidimpl.MRAIDBasic: void getDefaultPosition()> in <com.inmobi.re.container.mraidimpl.MRAIDBasic: void getDefaultPosition()>
```

**Comment by maldil** [comment]
@mbenz89 @StevenArzt 
The issue is still there, (even if the validator is off :O )
Following exception fired for an another application. 
```
Warning: Bad use of primitive type at $f1 = $r3[0] in <com.inmobi.re.container.mraidimpl.MRAIDBasic: void getCurrentPosition()> in <com.inmobi.re.container.mraidimpl.MRAIDBasic: void getCurrentPosition()>
	at soot.validation.CheckTypesValidator.checkCopy(CheckTypesValidator.java:93)
	at soot.validation.CheckTypesValidator.validate(CheckTypesValidator.java:41)
	at soot.Body.validate(Body.java:259)
	at soot.jimple.JimpleBody.validate(JimpleBody.java:109)
	at soot.jimple.JimpleBody.validate(JimpleBody.java:97)
	at soot.PackManager.runBodyPacks(PackManager.java:975)
	at soot.PackManager.access$000(PackManager.java:112)
	at soot.PackManager$1.run(PackManager.java:620)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
Please note that, this is firing without any modification for the application (just only a transformation).

**Comment by mbenz89** [comment]
If you provide me the app and your full configuration, I can have a look at it.

**Comment by maldil** [comment]
@mbenz89 thank you very much for your response. 
the apk is uploaded to below location
1. [APK1](https://www.dropbox.com/s/ocm51l4axx87r2n/alpacasoft.restoreimage.apk?dl=0)
2. [APK2](https://www.dropbox.com/s/yyz385l7zc7wjig/video.mp3converter.apk?dl=0)

The Soot configuration is as below
 ```
public static void init(ARPManifestFile ARPManifestFile) {
        G.reset();
        //  Options.v().allow_phantom_refs();
        SootConfigForAndroid sootConf = new SootConfigForAndroid() {
            @Override
            public void setSootOptions(Options options) {
                super.setSootOptions(options);
                options.v().set_allow_phantom_refs(true);
                options.v().set_whole_program(true);
                options.v().set_prepend_classpath(true);
                options.v().set_validate(true);
                options.v().set_output_format(Options.output_format_dex);
                //  Options.v().set_soot_classpath(manifestFile.getAndroidFilePath());
                log.info("Path " + ARPObjectFactory.v().getARPManifestFile().getAndroidFilePath());
                options.v().set_force_android_jar(ARPObjectFactory.v().getARPManifestFile().getAndroidFilePath());

                options.v().set_soot_classpath(ARPObjectFactory.v().getARPManifestFile().getAndroidFilePath() + ";" +
                        ";D:\\WSU_Project2\\android-platforms-master\\android-Support-libs\\android-19\\android-support.jar");

                options.v().set_src_prec(Options.src_prec_apk);
                // Options.v().set_oaat(true);
                options.v().set_process_dir(Collections.singletonList(Details.APK_PATH));
                options.set_include_all(true);
            }
        };

        analyzer = new SetupApplication(Details.ANDROID_PLATFORMS,Details.APK_PATH);
        analyzer.setSootConfig(sootConf);
        analyzer.getConfig().setTaintAnalysisEnabled(false);
        analyzer.setCallbackFile(Soot.class.getClassLoader().getResource("AndroidCallbacks.txt").getFile());
        analyzer.constructCallgraph();
    }
```

**Comment by maldil** [comment]
@mbenz89 Kind reminder on this. 🥇 :)

**Comment by mbenz89** [comment]
I checked APK1 and I cannot reproduce your error without any instrumentation/transformation of the original code.

This is my configuration (I removed all the unnecessary stuff):
```
public class Main {
    public static void main(String[] args) {
        //  Options.v().allow_phantom_refs();
        SootConfigForAndroid sootConf = new SootConfigForAndroid() {
            @Override
            public void setSootOptions(Options options) {
                options.v().set_allow_phantom_refs(true);
                options.v().set_whole_program(true);
                options.v().set_validate(true);
                options.set_include_all(true);
            }
        };

        SetupApplication analyzer = new SetupApplication("/PATH/TO/ANDROIDSKD/platforms","./PATH/TO/APP/alpacasoft.restoreimage.apk");
        analyzer.setSootConfig(sootConf);
        analyzer.constructCallgraph();

        Options.v().set_output_format(Options.output_format_dex);
        PackManager.v().writeOutput();
    }
}
```

I guess you are introducing the incorrect statement in your transformer.

**Comment by maldil** [comment]
@mbenz89 I updated the Soot configuration as you suggested and run the code again. But the result was same, the exception was fired. (It took very long time to construct the call graph when updated the configurations as you suggested)
Did you set the output configuration as below? 
```
        PackManager.v().getPack("wjtp").add(new Transform("wjtp.myAnalysis", new APKDSceneTransformer(finalChangingMethods)));
        PackManager.v().runPacks();
        PackManager.v().writeOutput();
```
Am I doing something wrong here ?

**Comment by pavanupb** [comment]
@maldil Please re-open if this issue is still relevant.
