### ISSUE TITLE
Getting a SootClass for a loaded Class?

### ISSUE THREAD

**Issue by koradir** [soot-oss/soot#832]
E.g: https://stackoverflow.com/questions/47438377/jimple-representation-from-class-instance

[This](https://raw.githubusercontent.com/wiki/Sable/soot/code/createclass/Main.java) seems to cover converting a `SootClass` to `byte[]`, but I have yet to find anything that would tell me how to get a `SootClass` from a `Class` object.

How do I do this?

**Comment by ericbodden** [comment]
Scene.v().getSootClass(String) ?

Cheers
Eric

**Comment by koradir** [comment]
Doesn't that one assume I already HAVE a `SootClass` somewhere?
At any rate, all I'm getting with that line is 

`Aborting: can't find classfile`

When I try the transformation with ASM, I'm reading the class like

`classReader = new ClassReader(fooClass.getClassLoader().getResourceAsStream( fooClass.getName().replace('.','/') + ".class"));`

where `Class<?> fooClass = Foo.class`

How do I translate that into 

`Scene.v().getSootClass(<???>)`

?

**Comment by mbenz89** [comment]
You might want to have a look at [this](https://github.com/Sable/soot/blob/develop/src/soot/SourceLocator.java#L201). You will need to adapt it to your use-case a bit. The idea is that Soot wil alsol try to locate a class you are searching for with `Scene.v().getSootClass()` in your program's classpath. 

Also, to avoid possible frustration about issues, make sure to use AsmClassSource instead of Coffi. You will also need to set it's constructor to public for that.

This is rather hacky and we might introduce a more convenient solution in the future.

**Comment by koradir** [comment]
@mbenz89 Adding the classfile directory to Soot's classpath does indeed allow me to `loadClassAndSupport` the class into a SootClass I can then compile into a `byte[]` --  which I can then use to reload the class with ByteBudy (although I'll have to make sure to retrieve all methods' bodies first, to make sure they get compiled).

However, let's say I want to add a `System.out.println("Hello World"),` stmt to a method's body.
I cannot do that, apparently, without also loading `System` and `Printstream` into `SootClass`es. And if I try that, [it fails](https://github.com/Sable/soot/issues/833).

Any suggestions? (I load my custom class in much the same way I try to load the `System` class in the issue I linked to, btw, and with options

        Options.v().set_no_bodies_for_excluded(true);
        Options.v().set_allow_phantom_refs(true);
        Options.v().set_debug_resolver(false);
        Options.v().set_keep_line_number(true);
        Options.v().set_no_output_inner_classes_attribute(false);
        Options.v().set_coffi(false);

)

**Comment by mbenz89** [comment]
Have you added the Java libraries to your classpath?

**Comment by pavanupb** [comment]
@koradir Please re-open if this issue is still relevant.
