### ISSUE TITLE
Spark call graph is missing recursion edge

### ISSUE THREAD

**Issue by stefandollase** [soot-oss/soot#835]
The spark call graph construction does not seem to work properly for recursive call graphs.

Given the following example ...

```
public class RecursionExample {
	public void foo() {
		foo();
	}
}
```

... and the following code to analyse the example ...

```
boolean useSpark = true;
File jar = new File("RecursionExample.jar");

Options.v().set_whole_program(true);
Options.v().setPhaseOption("cg", "implicit-entry:false");
Options.v().set_soot_classpath(jar.getAbsolutePath() + ":" + Scene.v().defaultClassPath());
Options.v().set_process_dir(Arrays.asList(jar.getAbsolutePath()));
Options.v().setPhaseOption("cg.cha", "enabled:" + !useSpark);
Options.v().setPhaseOption("cg.spark", "enabled:" + useSpark);
Options.v().setPhaseOption("jb", "use-original-names:true");

SootClass c = Scene.v().forceResolve("RecursionExample", SootClass.BODIES);
c.setApplicationClass();
Scene.v().loadNecessaryClasses();
SootMethod m = c.getMethodByName("foo");
Scene.v().setEntryPoints(Arrays.asList(m));
PackManager.v().runPacks();

System.out.println("start of call graph");
System.out.println(Scene.v().getCallGraph().toString());
System.out.println("end of call graph");
```

... we get an empty call graph:

>[Call Graph] For information on where the call graph may be incomplete, use the verbose option to the cg phase.
[Spark] Pointer Assignment Graph in 0.1 seconds.
[Spark] Type masks in 0.0 seconds.
[Spark] Pointer Graph simplified in 0.0 seconds.
[Spark] Propagation in 0.0 seconds.
[Spark] Solution found in 0.0 seconds.
Transforming RecursionExample... 
start of call graph
>
>end of call graph

However, if we set `useSpark` to `false`, we get an edge in the call graph:

>[Call Graph] For information on where the call graph may be incomplete, use the verbose option to the cg phase.
Transforming RecursionExample... 
start of call graph
VIRTUAL edge: virtualinvoke this.<RecursionExample: void foo()>() in <RecursionExample: void foo()> ==> <RecursionExample: void foo()>
>
>end of call graph

This was tested with *soot-3.0.0-jar-with-dependencies.jar*,  downloaded from [here](https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-release/ca/mcgill/sable/soot/3.0.0/soot-3.0.0-jar-with-dependencies.jar).

**Comment by pavanupb** [comment]
@stefandollase Please re-open if this issue is still relevant.
