### ISSUE TITLE
Exception table is removed when no method is called in try {} block

### ISSUE THREAD

**Issue by Buddy00** [soot-oss/soot#853]
Got the code:

		try {
			byte[] b = new byte[-10];
		} catch(NegativeArraySizeException e) {
			System.err.println("ERR");
		}

->

    public static void main(java.lang.String[])
    {
        java.lang.String[] r0;
        byte[] r1;

        r0 := @parameter0: java.lang.String[];

        r1 = newarray (byte)[-10];

        goto label1;

     label1:
        return;
    }

the System.err.println part is not respected and was removed (but obviously the Syserr part would be called in Java Runtime).

When using:
		try {
			byte[] b = new byte[-10];
			main(args);
		} catch(NegativeArraySizeException e) {
			System.err.println("ERR");
		}

->

    public static void main(java.lang.String[])
    {
        java.lang.String[] r0;
        java.lang.NegativeArraySizeException $r1, r4;
        java.io.PrintStream $r2;
        byte[] r3;

        r0 := @parameter0: java.lang.String[];

     label1:
        r3 = newarray (byte)[-10];

        staticinvoke <TestJava: void main(java.lang.String[])>(r0);

     label2:
        goto label4;

     label3:
        $r1 := @caughtexception;

        r4 = $r1;

        $r2 = <java.lang.System: java.io.PrintStream err>;

        virtualinvoke $r2.<java.io.PrintStream: void println(java.lang.String)>("ERR");

     label4:
        return;

        catch java.lang.NegativeArraySizeException from label1 to label2 with label3;
    }

The Exception Table is back again.

I think the Optimizer ignores that allocating a array with a negative value results in a lowlevel exception throw.

**Comment by pavanupb** [comment]
@Buddy00 Please re-open if this issue is still relevant.
